### ISSUE TITLE
Installation on Anaconda

### ISSUE THREAD

**Issue by skaae** [SeanNaren/deepspeech.pytorch#10]
Hi, 

I have trouble installing the py_torch bindings using anaconda. I'm using Ubuntu 14.04.3, and gcc 5.4.1 and cuda 8. 
Everythings works fine untill i try to import the warp bindings in python:
```Python
>>> from warpctc_pytorch import CTCLoss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sorson/anaconda3/lib/python3.6/site-packages/warpctc_pytorch/__init__.py", line 7, in <module>
    from ._warp_ctc import lib as _lib, ffi as _ffi
ImportError: /home/sorson/anaconda3/lib/python3.6/site-packages/torch/lib/../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/sorson/warp-ctc/build/libwarpctc.so)
```

Output of installation:
```Bash
sorson@phoebe:~/warp-ctc/build$ cmake ..
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "6.5") 
-- cuda found TRUE
CMake Warning at CMakeLists.txt:48 (FIND_PACKAGE):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Torch found Torch_DIR-NOTFOUND
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sorson/warp-ctc/build
```

```Bash
sorson@phoebe:~/warp-ctc/build$ make
[ 25%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o
[ 50%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/./warpctc_generated_ctc_entrypoint.cu.o
Scanning dependencies of target warpctc
Linking CXX shared library libwarpctc.so
[ 50%] Built target warpctc
Scanning dependencies of target test_cpu
[ 75%] Building CXX object CMakeFiles/test_cpu.dir/tests/test_cpu.cpp.o
Linking CXX executable test_cpu
[ 75%] Built target test_cpu
[100%] Building NVCC (Device) object CMakeFiles/test_gpu.dir/tests/./test_gpu_generated_test_gpu.cu.o
Scanning dependencies of target test_gpu
Linking CXX executable test_gpu
[100%] Built target test_gpu
```

```Bash
sorson@phoebe:~/warp-ctc/pytorch_binding$ python setup.py install
generating build/_warp_ctc.c
regenerated: 'build/_warp_ctc.c'
running install
running build
running build_py
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/warpctc_pytorch
copying warpctc_pytorch/__init__.py -> build/lib.linux-x86_64-3.6/warpctc_pytorch
running build_ext
building 'warpctc_pytorch._warp_ctc' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/build
creating build/temp.linux-x86_64-3.6/home
creating build/temp.linux-x86_64-3.6/home/sorson
creating build/temp.linux-x86_64-3.6/home/sorson/warp-ctc
creating build/temp.linux-x86_64-3.6/home/sorson/warp-ctc/pytorch_binding
creating build/temp.linux-x86_64-3.6/home/sorson/warp-ctc/pytorch_binding/src
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sorson/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/sorson/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/sorson/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/sorson/warp-ctc/include -I/home/sorson/anaconda3/include/python3.6m -c build/_warp_ctc.c -o build/temp.linux-x86_64-3.6/build/_warp_ctc.o -std=c++11 -fPIC -DWARPCTC_ENABLE_GPU
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sorson/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/sorson/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/sorson/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/sorson/warp-ctc/include -I/home/sorson/anaconda3/include/python3.6m -c /home/sorson/warp-ctc/pytorch_binding/src/binding.cpp -o build/temp.linux-x86_64-3.6/home/sorson/warp-ctc/pytorch_binding/src/binding.o -std=c++11 -fPIC -DWARPCTC_ENABLE_GPU
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -L/home/sorson/anaconda3/lib -Wl,-rpath=/home/sorson/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.6/build/_warp_ctc.o build/temp.linux-x86_64-3.6/home/sorson/warp-ctc/pytorch_binding/src/binding.o -L/home/sorson/warp-ctc/build -L/home/sorson/anaconda3/lib -Wl,--enable-new-dtags,-R/home/sorson/warp-ctc/build -lwarpctc -lpython3.6m -o build/lib.linux-x86_64-3.6/warpctc_pytorch/_warp_ctc.cpython-36m-x86_64-linux-gnu.so
running install_lib
copying build/lib.linux-x86_64-3.6/warpctc_pytorch/_warp_ctc.cpython-36m-x86_64-linux-gnu.so -> /home/sorson/anaconda3/lib/python3.6/site-packages/warpctc_pytorch
copying build/lib.linux-x86_64-3.6/warpctc_pytorch/__init__.py -> /home/sorson/anaconda3/lib/python3.6/site-packages/warpctc_pytorch
byte-compiling /home/sorson/anaconda3/lib/python3.6/site-packages/warpctc_pytorch/__init__.py to __init__.cpython-36.pyc
running install_egg_info
Removing /home/sorson/anaconda3/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6.egg-info
Writing /home/sorson/anaconda3/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6.egg-info
```

**Comment by SeanNaren** [comment]
Hmm I ran into similar issues some while back and I think it's due to anaconda having it's own gcc compiler.

Could you try forcing the gcc/g++ compiler by adding this in your `~/.bashrc` script:

```
export CC="/usr/bin/gcc"
export CXX="/usr/bin/g++"
```

And then doing a `source ~/.bashrc`, removing the build file in the warp_ctc library and installing again?

**Comment by skaae** [comment]
I Also had that problem untill i checked the path of gcc :)
It seems to be gcc version 5.4.1 that is the problem. I just compiled and imported after changing to 
gcc version 4.8.4

**Comment by SeanNaren** [comment]
That's good to know! thanks for posting the fix :)

**Comment by skaae** [comment]
Thanks for creating the bindings :)

**Comment by dlmacedo** [comment]
Please,

How can a change to gcc 4.8?

David

**Comment by dlmacedo** [comment]
Still not working for me...

**Comment by ahmedmazari** [comment]
@SeanNaren  ,```
 export CC="/usr/bin/gcc"
export CXX="/usr/bin/g++"
```
doesn't work for me.

@skaae , please help.
l have ubuntu 16.04. 
l got the same problem with you when l tested to import `warptc_pytorch`. How did you solve that ? can l put a detailed answer 
"I Also had that problem untill i checked the path of gcc :)
It seems to be gcc version 5.4.1 that is the problem. I just compiled and imported after changing to
gcc version 4.8.4"
How did you change the path of gcc to 4.8.4 and is it on ~/.bashcrc ? thank you for clarifying that.

Moreover l still have problem with building : `cmake ../ and make `
l did the following
```
 export CUDA_BIN_PATH="/usr/local/cuda"
cd build
cmake ../
make

```

```
cmake ../
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /root/anaconda3/bin/cc
-- Check for working C compiler: /root/anaconda3/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /root/anaconda3/bin/c++
-- Check for working CXX compiler: /root/anaconda3/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:771 (message):
  Expecting to find librt for libcudart_static, but didn't find it.
Call Stack (most recent call first):
  CMakeLists.txt:20 (FIND_PACKAGE)


-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "6.5") 
-- cuda found TRUE
-- Found Torch7 in /home/ahmed/torch/install
-- Torch found /home/ahmed/torch/install/share/cmake/torch
-- Building shared library with GPU support
-- Building Torch Bindings with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ahmed/warp-ctc/build

```
and make returns  :   

```
make
[ 10%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
[ 20%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_ctc_entrypoint.cu.o
Scanning dependencies of target warpctc
[ 30%] Linking CXX shared library libwarpctc.so
[ 30%] Built target warpctc
Scanning dependencies of target test_cpu
[ 40%] Building CXX object CMakeFiles/test_cpu.dir/tests/test_cpu.cpp.o
[ 50%] Linking CXX executable test_cpu
/home/ahmed/torch/install/lib/libTHC.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
/home/ahmed/torch/install/lib/libTHC.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/home/ahmed/torch/install/lib/libTH.so.0: undefined reference to `GOMP_parallel@GOMP_4.0'
/home/ahmed/torch/install/lib/libTHC.so: undefined reference to `std::random_device::_M_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/ahmed/torch/install/lib/libTHC.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/home/ahmed/torch/install/lib/libTHC.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/home/ahmed/torch/install/lib/libTHC.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
CMakeFiles/test_cpu.dir/build.make:99: recipe for target 'test_cpu' failed
make[2]: *** [test_cpu] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test_cpu.dir/all' failed
make[1]: *** [CMakeFiles/test_cpu.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by devinbostIL** [comment]
I was able to install warp-ctc like this:

```
sudo apt-get install gcc-4.8 g++-4.8
export CC="/usr/bin/gcc-4.8"
export CXX="/usr/bin/g++-4.8"
luarocks install http://raw.githubusercontent.com/baidu-research/warp-ctc/master/torch_binding/rocks/warp-ctc-scm-1.rockspec
```
I'm on Ubuntu 16.04 with CUDA 8.0.

**Comment by ahmedmazari-dhatim** [comment]
Hello @SeanNaren , @skaae , @devinbostIL 
l installed successfully pytorch, warp-ctc without any error but when executing it l get the following error: 

```
from warpctc_pytorch import CTCLoss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name CTCLoss

```
What's wrong ?
Thanks for your help

**Comment by safaasawalhah** [comment]
> @dlmacedo have you solved the problem?
> If yes please share an answer

plz, I have the same problem and I am new in deep learning and ubuntu can you help me ?
 note that I used PyTorch 1.1, Cuda 9, and ubuntu 18.04
