### ISSUE TITLE
Unable to run an4.py from data/ directory

### ISSUE THREAD

**Issue by dlmacedo** [SeanNaren/deepspeech.pytorch#11]
Dear friends,

When trying to run an4.py from ./data I get:

> dlm@vm001nc6:~/code/deepspeech.pytorch/data$ python an4.py
> Traceback (most recent call last):
>   File "an4.py", line 8, in <module>
>     from data.utils import create_manifest
> ModuleNotFoundError: No module named 'data'
> 

I guess when I try to run an4.py from data dir (as explained in the README.md), the data module is not resolved.

David

**Comment by SeanNaren** [comment]
Pull and retry, #14 should fix this
