### ISSUE TITLE
Result of slicing is an empty sensor

### ISSUE THREAD

**Issue by scelesticsiva** [SeanNaren/deepspeech.pytorch#113]
I am trying to train Deep Speech 2 with a custom dataset(1120 utterances). I was using 80% of the data for training and the remaining 20% of the data for testing. I was able to achieve 11% CER with a little bit of hyperparamter tuning. I decided to test the robustness of the model with 5-fold cross validation but i am facing this following error 
Traceback (most recent call last):
  File "train.py", line 389, in <module>
    main()
  File "train.py", line 299, in main
    split_targets.append(targets[offset:offset + size])
ValueError: result of slicing is an empty tensor
for all the folds except for one. (I have never worked on pytorch before)

**Comment by mcernak** [comment]
I had this error when I changed the label file `labels.json` and did not keep the first label `"_"`. Is it also your case?
BTW, I don't know what this 'zero' label mean.

**Comment by scelesticsiva** [comment]
"_" is the first label in my labels.json (i did not change my labels.json). I think "zero" label (or the blank label) is to account for the blanks between words.

**Comment by scelesticsiva** [comment]
After careful debugging, i found that some of the .txt files i was using were empty which was the cause of the error. Closing this issue.
