### ISSUE TITLE
error of install pytorch ctc?

### ISSUE THREAD

**Issue by lxj0276** [SeanNaren/deepspeech.pytorch#116]
when I use my macbook install pytorch ctc,It shows:

`CUDA_HOME not found in the environment so building without GPU support. To build with GPU support please define the CUDA_HOME environment variable. This should be a path which contains include/cuda.h
generating build/_warp_ctc.c
regenerated: 'build/_warp_ctc.c'
running install
running build
running build_py
creating build/lib.macosx-10.7-x86_64-2.7
creating build/lib.macosx-10.7-x86_64-2.7/warpctc_pytorch
copying warpctc_pytorch/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/warpctc_pytorch
running build_ext
building 'warpctc_pytorch._warp_ctc' extension
creating build/temp.macosx-10.7-x86_64-2.7
creating build/temp.macosx-10.7-x86_64-2.7/build
creating build/temp.macosx-10.7-x86_64-2.7/Users
creating build/temp.macosx-10.7-x86_64-2.7/Users/lixianjie
creating build/temp.macosx-10.7-x86_64-2.7/Users/lixianjie/code
creating build/temp.macosx-10.7-x86_64-2.7/Users/lixianjie/code/yunda
creating build/temp.macosx-10.7-x86_64-2.7/Users/lixianjie/code/yunda/baidu
creating build/temp.macosx-10.7-x86_64-2.7/Users/lixianjie/code/yunda/baidu/warp-ctc
creating build/temp.macosx-10.7-x86_64-2.7/Users/lixianjie/code/yunda/baidu/warp-ctc/pytorch_binding
creating build/temp.macosx-10.7-x86_64-2.7/Users/lixianjie/code/yunda/baidu/warp-ctc/pytorch_binding/src
gcc -fno-strict-aliasing -I/Users/lixianjie/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/lixianjie/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/Users/lixianjie/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/lixianjie/code/yunda/baidu/warp-ctc/include -I/Users/lixianjie/anaconda2/include/python2.7 -c build/_warp_ctc.c -o build/temp.macosx-10.7-x86_64-2.7/build/_warp_ctc.o -std=c++11 -fPIC
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
error: command 'gcc' failed with exit status 1`
anybody can help me to solve it?

**Comment by ryanleary** [comment]
This is actually the warp-ctc library you're having trouble with.

I think you need to ensure that the compiler you're using is actually GNU GCC and not Apple's Clang/LLVM.

**Comment by SeanNaren** [comment]
You are also installing on a macbook, unless you're using an external GPU it cannot support CUDA (AFAIK)

**Comment by rdp** [comment]
For followers `CC=g++-7 python setup.py install` (after installing gcc via homebrew) ref: http://betterlogic.com/roger/2018/02/cmake-woe/
