### ISSUE TITLE
Custom dataset training runtime error

### ISSUE THREAD

**Issue by mit456** [SeanNaren/deepspeech.pytorch#117]
Hello,

I am trying to train on custom indian english dataset, I did complete data building, then when given for training using 
`python train.py --train_manifest data/complete_indian_70_train_manifest.csv --val_manifest data/complete_indian_70_test_manifest.csv` I am getting RuntimeError in first epoch and first batch:

`RuntimeError: Given input size: (32 x 61 x 9). Calculated output size: (32 x 21 x -1). Output size is too small at /vmdata/mithun/Playground/A/pytorch/torch/lib/THNN/generic/SpatialConvolutionMM.c:45`

Found this thread: `https://discuss.pytorch.org/t/output-size-is-too-small-at-spatialconvolutionmm-c-45-error/3292 `

While debugging I found following inputs, hoping would be useful to understand the problem:
`inputs size = 20x1x161x27` which in the form of `minibatch x channel x iH x iW`

`Traceback (most recent call last):`
  `File "train.py", line 412, in <module>  `
    `main()`
  `File "train.py", line 249, in main`
   ` out = model(inputs)`
  `File "/vmdata/mithun/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 207, in __call__`
   ` result = self.forward(*input, **kwargs)`
  `File "/vmdata/mithun/Playground/A/deepspeech.pytorch/model.py", line 121, in forward`
   ` x = self.conv(x)`
  `File "/vmdata/mithun/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 207, in __call__`
    `result = self.forward(*input, **kwargs)`
  `File "/vmdata/mithun/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward`
   ` input = module(input)`
  `File "/vmdata/mithun/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 207, in __call__`
    `result = self.forward(*input, **kwargs)`
 ` File "/vmdata/mithun/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 244, in forward`
   ` self.padding, self.dilation, self.groups)`
  `File "/vmdata/mithun/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 48, in conv2d`
    `return f(input, weight, bias)`

What could be the reason of this issue? Does it mean data is not properly built?

Thanks

**Comment by SiddGururani** [comment]
It's possible that the utterances are too short in that batch. You could use a smaller window/hop to address this.

**Comment by SeanNaren** [comment]
As @SiddGururani said, some of your utterances are too short. You probably want to filter out using the preprocessing script anything under a second!

**Comment by mit456** [comment]
@SeanNaren @SiddGururani Thanks for the help, I didn't get time to try it out, but I will be applying your suggested changes and then will update you guys.
