### ISSUE TITLE
Audio sampling rate in data augmentation

### ISSUE THREAD

**Issue by srviest** [SeanNaren/deepspeech.pytorch#119]
I ran out of memory when training with data augmentation. I found that the sampling rate of load_randomly_augmented_audio in data_loader.py is locked to 16k, so if you change the sampling rate there would be an inconsistency, is that a bug need to be fixed?

**Comment by SeanNaren** [comment]
Yes there is! Will get to it

**Comment by SeanNaren** [comment]
Fixed on master!
