### ISSUE TITLE
Unable to create an4 dataset using Python 3.6

### ISSUE THREAD

**Issue by dlmacedo** [SeanNaren/deepspeech.pytorch#12]
Dear friends,

In order to run an4.py from inside the data dir (as described by README.md) I fix the data.utils in an4.py with the following changes:

```
#from data.utils import create_manifest
from utils import create_manifest

```

If I am using Python 3.6:

Now, I am getting following error:

> Traceback (most recent call last):
>   File "an4.py", line 84, in <module>
>     main()
>   File "an4.py", line 72, in main
>     _format_data(root_path, 'train', name, 'an4_clstk')
>   File "an4.py", line 31, in _format_data
>     _format_files(file_ids, new_transcript_path, new_wav_path, transcripts, wav_path)
>   File "an4.py", line 57, in _format_files
>     file.write(extracted_transcript)
> TypeError: a bytes-like object is required, not 'str'

David

**Comment by SeanNaren** [comment]
PyTorch only supports 2.7 and 3.5 so I'm not sure what changes are required for 3.6.

**Comment by rampage644** [comment]
@dlmacedo replace that line with `file.write(bytes(extracted_transcript, 'utf-8'))`. It's `python3` issue, not `python3.6`.

**Comment by SeanNaren** [comment]
Thanks @rampage644 , pull the latest master branch and retry.

**Comment by dlmacedo** [comment]
Dear friends,

I pulled the repo and run an4.py and I got this:

```
Traceback (most recent call last):
  File "an4.py", line 83, in <module>
    main()
  File "an4.py", line 78, in main
    create_manifest(train_path, 'train')
  File "/home/dlm/code/deepspeech.pytorch/data/utils.py", line 35, in create_manifest
    file.write(sample)
TypeError: a bytes-like object is required, not 'str'
```

See the new code below for an4.py: 

```
def _format_files(file_ids, new_transcript_path, new_wav_path, transcripts, wav_path):
    with open(file_ids, 'r') as f:
        with open(transcripts, 'r') as t:
            paths = f.readlines()
            transcripts = t.readlines()
            for x in range(len(paths)):
                path = wav_path + paths[x].strip() + '.wav'
                filename = path.split('/')[-1]
                extracted_transcript = _process_transcript(transcripts, x)
                current_path = os.path.abspath(path)
                new_path = new_wav_path + filename
                text_path = new_transcript_path + filename.replace('.wav', '.txt')
                with io.FileIO(text_path, "w") as file:
                    file.write(extracted_transcript.encode('utf-8'))
                os.rename(current_path, new_path)
```

I think we should do something following the bellow link:

https://docs.python.org/3/howto/pyporting.html#text-versus-binary-data

**Comment by SeanNaren** [comment]
Added to that line (should've tested it, my bad). Thanks @dlmacedo !
