### ISSUE TITLE
Trie in KenLM

### ISSUE THREAD

**Issue by ArtemiyFirsov** [SeanNaren/deepspeech.pytorch#120]
Hi!

I trained KenLM model using kenLM library and deepspeech.pytorch assks for trie_path/ 
Where should I get it? I cannot see any file provided by kenLM library. Should I get it additionally? Maybe you can advice any library that is capable of building trie?

**Comment by ArtemiyFirsov** [comment]
OK, I got ot with _bin/build_binary -T /tmp/trie -S 1G trie ~/path/to/arpa ~/wher/to/save/trie_ command

**Comment by ryanleary** [comment]
You should use the generate_lm_trie.py script to generate the trie. The kenlm trie is something different.

**Comment by ArtemiyFirsov** [comment]
@ryanleary cool, thank you. will try and let you know if face any issue

**Comment by ryanleary** [comment]
@ArtemiyFirsov is this resolved?

**Comment by SeanNaren** [comment]
Will close this for now...

**Comment by ArtemiyFirsov** [comment]
@ryanleary @SeanNaren yes, resolved, thank you.
