### ISSUE TITLE
DeepSpeech.PyTorch stops working after installing Torch to use also DeepSpeech.Torch

### ISSUE THREAD

**Issue by dlmacedo** [SeanNaren/deepspeech.pytorch#13]
Dear friends,

My DeepSpeech.PyTorch stopped working after installing Torch to use also DeepSpeech.Torch. See the logs bellow. It is very similar with an another issue of the repo and they said we should use another gcc, but I am not sure exactly what is the REAL problem.

If a move the torch installation directory, DeepSpeech.PyTorch works again! If a move the torch installation directory back, DeepSpeech.PyTorch fails!

```
> dlm@vm001nc6:~/code/deepspeech.pytorch$
> dlm@vm001nc6:~/code/deepspeech.pytorch$
> dlm@vm001nc6:~/code/deepspeech.pytorch$ python train.py --train_manifest data/train_manifest.csv --val_manifest data/val_manifest.csv
> Traceback (most recent call last):
>   File "train.py", line 9, in <module>
>     from warpctc_pytorch import CTCLoss
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/warpctc_pytorch/__init__.py", line 7, in <module>
>     from ._warp_ctc import lib as _lib, ffi as _ffi
> ImportError: /home/dlm/anaconda3/lib/python3.6/site-packages/torch/lib/../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/dlm/torch/install/lib/libwarpctc.so)
> dlm@vm001nc6:~/code/deepspeech.pytorch$

```

**Comment by SeanNaren** [comment]
Have you tried installing gcc 4.8 suggested [here](https://github.com/SeanNaren/deepspeech.pytorch/issues/10)? Instructions to install gcc 4.8 found [here](http://askubuntu.com/a/581497). Then try compiling the warp_ctc library for pytorch.

**Comment by dlmacedo** [comment]
I did exactly this. I build the PyTorch project with gcc 4.8 and it made the project work! With gcc 5.1 not even worked.

But after installing Torch and DeepSpeech.Torch, everything crashed. I only can use DeepSpeech.pytorhc if I move to torch installation dir to another place temporarily.

Very strange, really.

**Comment by rampage644** [comment]
@dlmacedo The real problem is that `pytorch` distribution comes with its own `libgomp.so` against which pytorch is compiled.

I had exactly the same problem because my system `libgomp` lib was either compiled with different compiler and/or even different lib version.

`pytorch` distribution (binary, from `pip`) comes with its own `libgomp.so`, so pytorch is guaranteed to work. However, if you compile `warp-ctc` then it would be linked against your system `libgomp` (if no actions against that is taken) that could be incompatible. What you want to do is to make sure `warp-ctc` is linked against exactly the same `libgomp` pytorch was linked. For that, i just compiled pytorch from sources (so it's also linked against system `libgomp`)

**Comment by dlmacedo** [comment]
https://github.com/SeanNaren/deepspeech.pytorch/issues/16

**Comment by ahmedmazari** [comment]
@rampage644 , thanks for your clarifications but  l'm not sure to understand your solution.
Fom me l get the error when trying to build warp ctc as follow :  
```

git clone https://github.com/baidu-research/warp-ctc.git
cd warp-ctc
mkdir build 
cd build 
cmake ../

```
Here is the error
```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /root/anaconda3/bin/cc
-- Check for working C compiler: /root/anaconda3/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /root/anaconda3/bin/c++
-- Check for working CXX compiler: /root/anaconda3/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
**CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:771 (message):
  Expecting to find librt for libcudart_static, but didn't find it.
Call Stack (most recent call first):
  CMakeLists.txt:20 (FIND_PACKAGE)**


-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "6.5") 
-- cuda found TRUE
-- Found Torch7 in /home/ahmed/torch/install
-- Torch found /home/ahmed/torch/install/share/cmake/torch
-- Building shared library with GPU support
-- Building Torch Bindings with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ahmed/warp-ctc/build
```

**Comment by ahmedmazari** [comment]
Please see my updates @dlmacedo  @SeanNaren  @rampage644

**Comment by SeanNaren** [comment]
I ran into similar errors, and as people said this is due to g++/cmake being installed via pytorch conda. I would suggest trying to below commands if you're still having issue:

```

**Comment by mit456** [comment]
I am facing similar issue in `wrap-ctc` `cmake ../` and `make` and then found this thread, so removed anaconda g++ and cmake and trying to install pytorch using global cmake and g++.

but `python setup.py install` command is unable to find C or CXX compiler, I have set the environment variable in my `~/.zshrc` file

`export CC="/usr/bin/gcc"`
`export CXX="/usr/bin/g++"`

Error: 
`running install`
 `running build_deps`
`-- The C compiler identification is unknown`
`-- The CXX compiler identification is unknown`
`CMake Error in CMakeLists.txt:`
  `The CMAKE_C_COMPILER:`
   `/vmdata/mithun/anaconda3/bin/cc`
  `is not a full path to an existing compiler tool.`

  `Tell CMake where to find the compiler by setting either the environment`
  `variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to`
  `the compiler, or to the compiler name if it is in the PATH.`


`CMake Error in CMakeLists.txt:`
  `The CMAKE_CXX_COMPILER:`
    `/vmdata/mithun/anaconda3/bin/c++`

  `is not a full path to an existing compiler tool.`

  `Tell CMake where to find the compiler by setting either the environment`
  `variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path`
  `to the compiler, or to the compiler name if it is in the PATH.`


`-- Configuring incomplete, errors occurred!`
`See also "/vmdata/mithun/Playground/A/pytorch/torch/lib/build/TH/CMakeFiles/CMakeOutput.log".`
`See also "/vmdata/mithun/Playground/A/pytorch/torch/lib/build/TH/CMakeFiles/CMakeError.log"`

Any help ?

**Comment by SeanNaren** [comment]
when you do `which gcc` or `which g++` what comes up @mit456 ? you might need to do `sudo apt-get install gcc g++`

**Comment by mit456** [comment]
@SeanNaren `which gcc` gives `/usr/bin/gcc` and `which g++` gives `/usr/bin/g++`.

**Comment by SeanNaren** [comment]
If you do `echo $CC` what comes up?

**Comment by mit456** [comment]
It shows `/usr/bin/gcc`

**Comment by mit456** [comment]
I will try removing everything and then installing from scratch if that helps I will let you know.

**Comment by dlmacedo** [comment]
In the last line of the above script I got:
```
dlm@vm001nc24:~/code/warp-ctc/pytorch_binding$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from torch.utils.ffi import create_extension
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/dlm/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/dlm/anaconda3/lib/python3.6/site-packages/torch/lib/libshm.so)

```

**Comment by dlmacedo** [comment]
This time I tried:

1. To be sure you are using gcc, cmake and g++ from linux. Not from Anaconda.

2. To be sure to be using version 4.8 of gcc and g++.

3. To install PyTorch from source without never being installed before with Anaconda.

And I got this:

```
> dlm@vm001nc24:~/code/deepspeech.pytorch$ python train.py --train_manifest data/an4_train_manifest.csv --val_manifest data/an4_val_manifest.csv
> Traceback (most recent call last):
>   File "train.py", line 11, in <module>
>     from data.bucketing_sampler import BucketingSampler, SpectrogramDatasetWithLength
>   File "/home/dlm/code/deepspeech.pytorch/data/__init__.py", line 1, in <module>
>     from . import data_loader
>   File "/home/dlm/code/deepspeech.pytorch/data/data_loader.py", line 8, in <module>
>     import torchaudio
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torchaudio-0.1-py3.6-linux-x86_64.egg/torchaudio/__init__.py", line 8, in <module>
>     from ._ext import th_sox
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torchaudio-0.1-py3.6-linux-x86_64.egg/torchaudio/_ext/th_sox/__init__.py", line 3, in <module>
>     from ._th_sox import lib as _lib, ffi as _ffi
> ImportError: /home/dlm/anaconda3/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /usr/lib/x86_64-linux-gnu/libsox.so.2)
> dlm@vm001nc24:~/code/deepspeech.pytorch$ which gcc
> /usr/bin/gcc
> dlm@vm001nc24:~/code/deepspeech.pytorch$ which g++
> /usr/bin/g++
> dlm@vm001nc24:~/code/deepspeech.pytorch$ gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu2)
> dlm@vm001nc24:~/code/deepspeech.pytorch$ g++ -v
> Using built-in specs.
> COLLECT_GCC=g++
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu2)
```

**Comment by dlmacedo** [comment]
[https://github.com/pytorch/pytorch/issues/643](url)

**Comment by skaae** [comment]
Maybe this will help someone. I installed pytorch using anaconda gcc/g++ version 4.8.5 and compiled the bindings using system (`usr/bin`) gcc/gcc version 4.8.5. 

and then 
 `conda install libgcc`

**Comment by saurabhvyas** [comment]
I followed all the steps described above , building pytorch from scratch but still get the same error 
```
saurabh@saurabh-Inspiron-5559:~/warp-ctc/build$ cd ..
saurabh@saurabh-Inspiron-5559:~/warp-ctc$ cd pytorch_binding && python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from torch.utils.ffi import create_extension
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/saurabh/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/saurabh/anaconda3/lib/python3.6/site-packages/torch/lib/libshm.so)
saurabh@saurabh-Inspiron-5559:~/warp-ctc/pytorch_binding$ 

```

**Comment by xmfbit** [comment]
Share my solution here. However I don't know why...
The environment is Ubuntu16.04 with CUDA8.0, GCC version of system is 5.4.0. And GCC version of Anaconda is 4.8.5. I installed PyTorch from source following the instructions on its GitHub repo page.
1. I add the two lines in `~/.zshrc` file (if you are using bash, modify `~/.bashrc` instead).
```
export CC="/usr/bin/gcc"
export CXX="/usr/bin/g++"
```
Make sure that after you export Anaconda, the value of environment variable `CC` is `/usr/bin/gcc`.
```
# print the value of CC
echo $CC
```
If not, it will fail when building the warp-ctc C++ code.

2. Inspired by @skaae, but I didn't install GCC 4.8 (because the server is owned by the lab and I can't modify things at will). I just run the following command:
```
conda install libgcc
```

3. After building the warpctc code, you should export `CUDA_HOME` if you want to enable GPU before running python installation script.
```
export CUDA_HOME=/path/to/cuda
cd pytorch_binding
python setup.py install
```
4. Test! After all of this, you can test it!
```
cd pytorch_binding/tests
python test.py
```
If it works well, it will print the gradient information like this:
```
➜  tests git:(pytorch_bindings) ✗ python test.py 
Variable containing:
 0.1770 -0.7081  0.1770  0.1770  0.1770
-0.8230  0.1770  0.2919  0.1770  0.1770
 0.2919  0.1770 -0.8230  0.1770  0.1770
-0.8213  0.1787  0.2665  0.1975  0.1787
[torch.cuda.FloatTensor of size 4x5 (GPU 0)]

.Variable containing:
 0.1770 -0.7081  0.1770  0.1770  0.1770
 0.1770 -0.8230  0.2919  0.1770  0.1770
 0.2919  0.1770 -0.8230  0.1770  0.1770
 0.1787  0.1787 -0.7335  0.1975  0.1787
[torch.cuda.FloatTensor of size 4x5 (GPU 0)]

.Variable containing:
 0.0000  0.0000  0.0000  0.0000  0.0000
 0.0000 -1.0000  1.0000  0.0000  0.0000
 1.0000  0.0000 -1.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  0.0000  0.0000
[torch.cuda.FloatTensor of size 4x5 (GPU 0)]

.Variable containing:
 0.1770 -0.7081  0.1770  0.1770  0.1770
 0.1770  0.1770 -0.7081  0.1770  0.1770
[torch.cuda.FloatTensor of size 2x5 (GPU 0)]

.
----------------------------------------------------------------------
Ran 4 tests in 2.832s

OK
```
