### ISSUE TITLE
Fail to install warpctc_pytorch with gpu

### ISSUE THREAD

**Issue by FrBernkastel** [SeanNaren/deepspeech.pytorch#138]
I have built libwarpctc.so, but after export CUDA_HOME and running `python setup.py install`, it reminded me that `CUDA_HOME not found in the environment so building without GPU support. To build with GPU support please define the CUDA_HOME environment variable. This should be a path which contains include/cuda.h` 
However, i checked the CUDA_HOME (/usr/local/cuda) and found that include/cuda.h and lib/libcudart.so exist there.
BY THE WAY, there is not lib/ in the CUDA_HOME but just lib64/, so i cp the lib64/ as the lib/.

**Comment by SeanNaren** [comment]
Sorry for the late response. To hack around this modify the setup.py script such that `enable_gpu` [here](https://github.com/SeanNaren/warp-ctc/blob/pytorch_bindings/pytorch_binding/setup.py#L19) is always true. Hopefully that can get around that.
