### ISSUE TITLE
seg fault issue by gpu memory

### ISSUE THREAD

**Issue by jinserk** [SeanNaren/deepspeech.pytorch#139]
Hello,

I'm using single GTX1070 with 8GB GDDR5, and trying to train deepspeech.pytorch with TEDLIUM corpus. However, a few trials were failed by seg fault, which I guess it's originated from the OOM issue. I've tried to reduce the batch size, but now I found another parameter `--num_workers`. I wonder which parameter can be more profitable to manage OOM issue. Could you give me any guide for this?

```
Epoch: [1][10823/11373] Time 0.504 (0.243)      Data 0.011 (0.021)      Loss 218.2781 (164.8313)                                                                         │···························································
Epoch: [1][10824/11373] Time 0.512 (0.244)      Data 0.011 (0.021)      Loss 244.8923 (164.8387)                                                                         │···························································
Epoch: [1][10825/11373] Time 0.503 (0.244)      Data 0.012 (0.021)      Loss 233.4698 (164.8451)                                                                         │···························································
./train.sh: line 12: 35528 Segmentation fault      (core dumped) python train.py --train_manifest data/ted/ted_train_manifest.csv --val data/ted/ted_val_manifest.csv --s│···························································
ample_rate 8000 --augment --batch_size 8 --epochs 100 --cuda --checkpoint --save_folder models/20170823            
```                                                      │

**Comment by jinserk** [comment]
I think this is closely related to #104

**Comment by dlmacedo** [comment]
If you activate the warnings of the PyTorch 0.2.0, you receive something like this:

`/home/dlm/code/deepspeech.pytorch/model.py:63: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greately increasing memory usage. To compact weights again call flatten_parameters().`

The warming indicates that our code works but that it is not optimal of a memory allocation point of view.

I guess if we change the code in order to follow the recommendation above, we will probably solve out of memory related problems.

**Comment by jinserk** [comment]
I added a single line ```self.rnn.flatten_parameters()``` into model.py like this:
```
diff --git a/model.py b/model.py
index 1664e71..e7b5ad6 100644
--- a/model.py
+++ b/model.py
@@ -63,6 +63,7 @@ class BatchRNN(nn.Module):
         x, _ = self.rnn(x)
         if self.bidirectional:
             x = x.view(x.size(0), x.size(1), 2, -1).sum(2).view(x.size(0), x.size(1), -1)  # (TxNxH*2) -> (TxNxH) by sum
+        self.rnn.flatten_parameters()
         return x
```
and it seems the seg fault by OOM disappeared.
I'm not sure I've done correctly.

**Comment by SeanNaren** [comment]
Thanks for that @jinserk, my guess it that the data parallel wrapper causes weights to be non-contiguous or something. The only issue I have with putting the `flatten_parameters()` command there is that it might be time consuming; have you noticed a slowdown when putting this here? 

I'll investigate if there is a slowdown and create a PR for this!

**Comment by ryanleary** [comment]
I think we should be able to do `self.rnn.flatten_parameters()` at model loading time, no?

**Comment by jinserk** [comment]
Well, I have no reference to notice any slowdown issue since all previous training was failed by seg fault. My data is as big as taking almost half day for single epoch, and I don't feel that it is slower than before.
