### ISSUE TITLE
Issue w/ TED Dataloader

### ISSUE THREAD

**Issue by tbornt** [SeanNaren/deepspeech.pytorch#140]
When I trained using TED dataset, dataloader breaks at the end of the first epoch. very similar to issue #33 .

Epoch: [1][4249/4549]	Time 1.030 (0.795)	Data 0.009 (0.300)	Loss 188.7770 (141.7761)
Epoch: [1][4250/4549]	Time 1.029 (0.795)	Data 0.011 (0.300)	Loss 195.2455 (141.7887)
Epoch: [1][4251/4549]	Time 1.036 (0.795)	Data 0.012 (0.300)	Loss 220.4217 (141.8072)
Epoch: [1][4252/4549]	Time 1.355 (0.795)	Data 0.330 (0.300)	Loss 230.9768 (141.8281)
Epoch: [1][4253/4549]	Time 1.037 (0.795)	Data 0.011 (0.300)	Loss 186.9595 (141.8387)
Epoch: [1][4254/4549]	Time 1.045 (0.795)	Data 0.012 (0.300)	Loss 212.6549 (141.8554)
Epoch: [1][4255/4549]	Time 1.044 (0.795)	Data 0.011 (0.300)	Loss 177.9757 (141.8639)
Epoch: [1][4256/4549]	Time 2.293 (0.796)	Data 1.245 (0.300)	Loss 208.0037 (141.8794)
Epoch: [1][4257/4549]	Time 1.046 (0.796)	Data 0.012 (0.300)	Loss 189.0724 (141.8905)
Epoch: [1][4258/4549]	Time 1.048 (0.796)	Data 0.012 (0.300)	Loss 198.3966 (141.9038)
Epoch: [1][4259/4549]	Time 1.091 (0.796)	Data 0.012 (0.300)	Loss 186.5566 (141.9143)
Epoch: [1][4260/4549]	Time 1.829 (0.796)	Data 0.782 (0.300)	Loss 199.6965 (141.9278)
Epoch: [1][4261/4549]	Time 2.006 (0.796)	Data 0.958 (0.300)	Loss 220.2037 (141.9462)
Epoch: [1][4262/4549]	Time 1.049 (0.796)	Data 0.009 (0.300)	Loss 205.2232 (141.9610)
Traceback (most recent call last):
  File "train.py", line 397, in <module>
    main()
  File "train.py", line 221, in main
    for i, (data) in enumerate(train_loader, start=start_iter):
  File "/home/gpu/xuheng/Code/deepspeech.pytorch/venv3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 187, in __next__
    return self._process_next_batch(batch)
  File "/home/gpu/xuheng/Code/deepspeech.pytorch/venv3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: function takes exactly 5 arguments (1 given)

**Comment by tbornt** [comment]
The issue is not reproduced in another server. Closed this issue.

**Comment by mrmidnight55** [comment]
Now. I'm facing this problem when I try to train all dataset(an4, Tedlium2, all Librispeech, Voxforge)
