### ISSUE TITLE
too slow bucketing sampler

### ISSUE THREAD

**Issue by jinserk** [SeanNaren/deepspeech.pytorch#143]
I'm training with 1.2M lined manifest file, but the bucketing sampler in each epoch takes time too much. It takes almost 2 hrs for bucketing only. Is there any good way to reduce this?
How about changing the format of manifest file that it contains length of the corresponding utterance like [Mozilla's DeepSpeech using Tensorflow](https://github.com/mozilla/DeepSpeech.git)? Their manifest file contains ```<wav_filename>,<wav_filesize>,<transcript>```; it's not a bad idea to utilize this length info to make a sorted batch.

**Comment by EgorLakomkin** [comment]
I have a local branch where I pre-calculate duration and that allows to start training with no delay. I will do PR.

**Comment by SeanNaren** [comment]
Fixed in #163
