### ISSUE TITLE
can it work with out GPU?

### ISSUE THREAD

**Issue by sekarpdkt** [SeanNaren/deepspeech.pytorch#144]
Can it work without GPU? If yes, what shall be the step for 

```
export CUDA_HOME="/usr/local/cuda"
cd pytorch_binding
python setup.py instal
```

**Comment by sekarpdkt** [comment]
leave it.. I found that it works

**Comment by vermasrijan** [comment]
Hi @sekarpdkt ,
Even I have the same question 
Can deepspeech.pytorch work without a gpu?
I am not able to figure this out yet.
Any insights would be helpful.

Thanks!

**Comment by ryanleary** [comment]
Yes, you can do training and inference without a GPU. It will be extremely slow to train without a GPU however.

**Comment by vermasrijan** [comment]
Thanks for replying @ryanleary . 
I am really stuck at the installation of warp-ctc, here-
export CUDA_HOME="/usr/local/cuda"
cd ../pytorch_binding
python setup.py install

After running <python setup.py install> command, I keep getting the following error: 
fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
                     ^
I believe this ^ is something related to gcc compiler (the version that I am using is gcc4.9)

also, if I dont run <export CUDA_HOME="/usr/local/cuda"> command and then run <python setup.py install> , warpctc_pytorch does get installed in my site-packages(with the name- warpctc_pytorch-0.1-py3.6-macosx-10.9-x86_64.egg), but after importing the library, I get the following error: No module named 'warpctc_pytorch._warp_ctc.__warp_ctc'

I have a macos, and for the timing I want to run deepspeech without a gpu. 

Any insights would be really helpful.

Thanks!

**Comment by miguelvr** [comment]
I don't think warp-ctc can be installed without CUDA :/

**Comment by SeanNaren** [comment]
@miguelvr don't think thats correct, you can install warp-ctc without GPUs AFAIK. but as @ryanleary said it's going to be quite slow to train things.

**Comment by miguelvr** [comment]
when it compiles it looks for `cuda.h`. how to you circumvent this then? I've been wondering myself

**Comment by ryanleary** [comment]
Have you tried it? The warp-ctc library has a CPU only implementation and the pytorch bindings also support cpu only. If it isn't working, then there's some small bug in the build process.

See here for the warp-ctc library https://github.com/SeanNaren/warp-ctc/blob/pytorch_bindings/CMakeLists.txt#L100 "Building shared library with no GPU support" and here for the PyTorch binding: https://github.com/SeanNaren/warp-ctc/blob/pytorch_bindings/pytorch_binding/setup.py#L45 where it's clear that having GPU support is optional.

**Comment by vermasrijan** [comment]
@ryanleary , thanks for sharing these.
I tried to work around the resources that you just shared. I was getting the following error on the 'make' process: error: unsupported option '-fopenmp' , but solved this by making some changes in the CMakeList.txt. Following are the changes that i made : 
option(DWITH_OMP "compile warp-ctc with openmp." OFF)

add_definitions(-DCTC_DISABLE_OMP)

#if(NOT WITH_OMP)
#    add_definitions(-DCTC_DISABLE_OMP)
#endif()
#if (WITH_OMP)
#    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
#    set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -Xcompiler -fopenmp")
#endif()

after this, when i ran the setup.py file (in the pytorch_binding directory), this is what i got: 
<img width="564" alt="screen shot 2018-07-16 at 3 48 50 pm" src="https://user-images.githubusercontent.com/24618926/42753834-cacdfff8-890f-11e8-9d71-3de73a28dfcc.png">

And when i tried to import warpctc_pytorch, i got the same error as : No module named 'warpctc_pytorch._warp_ctc.__warp_ctc'

Maybe I am missing out on something, cant figure it out though. 

Thanks!
