### ISSUE TITLE
no network params in saved checkpoint file?

### ISSUE THREAD

**Issue by jinserk** [SeanNaren/deepspeech.pytorch#146]
Hi,

During the training I've stopped it to add visdom monitoring option, and resuming the training, but I got an error like this:
```
Directory already exists.
Directory already exists.
Loading checkpoint model models/20170829/deepspeech_12.pth.tar
While copying the parameter named rnns.0.rnn.weight_ih_l0, whose dimensions in the model are torch.Size([2400, 32]) and whose dimensions in the checkpoint are torch.Size([1600, 32]), ...
Traceback (most recent call last):
  File "train.py", line 395, in <module>
    main()
  File "train.py", line 163, in main
    model.load_state_dict(package['state_dict'])
  File "/home/jbaik/.pyenv/versions/3.6.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 398, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /d2/jbaik/tmp/pip-9398smki-build/torch/lib/THC/generic/THCTensorCopy.c:95
```
And I realize that the default network configuration was recently changed (lstm 400 x 4 layers -> gru 800 x 5 layers). In this time the change was traceable, but IMO, it's better that the saved checkpoint contains such model structure.

**Comment by ryanleary** [comment]
The model params are stored in the model (you can verify this by running `python model.py --model_path /path/to/checkpoint.pth`), but I'm not sure it's actually loaded in the checkpoint load. Sorry for the trouble there. Good find, this should be pretty easy to address.

**Comment by SeanNaren** [comment]
Yep there is an error here, will open a PR ASAP to fix this
