### ISSUE TITLE
Can the labels be more than one character?

### ISSUE THREAD

**Issue by bishwa420** [SeanNaren/deepspeech.pytorch#147]
Hello,

The **labels.json** file contains all possible characters in the script. All the labels in that file are single characters. It is not clear to me whether it is okay to have labels as more than one character. For example, say, my **labels.json** contains:
```
[
..
..
"h",
..,
"sh",
..,
]
```
Is it valid? I think it is valid because nowhere such labeling is checked in the code (as far as I have seen). If that is valid, how will the word  **harsha** be processed? 
<>h<>a<>r<>_sh_<>a<> 
or
 <>h<>a<>r<>_s<>h_<>a<>
..?

PS: I need to have labels of more than one character for my work!

**Comment by ryanleary** [comment]
It does not support that at this time, but should be a reasonable straightforward PR if you would like to contribute it.

**Comment by johndouglascm** [comment]
Just curious, but if the sequence is multi-character based, doesn't the WER basically give you the same thing?  e.g. sh is a 'word' of s+h segmented by a space.  We do something similar with phonemes, and it works well.
