### ISSUE TITLE
row convolution layer?

### ISSUE THREAD

**Issue by jinserk** [SeanNaren/deepspeech.pytorch#148]
In the [DS2 paper](https://arxiv.org/pdf/1512.02595.pdf), they mentioned about a custom layer called as "row convolution layer" in section 3.7, which makes their unidirectional recurrent layer as good as bidirectional one. But in ```model.py```, I coudn't find out this layer implemented. Am I correct? and if so, did you compare the performance according to its existence?

**Comment by ryanleary** [comment]
Please see #46. It's not implemented in PyTorch yet (though most of the underlying code is there already as it exists in TH). PRs welcome for implementing the layer.
