### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by rampage644** [SeanNaren/deepspeech.pytorch#15]
Training process introduce memory leak that prevents model to be trained on larger dataset for long time.

I haven't dig into issue deep enough but here are my observations (i've adapted code to work with vctk dataset): each iteration increase memory consumption of main process by some number (~1.5G for vctk, don't have exact number), on each iteration worker processes double memory requirements (they're `fork()`ed on each iteration).

Right now I'm thinking the problem is inside data loader and/or it integration. But again, I haven't dig into that because of time constraints.

I'm able to train the model on VCTK for 9 iterations with default parameters. My current workaround is to resume training from last checkpoint.

**Comment by SeanNaren** [comment]
Any progress made on this so far? Going to be hard for me to replicate this one I feel!

**Comment by rampage644** [comment]
@SeanNaren Nope, didn't invest time into the issue. My current estimation that I won't be able to.

**Comment by t-vi** [comment]
I may have seen this too and it seems that https://gist.github.com/t-vi/60515a24e1cbc4dc87897a6d8c224698 is a minimal example exhibiting leakage on bidirectional RNNs.
I have tried to debug this, but the memory seems to be allocated somewhere inside cuLaunchKernel in the cudnnRNNForwardTraining.
Various people seem to see different things:
https://discuss.pytorch.org/t/tracking-down-a-suspected-memory-leak/1130

Best regards

Thomas

**Comment by rampage644** [comment]
@t-vi Nice! Thank you for sharing your findings!

**Comment by ryanleary** [comment]
This may have been fixed with the addition of the various `del` variable deletions in the training script. I haven't heard any complaints about this recently.
