### ISSUE TITLE
Custom dataset ::: RuntimeError: $ Torch: not enough memory: you tried to allocate 8GB. But runs with an4_dataset.

### ISSUE THREAD

**Issue by bishwa420** [SeanNaren/deepspeech.pytorch#150]
I cannot start training my model on my machine (Ubuntu 16.04, i7 CPU with 8 GB memory). My recurrent model has only got 200  thousand parameters. The custom dataset contains only 1 training example and 1 validation example (just to check that memory error).

But whenever I try to train the model, I get the following error:

> File "train.py", line 398, in <module>
    main()
  File "train.py", line 235, in main
    out = model(inputs)
  File "/Anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 259, in __call__
    result = self.forward(*input, **kwargs)
  File "/model.py", line 123, in forward
    x = self.conv(x)
  File "/Anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 259, in __call__
    result = self.forward(*input, **kwargs)
  File "/Anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/Anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 259, in __call__
    result = self.forward(*input, **kwargs)
  File "/Anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 255, in forward
    self.padding, self.dilation, self.groups)
  File "/Anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/functional.py", line 53, in conv2d
    return f(input, weight, bias)
RuntimeError: $ Torch: not enough memory: you tried to allocate 8GB. Buy new RAM! at /pytorch/torch/lib/TH/THGeneral.c:270

I did not modify anything major (other than changing the parameters) in the code. I believe there's something mixed up. Is it okay to have a memory error like this (given the number of parameters and dataset size)???? Do I really need to extend my RAM...?

The same code runs with an4 dataset with charm and only consumes  6 GB of RAM. But shortly (about after 20 iterations) the memory usage booms (i.e., ostensible memory leaks).

**Comment by SeanNaren** [comment]
What command are you trying to run?

**Comment by bishwa420** [comment]
I am running from terminal.

`python train.py`

**Comment by SeanNaren** [comment]
Just to make sure this is 8gb on CPU right? There is no GPU installed on the machine?

How big are the files in your custom dataset in seconds?

**Comment by bishwa420** [comment]
@SeanNaren, actually I have plugged in more memory into my device (now it has 16 GB of memory). No GPU installed. The custom dataset has only 155 wav files (say 30 MB of length average lengths 6 seconds).

**Comment by bishwa420** [comment]
Actually, I have trapped myself into more trouble. Before convolution operation `x = self.conv(x)` in class `DeepSpeech` is executed in **model.py**, the RAM usage is normal (say 1-1.5 GB with other applications open). After this line is executed, my memory usage booms to 11 GB. Before the routine can finish `forward()` all its instructions, my computer hangs. I learned from other threads that bidirectional architectures can cause memory leakage, but I was not able to run with the unidirectionals also. I am pretty sure, its my bad that I have done something wrong.

**Comment by SeanNaren** [comment]
Could you try reducing the batch size to 1?

**Comment by bishwa420** [comment]
@SeanNaren, yes its working (at least its started training in a bidirectional model). My memory usage is also stable (less than 3.5 GB). What is the intuition behind this?

**Comment by SeanNaren** [comment]
@bishwa420 the larger the batch size, the larger the memory usage :) there is a script to benchmark batch sizes in the repo [here](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/benchmark.py)! Use this to test batch sizes to see which ones can fit into your memory!

**Comment by bishwa420** [comment]
@SeanNaren, I knew this theoretically, but never conceived this could me jolt me for days!!!! Thanks anyhow for this package!!!!! :D 

P.S. Don't close this thread now. I may need to post more.

**Comment by jinserk** [comment]
@bishwa420, you may need to reinstall pytorch from its [source](https://github.com/pytorch/pytorch).
```
$ git clone https://github.com/pytorch/pytorch.git --recursive
```
then you might need to modify the ```torch/lib/TH/THGeneral.c```
```
diff --git a/torch/lib/TH/THGeneral.c b/torch/lib/TH/THGeneral.c
index ac032b9..e4b7ca1 100644
--- a/torch/lib/TH/THGeneral.c
+++ b/torch/lib/TH/THGeneral.c
@@ -223,6 +223,8 @@ void THHeapUpdate(ptrdiff_t size) {
   }
 }
 
+#define DISABLE_POSIX_MEMALIGN
+
 static void* THAllocInternal(ptrdiff_t size)
 {
   void *ptr;
``
Then, install it as:
```
$ python setup.py install
```

As you can see the code, there is some limitation of mem allocation in the THGeneral.c. I have a 256GB memory system, and using the above treatment, I could use the overall memory in pytorch. Please let me know if you got a problem.

**Comment by bishwa420** [comment]
@jinserk thanks for replying. Actually I am doing this now with charm as @SeanNaren told me. Obviously I would like to investigate it more using your way. I'll inform you when I do this. Thanks.
