### ISSUE TITLE
Whether CTCLoss in pytorch support multi-gpu.

### ISSUE THREAD

**Issue by SnailTyan** [SeanNaren/deepspeech.pytorch#153]
@SeanNaren  I want to know whether CTCLoss in pytorch support multi-gpu. When I use CTCLoss trainig crnn model, I find CTCLoss can't support multi-gpu, is it right?

**Comment by SeanNaren** [comment]
I'm not sure if the actual loss can be put inside the data parallel table, but the current implementation in the master repo should work! What error are you running into?

**Comment by SeanNaren** [comment]
Going to close this for now...
