### ISSUE TITLE
import warpctc_pytorch error

### ISSUE THREAD

**Issue by mengya22** [SeanNaren/deepspeech.pytorch#155]
from warpctc_pytorch import CTCLoss  I get error like this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "warpctc_pytorch/__init__.py", line 7, in <module>
    from ._warp_ctc import lib as _lib, ffi as _ffi
ImportError: No module named _warp_ctc

How can I pass this error and use CTCLoss ? Thanks

**Comment by SeanNaren** [comment]
Have you correctly installed the warp-ctc library as described in the README?

**Comment by mengya22** [comment]
@SeanNaren  Thank you for your reply,I have import CTCLoss successfully，but I can not calculate loss  on GPU. I am sure that I execute export CUDA_HOME="/usr/local/cuda"

**Comment by SeanNaren** [comment]
@mengya22 Seems like for some reason the variable isn't being picked up by the install, could you modify the setup.py line [here](https://github.com/SeanNaren/warp-ctc/blob/pytorch_bindings/pytorch_binding/setup.py#L19) and hardcode `enable_gpu` to true? this will force it to install the GPU stuff!

**Comment by SeanNaren** [comment]
It also works to use `CUDA_HOME='LOCATION' python setup.py install`. The actual var doesn't matter, just that it exists

**Comment by rdp** [comment]
For followers, if you get this on mac (and installed anaconda via brew cask)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/my/dirwarp-ctc/pytorch_binding/warpctc_pytorch/__init__.py", line 8, in <module>
    from ._warp_ctc import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'warpctc_pytorch._warp_ctc'
```

meant `cd ../build && cp libwarpctc.dylib /usr/local/anaconda3/lib`

**Comment by zoe218** [comment]
@mengya22 Hello! How did solve the problem?
>>> from warpctc_pytorch import CTCLoss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/warpctc_pytorch/__init__.py", line 8, in <module>
ImportError: No module named _warp_ctc

**Comment by USCIS-DC-RFI-Response-HSSCCG17I00019** [comment]
Yep, same issue here.  I followed the instructions on installing warp-ctc.

ImportError: No module named _warp_ctc

**Comment by zoe218** [comment]
@USCIS-DC-RFI-Response-HSSCCG17I00019  Have you solved?:(

**Comment by Eric-Chen-007** [comment]
I meet the same problem. Have you solved?

**Comment by USCIS-DC-RFI-Response-HSSCCG17I00019** [comment]
nope. i meant, that i am getting the same issue, while following the instructions.

**Comment by remi10001** [comment]
I also got the same issue this week. Thankfully, I have access to a different machine that had it already installed (for reference). I found that the setup.py script was not putting the modules in the right folder in my activated anaconda environment, but the correct files were generated.

I pulled files from the warp-ctc installation into the following directory structure:

warpctc_pytorch:
__init__.py  _warp_ctc

warpctc_pytorch/_warp_ctc:
__init__.py  __warp_ctc.so

Then I copied this directory into my anaconda3/envs/$MYENV/lib/python2.7/site-packages
where $MYENV is the environment one is using in anaconda (I am using python 2.7).

Some of these files were in warp-ctc/pytorch_bindings/warpctc_pytorch after running the setup.py script, but not all of them. I had to search for them in the warp-ctc folder.

Hope this helps. I don't know why I was getting this issue.

**Comment by ryanleary** [comment]
These are issues related to warp-ctc. See seannaren/warp-ctc#31.

**Comment by duniang818** [comment]
@SeanNaren when to build on Windows, then happend the following errors, how should I change the file and correct the error?


CMake Error at CMakeLists.txt:7 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/Coco/PycharmProjects/crnn-pytorch/warp-ctc/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Coco/PycharmProjects/crnn-pytorch/warp-ctc/build/CMakeFiles/CMakeError.log".

**Comment by thierrydesot1** [comment]
hi
whatever I try, taking into account the above remarks
I keep getting 

ModuleNotFoundError: No module named 'warpctc_pytorch._warp_ctc.__warp_ctc'
>>> from warpctc_pytorch import CTCLoss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/getalp/desotth/virtenv_pytorch/anaconda3/lib/python3.6/site-packages/warpctc_pytorch/__init__.py", line 6, in <module>
    from ._warp_ctc import *
  File "/home/getalp/desotth/virtenv_pytorch/anaconda3/lib/python3.6/site-packages/warpctc_pytorch/_warp_ctc/__init__.py", line 3, in <module>
    from .__warp_ctc import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'warpctc_pytorch._warp_ctc.__warp_ctc'

I would be very grateful if someone could give more feedback or help, thanks a lot in advance

**Comment by jjz-learning** [comment]
You can look at the link below, I have solved my issues with its help.

https://github.com/SeanNaren/warp-ctc/pull/31#issue-175729225
