### ISSUE TITLE
librispeech pre-trained model issue

### ISSUE THREAD

**Issue by slbinilkumar** [SeanNaren/deepspeech.pytorch#160]
When testing with some you tube videos, it is observed that some words are combined together and some words are broken in between them. How to solve this issue?
1. By proper adjusting the beam-width ?
2. By using a good language model ?

**Comment by SeanNaren** [comment]
I'd refer to [here](https://github.com/SeanNaren/deepspeech.torch/issues/84#issuecomment-289431990) for getting better results.

But on top of that, I'd say using a good language model is also important. And choosing the right alpha/beta1/beta2 parameters!
