### ISSUE TITLE
How to fine-tune a provided model?

### ISSUE THREAD

**Issue by SarthakYadav** [SeanNaren/deepspeech.pytorch#168]
As the topic says, how can I fine-tune a pretrained model? (librispeech_pretrained.pth)

I have already created the manifest files. But when I give the following command:

`python train.py --train_manifest ./timit_train.csv --val_manifest ./timit-manifest.csv --sample_rate 16000 --epochs 10 --cuda --save_folder ./output/timit-librift/all/ --model_path ./output/timit-librift/best.pth --batch_size 32 --continue_from ./pretrained/librispeech_pretrained.pth`

training doesnt start. The program exits after printing the number of parameters in the model.

On the other hand, training successfully starts if I do not provide the --continue_from argument.

**Comment by SarthakYadav** [comment]
Figured it out. Simply modified train.py to load the state dict only from the provided path and commenting out the entire 
`if args.continue_from ...`
 condition.

**Comment by SeanNaren** [comment]
If you don't mind I'm going to keep this open for now, this might be an important parameter to add; to load a model but to not continue training from the last epoch!

**Comment by SarthakYadav** [comment]
No problem! Do you think this functionality should be integrated in the existing "train.py" script or another dedicated script?

**Comment by SeanNaren** [comment]
@SarthakYadav definitely into the train script, should be a parameter like`--load_model` or something that doesn't take anything but the weights!

**Comment by SarthakYadav** [comment]
That sounds simple. I'll try to submit a merge request once I get home!

**Comment by ryanleary** [comment]
This is also something on my immediate roadmap. @SarthakYadav let me know if you're going to make a first cut at this.

**Comment by SarthakYadav** [comment]
@ryanleary Yep, I'm on it. I think a simple argument flag "finetune" would be good? That is, 

`python train.py --epochs 10 --cuda --continue_from ./pretrained/librispeech_pretrained.pth`

this will simply continue the model, whereas the additional --finetune flag like the command below:

`python train.py --train_manifest ./timit_train.csv --val_manifest ./timit-manifest.csv --epochs 10 --cuda --save_folder ./output/timit-librift/all/ --model_path ./output/timit-librift/best.pth --batch_size 32 --continue_from ./pretrained/librispeech_pretrained.pth --finetune`

Will fine-tune the model on the given training set

**Comment by SeanNaren** [comment]
@SarthakYadav awesome! That looks great :)

**Comment by SeanNaren** [comment]
Added in #169 , cheers!

**Comment by SarthakYadav** [comment]
Great!
