### ISSUE TITLE
Support limiting set of GPUs

### ISSUE THREAD

**Issue by ryanleary** [SeanNaren/deepspeech.pytorch#176]
We should have a command-line option for both train and test to be able to (optionally) limit the GPUs used to a set of device ids.

**Comment by standy66** [comment]
Isn't it easier to achieve this with `CUDA_VISIBLE_DEVICES`? 

Like this:
```$ CUDA_VISIBLE_DEVICES=1,3 python train.py ...```

**Comment by ryanleary** [comment]
Closing. `CUDA_VISIBLE_DEVICES` should be sufficient.
