### ISSUE TITLE
Error using kenlm language model

### ISSUE THREAD

**Issue by dalcazar** [SeanNaren/deepspeech.pytorch#185]
Hi,

I'm training a model in spanish and I can decode with the greedy decoder without any problem. I also tried with the beam decoder and a dict and worked. I tried with a kenlm language model I've created removing symbols not included in my labels.json, but when I try to decode with the last deepspeech.pytorch version I got this error. Any idea why this could be happening?

> #~/deepspeech.pytorch$ python transcribe.py --decoder beam --lm_path ../kenlm-ngram/nuevo_spanish_3gram.arpa --model_path models/deepspeech_checkpoint_epoch_2_iter_83000.pth.tar --audio_path in1.wav
> Loading the LM will be faster if you build a binary file.
> Reading ../kenlm-ngram/nuevo_spanish_3gram.arpa
> ----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
> ****************************************************************************************************
> [/tmp/pip-tm9g6o_m-build/ctcdecode/src/ctc_beam_search_decoder.cpp:31] FATAL: "(probs_seq[i].size()) == (vocabulary.size())" check failed. The shape of probs_seq does not match with the shape of the vocabulary

**Comment by ryanleary** [comment]
This is an issue related to the handling of unicode characters in the ctcdecode project. I'm looking into it.

**Comment by ryanleary** [comment]
@dalcazar I have a PR here that may fix this for you. Could you give it a try? https://github.com/parlance/ctcdecode/pull/47

**Comment by jpdevicente** [comment]
Im having this exact same issue. My model is also in spanish, and Im using the latest version of ctcdecode.

[[ctcdecode/src/ctc_beam_search_decoder.cpp[ctcdecode/src/ctc_beam_search_decoder.cpp::ctcdecode/src/ctc_beam_search_decoder.cpp[32ctcdecode/src/ctc_beam_search_decoder.cpp[:] [ctcdecode/src/ctc_beam_search_decoder.cpp:FATALctcdecode/src/ctc_beam_search_decoder.cpp[32ctcdecode/src/ctc_beam_search_decoder.cpp:3232:] FATAL[ctcdecode/src/ctc_beam_search_decoder.cpp:32] : [] ctcdecode/src/ctc_beam_search_decoder.cpp:32] FATAL"] 32: : FATAL":"FATAL] 32] (probs_seq[i].size()) == (vocabulary.size())(probs_seq[i].size()) == (vocabulary.size())FATAL32] FATAL: FATAL: "(probs_seq[i].size()) == (vocabulary.size())" check failed. The shape of probs_seq does not match with the shape of the vocabulary
: "(probs_seq[i].size()) == (vocabulary.size())" check failed. The shape of probs_seq does not match with the shape of the vocabulary
" check failed. The shape of probs_seq does not match with the shape of the vocabulary

Anyone has any idea why this might be happening again?
