### ISSUE TITLE
Add doc to word_decode in transcribe

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/deepspeech.pytorch#187]
There is some confusion with what `window` and `time_div` represent in this [function](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/transcribe.py#L41), it would be good to add small docs as to what these are in the class!

**Comment by jinserk** [comment]
Is this related to the multiple decoded output sentences from the beam decoder, by the recent updates?

**Comment by saharghannay** [comment]
Hi,
Also, is not clear the abbreviation of those variables : strings, aligns, con, char_probs = decoder.decode(data), and how we get them, because the decoding function return string and offsets tensors.

Thank you

**Comment by SeanNaren** [comment]
I've opted to remove this functionality and clean up the function a bit since it's missing from the new decoder in #191

**Comment by saharghannay** [comment]
Ok, thank you

**Comment by SeanNaren** [comment]
Has been merged, closing this ticket in favour of new tickets to add this functionality back!
