### ISSUE TITLE
Adding data importers for mozilla voice dataset and Tatoeba dataset

### ISSUE THREAD

**Issue by voidspacexyz** [SeanNaren/deepspeech.pytorch#188]
With the new release of Mozilla's voice data and Tatoeba data, we could write custom importers for the same .
If it is too much load, I would be willing to submit a PR for review.

**Comment by voidspacexyz** [comment]
https://voice.mozilla.org/data

**Comment by ryanleary** [comment]
PR welcomed for this dataset, thanks.

**Comment by ryanleary** [comment]
Mozilla Common Voice added in #220.

**Comment by sergun** [comment]
What about Tatoeba? Is it supported now?
