### ISSUE TITLE
Pretrained unidirectional model

### ISSUE THREAD

**Issue by githubnemo** [SeanNaren/deepspeech.pytorch#196]
As I see it, the current pretrained models are using bidirectional RNNs. Are there pretrained models for unidirectional RNNs? I'm currently working on continuous recognition but lack the proper training environment to do the training myself.

**Comment by SeanNaren** [comment]
Currently due to the engineering around a uni-directional model for streaming, this hasn't been a focus for us! Happy for contributions on this though.

**Comment by ryanleary** [comment]
Closing this for #199. We will solicit for someone to step up to train this model there.
