### ISSUE TITLE
Differentiation between clean and other in LibriSpeech

### ISSUE THREAD

**Issue by Minju-Jung** [SeanNaren/deepspeech.pytorch#200]
I want to use LibriSpeech dataset.
In the reported result (https://github.com/SeanNaren/deepspeech.pytorch/releases), LibriSpeech dataset has "clean" and "other" versions.
However, when I downloaded LibriSpeech using "python librispeech.py", I got only libri_train_manifest.csv, libri_test_manifest.csv, and libri_val_manifest.csv.
How can I differentiate  "clean" and "other" within a single csv file?

**Comment by SeanNaren** [comment]
Just pulled #205 this will differentiate between both test manifest scripts!
