### ISSUE TITLE
Training Process hangs in the middle. Full RAM and SWAP.

### ISSUE THREAD

**Issue by SarthakYadav** [SeanNaren/deepspeech.pytorch#201]
Hello

Whilst finetuning on my own dataset, the training script hangs in the middle (happens exactly after 4 epochs and a few iterations) and just stays there. No exception thrown, no error, nothing.

It turns out that the RAM (16 GBs) is full and so is the SWAP (16 GB) for some reason. The GPU usage shows memory used, but volatile usage (from nvidia-smi) is 0%. I am not even keeping intermediate torch tensors (model outputs, targets) after the update on that particular batch are completed. Any ideas what might be happening? FYI, this happens with a seemingly large dataset with ~150k training samples.

**Comment by ryanleary** [comment]
Which version of torch are you using?

**Comment by SarthakYadav** [comment]
I'm using pytorch v0.3. With Cuda 8.

**Comment by ryanleary** [comment]
Have you done any further debugging on this? May just need to try to find some objects to remove/not keep around. 16GB of RAM for large trainings is a bit light in my experience.

**Comment by SeanNaren** [comment]
Going to close this for now, feel free to reopen if needs be. As Ryan said for data loading 16gb RAM for larger training corpora is fairly small

**Comment by SarthakYadav** [comment]
The problem was in the script I wrote. I rewrote it with a clear head and the problem vanished. Thanks though!

**Comment by pbamotra** [comment]
I just set pin_memory=False and the problem went away.

**Comment by felixkreuk** [comment]
This happens to me when training multiproc  (docker image) on a pretty beefy machine. 125G memory, 4 GPUs, 32 cores. Any ideas why this might happen?
