### ISSUE TITLE
Librispeech Pretrained Model not getting correct results

### ISSUE THREAD

**Issue by kapursu** [SeanNaren/deepspeech.pytorch#203]
Using the the librispeech pre-trained model, I get a WER of 21.675. the command I use is: python test.py --model_path librispeech_pretrained.pth --test_manifest data/libri_test_manifest.csv

Are there any command line arguments I am missing to be able to get the WER down to what was reported?

**Comment by ryanleary** [comment]
That's probably about right. You're testing a combined set of the "clean" and "other" data.

**Comment by kapursu** [comment]
Is there a way that I can test on only the clean data set?

**Comment by ryanleary** [comment]
Yes. You will need to filter the manifest to only those documents that belong in the `test-clean` set. 

We'll probably create this automatically in the future, see #200.

**Comment by saisrinivas047** [comment]
@ryanleary @kapursu @
hi can you please tell me the steps to use pretrained model for librispeech. Does it require cuda installation.
ps-I am tring to use pretrained model in cpu
