### ISSUE TITLE
variable batch size

### ISSUE THREAD

**Issue by bchinnari** [SeanNaren/deepspeech.pytorch#206]
HI,
Currently, I see in the code that batch size is constant(say 5 or 10). Is it possible to have variable batch size? 
On top of my head, the idea coming is having an array which specifies length of each batch.

**Comment by SeanNaren** [comment]
Not entirely sure of the reasoning behind this but this is currently not supported. What are you trying to solve/do?

**Comment by bchinnari** [comment]
I tried with batch sizes of 20&10. It is giving memory error before
completing 1 epoch. I have few utterances which are above 40secs. I reduced
batch size to 5. It is giving out of memory error at 2.5 epochs.
My doubt is that these long utterances are causing the problem. I want to
push 2 of these in one batch & more short utterances in another batch.

On 26 Dec 2017 9:31 pm, "Sean Naren" <notifications@github.com> wrote:

Not entirely sure of the reasoning behind this but this is currently not
supported. What are you trying to solve/do?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SeanNaren/deepspeech.pytorch/issues/206#issuecomment-353983676>,
or mute the thread

**Comment by SeanNaren** [comment]
This is something that I know @ryanleary is looking into (changing batch sizes as the epoch moves on to reduce memory overhead). The current fix honestly is to reduce the size of the batches and limit the length of utterances. Usually between 1 to 15 seconds is a good bound (like Baidu did in their paper!)

**Comment by bchinnari** [comment]
When it successfully completed 2 epochs, I thought it would run for rest of
the epochs. Why couldn't it run past 2 epochs? What are the possible
reasons??

**Comment by ryanleary** [comment]
Are you using the `--augment` flag @bchinnari ? That flag will randomly perturb the duration of the audio making it easy for there to be an OOM. Also, there's something funky going on with the caching allocator in pytorch when coupled with this project for some reason.

**Comment by bchinnari** [comment]
I am not using data perturb.

**Comment by bchinnari** [comment]
One final question is can I limit my utterances to 20sec & use a batch size
of 20??

On 27 Dec 2017 10:01 am, "Bhargav Srinivas" <baru.anits@gmail.com> wrote:

I am not using data perturb.

**Comment by ryanleary** [comment]
After further study, this is doable, but perhaps not worth the effort. Better, as you said, to use a smaller batch size and limit the size of the utterances used. The various `data` scripts now have flags for excluding files above a certain size.
