### ISSUE TITLE
Variable lengths in minibatch

### ISSUE THREAD

**Issue by gmkim90** [SeanNaren/deepspeech.pytorch#212]
First of all, thanks for developing awesome library.

I saw the solution to deal with variable length output in minibatch from #99 (= append blank symbol for CTCloss)

How about **variable length in input minibatch** (= speech data)?
I can't see any padding or masking in model.py, data_loader.py implementation.

**Comment by SeanNaren** [comment]
Currently this isn't a priority but PRs are welcome :)
