### ISSUE TITLE
transcribe.py issue

### ISSUE THREAD

**Issue by absolutelyharsh123** [SeanNaren/deepspeech.pytorch#213]
After training and testing the deepspeech.pytorch on an4 dataset when i try to transcribe using the transcribe.py code on test audio files of an4 i get the following error: 
  
File "transcribe.py", line 45
    **DeepSpeech.get_meta(model)
     ^
SyntaxError: invalid syntax

**Comment by minushuang** [comment]
Hi, same issue when i am using scripts 'python transcribe --model models/model/path --audio_path data/audio/path'

do u have the solution now?

**Comment by absolutelyharsh123** [comment]
No solution yet. Expecting some help. As cannot get the transcribe.py to run

**Comment by ryanleary** [comment]
It's a Python 3 idiom. We'll have to change to something different to support Python 2 and 3. 

You can just remove `, DeepSpeech.get_meta(model)` in the meantime. It's not really critical.

**Comment by minushuang** [comment]
OK,Thanks for your answer,it works for me .

**Comment by ryanleary** [comment]
Fixed by #221

**Comment by ashupednekar** [comment]
Thanks a lot..... This fixed my problem
