### ISSUE TITLE
--cutoff_top_n option

### ISSUE THREAD

**Issue by yyang29** [SeanNaren/deepspeech.pytorch#219]
This isn't really an issue. Sorry for the dumb question.

I'm trying to evaluate the performance impact of beam search.

I'm wondering what does the --cutoff_top_n option do inside the beam search. How does this option diff from --beam_width option?

Thanks in advance.

**Comment by ryanleary** [comment]
I refer you to *Section 7.3* of the DeepSpeech 2 paper.

**Comment by yyang29** [comment]
Thanks for the pointer. Closing this issue.
