### ISSUE TITLE
Is it possible to have silence samples?

### ISSUE THREAD

**Issue by antorsae** [SeanNaren/deepspeech.pytorch#223]
Hi, I've successfully trained a small dataset containing 30 different words (each sample `wav` file only has one word), but I'd like to include samples with no words whatsoever, just silence. I've tried creating a manifest with the .txt file containing either ` ` (space) or `_`, however if doing so training will crash:

```
Number of parameters: 38067968
Training Summary Epoch: [1]e 0.5Average Loss 28.280a 0.003 (1.651)))	Loss 15.0038 (28.4198)))
  0%|                                                                                                                   | 0/13 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 332, in <module>
    split_targets.append(targets[offset:offset + size])
ValueError: result of slicing is an empty tensor
```
Is it possible to train silence samples? If so, what target text should be included in the `txt` manifest files?

**Comment by ryanleary** [comment]
I would just notate it with some ascii or unicode character that isn't used elsewhere (e.g. `^` or 🔇 , etc.). In the future, we may add support for multi-character labels and tags (a la `<silence>`, `<music>`, etc). We're open to PRs if that's something you'd like to add as well.

**Comment by antorsae** [comment]
Doesn't seem to work. My `labels.json`:
```
[
  "^",
  "_",
  "'",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  " "
]
```

and one line of the manifest with an offending sample:

`zero/d90b4138_nohash_2.wav,zero/d90b4138_nohash_2.txt`

`zero/d90b4138_nohash_2.txt` just contains `^` and the wav file is just silence.

**Comment by ryanleary** [comment]
Could you retry, but keep the `_` first? That represents the `blank` character in our implementation for CTC and there may be some assumptions that it comes first (we also plan to remove that requirement in future versions).

**Comment by antorsae** [comment]
Works now, thanks!
