### ISSUE TITLE
Regarding language model integration trie usecase.

### ISSUE THREAD

**Issue by Sanjeev2487** [SeanNaren/deepspeech.pytorch#225]
Why minimum_unigram_score of each word is being stored ? 

Should it not be maximum_unigram_score so that we have most probable word with that particular prefix , as we are adding it in score of uncompleted word score when any non-space character comes ? 

Also can anyone please explain what score, and delta_score represents in KenLMBeamState ?

**Comment by ryanleary** [comment]
Please update to the latest version of the decoder, we no longer need the trie file.

**Comment by Sanjeev2487** [comment]
Hi Ryan,
Actually I was also looking for a way to replace trie in my implementation. Can you explain a bit about what have you exactly  done to remove the need of trie dependency in latest version of the decoder?

**Comment by Sanjeev2487** [comment]
But I feel some kind of prefix look up should always be there in case of word based lm, which will not be  the case in character based lm. Is this what is happening in latter version ? If so how are we building char-lm as kenlm only supports word lm at the moment ?

**Comment by SeanNaren** [comment]
@Sanjeev2487 the 'trie' file in the old pytorch-ctc library iirc was the vocab of words. This is now stored within the kenlm model thus no need for a separate file
