### ISSUE TITLE
Using pre-trained model

### ISSUE THREAD

**Issue by saisrinivas047** [SeanNaren/deepspeech.pytorch#226]
Hi can someone tell me briefly the steps to use pre-trained model for librispeech. Do i have to train the dataset to use the pre-trained model?

PS-I want to try on cpu machine

**Comment by ryanleary** [comment]
> Hi can someone tell me briefly the steps to use pre-trained model for librispeech.
The readme has those instructions here: https://github.com/SeanNaren/deepspeech.pytorch#testinginference

> Do i have to train the dataset to use the pre-trained model?
No.

> PS-I want to try on cpu machine
Don't use the `--cuda` flag.

**Comment by saisrinivas047** [comment]
@ryanleary to use pretrained model for librispeech should I use test.py or transcribe.py

**Comment by SeanNaren** [comment]
@saisrinivas047 please consult the README, the information is there. It depends on what you want to do with the model.

**Comment by srinivas047** [comment]
I read the readme but I am not sure I understand, I am a little confused 

I just want to do the benchmarking using your pretrained model
