### ISSUE TITLE
what's the effect of  TED Dictionary  'TEDLIUM.152k.dic'

### ISSUE THREAD

**Issue by minushuang** [SeanNaren/deepspeech.pytorch#227]
follow the READEME instructions,I download the TED datasets. and there is a file named 'TEDLIUM.152k.dic' in  the datasets directory, we called that dictionary. But does anyone who can tell me the effect of this dictionary, or where we will use the dictionary file in the code??? because there is nothing when I use the shell of grep 'TEDLIUM.152k.dic' ./*.py

**Comment by ryanleary** [comment]
Not required for this project.

**Comment by dzubke** [comment]
The TEDLIUM.152k.dic is a mapping from words in the tedlium transcriptions to their phoneme pronunciations. It would be used to build an algorithm that predicts phonemes instead of words as the predicted classes would be phonemes and not words.
