### ISSUE TITLE
Timeline for TED?

### ISSUE THREAD

**Issue by davidyapdy** [SeanNaren/deepspeech.pytorch#23]
Any idea when will you be expanding other than an4? https://github.com/mozilla/DeepSpeech/blob/master/util/importers/ted.py 

How can I help/contribute?

**Comment by SeanNaren** [comment]
My current plan is to try get a LibriSpeech loader first before anything, and work on pre-training a few models after I finish up the skip rnn PR (which I'm running into issues thus taking time to fix). I described the loader format [here](https://github.com/SeanNaren/deepspeech.pytorch#custom-dataset) so if you want to create your own format script to load data for the tedlium corpus please go for it!

**Comment by SeanNaren** [comment]
TED has been added in #27
