### ISSUE TITLE
Segmentation error(core dumped)

### ISSUE THREAD

**Issue by wuyifat** [SeanNaren/deepspeech.pytorch#230]
I repeatedly ran into segmentation error even if I reduced batch size to ridiculously small. I was able to run benchmark.py with a much larger batch size and everything else the same.

For the record, I am running on a single titan xp with 12GB GPU RAM, hidden-size = 800, hidden-layers = 5
training batch-size = 3 (segmentation error)

benchmark batch-size = 30 (no problem, GPU RAM usage below 10GB)

Any thought is appreciated.

**Comment by ryanleary** [comment]
Please see #172.
