### ISSUE TITLE
Sudden mid-epoch NaN loss with --finetune

### ISSUE THREAD

**Issue by aaronzira** [SeanNaren/deepspeech.pytorch#232]
Finetuning a model that had successfully run for 20 epochs on a fairly large dataset, using a mixture of unseen files, as well as some that had appeared in the original training. First two epochs completed without error, and then at some point during the third, a nan loss appears, affecting the rest of the epoch. Outputs from two separate attempts at the point that the first nan loss was encountered:

> Epoch: [3][7427/24290]  Time 2.460 (2.266)      Data 0.045 (0.046)      Loss nan (nan)

> Epoch: [3][22999/24290] Time 2.394 (2.261)      Data 0.048 (0.045)      Loss nan (nan)

The run then crashes when trying to write to tensorboard:

> Epoch: [3][24289/24290] Time 2.390 (2.269)      Data 0.039 (0.046)      Loss nan (nan)
Epoch: [3][24290/24290] Time 2.466 (2.269)      Data 0.041 (0.046)      Loss nan (nan)
Training Summary Epoch: [3]     Average Loss nan
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 276/276 [05:47<00:00,  1.26s/it]
Validation Summary Epoch: [3]   Validation loss: nan    Average WER 99.998      Average CER 82.267
Traceback (most recent call last):
  File "train.py", line 397, in <module>
    tensorboard_writer.add_histogram(tag, to_np(value), epoch + 1)
  File "/...\<conda env\>.../lib/python3.6/site-packages/tensorboardX/writer.py", line 305, in add_histogram
    self.file_writer.add_summary(histogram(tag, values, bins), global_step)
  File "/...\<conda env\>.../lib/python3.6/site-packages/tensorboardX/summary.py", line 113, in histogram
    hist = make_histogram(values.astype(float), bins)
  File "/...\<conda env\>.../lib/python3.6/site-packages/tensorboardX/summary.py", line 121, in make_histogram
    counts, limits = np.histogram(values, bins=bins)
  File "/...\<conda env\>.../lib/python3.6/site-packages/numpy/lib/function_base.py", line 670, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.

Could this have something to do with the fact that some of the files were in the original run? I can't understand why it would take until the third epoch to produce a nan. Any ideas?

**Comment by ryanleary** [comment]
May have something to do with learning rates? NaN loss typically occurs due to exploding gradients.

**Comment by EgorLakomkin** [comment]
It could also happen that you might got an empty audio file in your data and z-normalization produced nan's in your input

**Comment by ryanleary** [comment]
@aaronzira any success tracking this down?

**Comment by aaronzira** [comment]
My original thought was that an empty file had found its way in, but after thorough checks there were no such files, and it seemed particularly strange that it would only happen after two successful epochs. 

It does look to have been related to the learning rate, as the first run had gone through 19 epochs, but starting a new run using the --finetune flag with no provided --lr argument brought it back to the default of 3e-4. The current --finetune run has only completed 4 epochs due to another issue interrupting training, but it looks as expected now, having begun with a learning rate of 5.9e-5, which was about where it had left off on the previous run (5.4e-5) after default annealing. Good call @ryanleary!
