### ISSUE TITLE
How to  make the label on  when trainning Mandarin model 

### ISSUE THREAD

**Issue by minushuang** [SeanNaren/deepspeech.pytorch#235]
the sample above is about English,doesn't mention about Mandarin. I download the dataset data_thchs30 which is Mandarin.How to make the Mandarin label on this project?

**Comment by ryanleary** [comment]
Tokenize the mandarin data and select the set of characters you want the recognizer to be able to predict. Create a new labels.json file with those tokens included in the array. Ensure that the first element in the array is a `_`.

**Comment by minushuang** [comment]
Thanks for your reply. Another question, does all of the English model can use this labels.json include 29 characters in this project? I check the ted and an4 model, the labels they are using are these 29 characters.  Does that mean the only thing I need to do is modify the labels.josn that include all of the  Mandarin characters when I train a Mandarin model?

**Comment by ryanleary** [comment]
Yes.

**Comment by minushuang** [comment]
How to make the train sets  and the label One-to-one correspondence?Ah,I am from computer vision...

**Comment by minushuang** [comment]
I know the effects of the lable.json. the character will correspondend to a  integer label with the label.json reference the code of docoder.py, and that's the label I understood. thank u very much.
