### ISSUE TITLE
Issues with pre trained model

### ISSUE THREAD

**Issue by slbinilkumar** [SeanNaren/deepspeech.pytorch#238]
Hi,
When testing with large wav files say 65 MB . System is getting out of memory error. Please let me know about the issue?
Any change in the code will solve this issue?
or segment the large file to some small files will solve it?

**Comment by ryanleary** [comment]
You will have to segment the audio into smaller pieces. Recommend using a voice activity detector to determine periods of silence/unvoiced speech to split on.
