### ISSUE TITLE
Different model sizes for pretrained models

### ISSUE THREAD

**Issue by antspy** [SeanNaren/deepspeech.pytorch#242]
Hi, 

Great repo! :-) 

I have a question about the pretrained models. If I create a model with the indicated options (rnn_hidden_size=800, nb_layers=5, rnn_type= 'gru',bidirectional=False) I get a model that is around 78 MB (around 19.5 million parameters). The size of your pretrained models is around 291 MB, so I was wondering where does this inconsistency come from! 

Thanks :-)

**Comment by ryanleary** [comment]
The pretrained models are bidirectional (roughly 2x bigger) and contain the optimizer state (roughly another 2x larger).
