### ISSUE TITLE
Not able to use multi-gpu : NCCL error

### ISSUE THREAD

**Issue by vaibhav0195** [SeanNaren/deepspeech.pytorch#244]
Hi,
I tired running the network on my custom data. the code works fine on single gpu but when i try to use both the gpu then i get the following error:
**************************************************************************************************************
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    out = model(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 67, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 72, in replicate
    return replicate(module, device_ids)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/replicate.py", line 12, in replicate
    param_copies = Broadcast.apply(devices, *params)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 17, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 63, in broadcast_coalesced
    results = broadcast(flat, devices)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 26, in broadcast
    nccl.broadcast(tensors)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/nccl.py", line 50, in broadcast
    torch._C._nccl_broadcast(inputs, root)
**RuntimeError: NCCL Error 2: system error**
************************************************************************************************
i then reinstalled the pytorch from the source to get the default nccl settings but the error remained.
i also tried using the conda for the same but the same error was still there.

I have 2 nvidia 1080TI and I am using python2.7 with pytorch version3 and with cuda8 and cudnn6. 
could you guys please tell me how did you run this multigpu environment ?

**Comment by SeanNaren** [comment]
Could you try the master? There is also some instructions [here](https://github.com/SeanNaren/deepspeech.pytorch#multi-gpu-training) to run! I'd suggest using the `gloo` backend for now.

**Comment by vaibhav0195** [comment]
hi 
I have been able to run the multi gpu server using your new distributed code. 
but I had the following issue to getting it run on a volta multi gpu machine having cuda 9 and cudnn7

torch gave me an error saying
torch.distributed has no attribute backend..

ihave commented the lines and have set the value of warn_on_half==False and it is working fine. i think the error is due to some version mismatch of pytorch ?

**Comment by SeanNaren** [comment]
@vaibhav0195 god I've run into this...  you're workaround is fine, another fix is to remove the `import distributed` at the top of the training script, and change `distributed.DistributedDataParallel` to use `torch.nn.parallel.DistributedDataParallel`. Some mistmatch between this custom distribution and pytorch.

**Comment by vaibhav0195** [comment]
hey,
I have run into some issue everytime my epoch finishes and my validation is loss is calculated i get this error as follows
***********************************************************
Traceback (most recent call last):
  File "train.py", line 293, in <module>
    loss.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/home/ubuntu/deepspeech2/data/distributed.py", line 51, in allreduce_params
    dist.all_reduce(coalesced)
  File "/usr/local/lib/python2.7/dist-packages/torch/distributed/__init__.py", line 216, in all_reduce
    return torch._C._dist_all_reduce(tensor, op, group)
RuntimeError: [/pytorch/torch/lib/gloo/gloo/transport/tcp/buffer.cc:76] Read timeout [127.0.0.1]:8355
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /pytorch/torch/lib/gloo/gloo/cuda.cu:249] error == cudaSuccess. 29 vs 0. Error at: /pytorch/torch/lib/gloo/gloo/cuda.cu:249: driver shutting down
['train.py', '--cuda', '--world-size', '4', '--rank', '0', '--gpu-rank', '0']
['train.py', '--cuda', '--world-size', '4', '--rank', '1', '--gpu-rank', '1']
['train.py', '--cuda', '--world-size', '4', '--rank', '2', '--gpu-rank', '2']
['train.py', '--cuda', '--world-size', '4', '--rank', '3', '--gpu-rank', '3']
******************

i looked up in the forums they say that such occur when cuda drivers are being reloaded into the code but if the program runs in a single go then this shouldn't be a problem.

any help would be appreciated..

**Comment by pankajkumar** [comment]
I am also receiving the same Read timeout error while using the Lookahead layer, otherwise it was working fine. Any ideas what's causing it?

**Comment by pankajkumar** [comment]
It's a pytorch issue:- 

[https://github.com/pytorch/pytorch/issues/2530](https://github.com/pytorch/pytorch/issues/2530)

**Comment by cslxiao** [comment]
Meet the same problem. And it happens randomly.

**Comment by Diamondfan** [comment]
@vaibhav0195  have you solved problem. I met the same situation as you.  when i run the code on small dataset lets say 100 files for train then it runs fine. but for the big dataset it throws the runtime error.

**Comment by miguelvr** [comment]
is this with the distributed option? I never managed to get that to work. I always run with the default --cuda option to use the regular nn.DataParallel module

**Comment by Diamondfan** [comment]
yes, it happened when using DDP and nn.DataParallel is fine.
