### ISSUE TITLE
why low test WER on CHiME, training on librispeech Acoustic Model

### ISSUE THREAD

**Issue by gmkim90** [SeanNaren/deepspeech.pytorch#249]
Librispeech provides fairly large amounts of speech (960hour) which is recorded from various recording environment. So I expect training acoustic model on this corpus will also works for speech in another domain, such as CHiME-3.

For acoustic model, deepspeech model is trained with librispeech corpus. 
For language model, 4-gram (from http://www.openslr.org/11/) is used.

It achieve 7.6% WER on test-clean, 24.8% WER on test-other.

However, this model is not working to recognize CHiME-3 data.

Clean evaluation dataset got WER 64.2%, Cafe-noise evaluation dataset got 83.7% WER.

What could be the possible reason for degradation?

**Comment by SeanNaren** [comment]
The amount of data is still not enough to train a model that can transfer to other domains. I'd suggest training a model with a collation of openly available data as well as any other data sources you may have. The model trained on librispeech is not good enough!
