### ISSUE TITLE
Results overview

### ISSUE THREAD

**Issue by stefbraun** [SeanNaren/deepspeech.pytorch#251]
Hi, thanks for sharing this ASR pipeline! The training script is packed with a ton of options, e.b. batch-norm, bidirectional etc. However, I cannot find a comparison of what results to expect with some of the options. Is there such a table or would it be a valuable contribution to try out some options and contribute results? Maybe the necessary experiments could be covered by several interested people to distribute the workload.

Thanks, Stefan

**Comment by ryanleary** [comment]
I would refer you to the deepspeech 2 paper. Most of those options are covered there. The results we've seen so far more or less follow the paper (though we have less data to train on than they did, so things are a bit worse across the board).
