### ISSUE TITLE
"customizing" an existing model

### ISSUE THREAD

**Issue by delip** [SeanNaren/deepspeech.pytorch#255]
Can I use this code to use one of the existing models (say Librispeech) and finetune a custom vocabulary? I have a small domain-specific corpus (audio+transcription) that I would like to adapt. Any pointers that would be helpful.  Thanks!

PS: my current thinking is simply to "merge" librispeech with this custom dataset and retrain, but hoping there is a simpler solution.

**Comment by ryanleary** [comment]
Yes. You can already finetune using the existing parameters. Look at the `--continue-from` and `--finetune` flags. You can simply start with the librispeech weights and then train against a new corpus. There are a number of improvements you could make beyond that depending on your exact use case.
