### ISSUE TITLE
has no attribute 'libthsox_Variable_read_audio_file'

### ISSUE THREAD

**Issue by xiaoC1314** [SeanNaren/deepspeech.pytorch#259]
logs:
File "/root/anaconda3/lib/python3.6/site-packages/torchaudio-0.1-py3.6-linux-x86_64.egg/torchaudio/__init__.py", line 61, in load
    func = getattr(th_sox, 'libthsox_{}_read_audio_file'.format(typename))
AttributeError: 
module 'torchaudio._ext.th_sox' has no attribute 'libthsox_Variable_read_audio_file'

anyone hava idea?

**Comment by mansur007** [comment]
same issue... please let me know if you fixed it

**Comment by ryanleary** [comment]
Make sure your torchaudio release is compatible with your pytorch release.
