### ISSUE TITLE
ImportError warpctc

### ISSUE THREAD

**Issue by zhangying0127** [SeanNaren/deepspeech.pytorch#264]
I think i did everything right in install. but still get this import error. 

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from warpctc_pytorch import CTCLoss
  File "build/bdist.linux-x86_64/egg/warpctc_pytorch/__init__.py", line 8, in <module>
ImportError: No module named _warp_ctc

**Comment by xuewenyuan** [comment]
I have met the same issue. Have you solve this problem?

**Comment by nedanov** [comment]
yep. same error here too.

**Comment by Eric-Chen-007** [comment]
same error. 
even tried install anaconda.
not work yet.

**Comment by Miyamizu** [comment]
+1 how to fix it?

**Comment by ryanleary** [comment]
These are issues related to warp-ctc. See seannaren/warp-ctc#31.
