### ISSUE TITLE
Issue about pre-trained model:  [torch.LongTensor of size ()]

### ISSUE THREAD

**Issue by JosephPai** [SeanNaren/deepspeech.pytorch#269]
My Command: 
python test.py --model-path pre/librispeech_pretrained.pth --test-manifest 
 data/libri_test_clean_manifest.csv 

Output: 
 0%|                                                                                                   | 0/131 [00:00<?, ?it/s]test.py:67: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)
Traceback (most recent call last):
  File "test.py", line 88, in <module>
    decoded_output, _, = decoder.decode(out.data, sizes)
  File "/home/ASR/deeptorch/deepspeech.pytorch/decoder.py", line 196, in decode
    remove_repetitions=True, return_offsets=True)
  File "/home/ASR/deeptorch/deepspeech.pytorch/decoder.py", line 156, in convert_to_strings
    string, string_offsets = self.process_string(sequences[x], seq_len, remove_repetitions)
  File "/home/ASR/deeptorch/deepspeech.pytorch/decoder.py", line 169, in process_string
    char = self.int_to_char[sequence[i]]
KeyError: 
 0
[torch.LongTensor of size ()]

----------------------------------------------------

when I use transcribe.py for the pretrained.pth, the output is the same as above

**Comment by SeanNaren** [comment]
I think this is an issue if you build on top of the master/0.4 release. Could you try installing from conda/0.3.1 release and see if you get the same issue?

**Comment by JosephPai** [comment]
@SeanNaren 
Do you mean to use the the source code in v1.0 release ?
Or could you give a link of commit hash for download.
Thank you so much.

**Comment by SeanNaren** [comment]
try installing the binaries first here https://github.com/pytorch/pytorch#binaries

**Comment by JosephPai** [comment]
@SeanNaren 
Sovled !
Thank you very much ~!

**Comment by himanshudce** [comment]
i got the same error with unexpected translation.
