### ISSUE TITLE
Data load time sometimes too slow

### ISSUE THREAD

**Issue by Eric-Chen-007** [SeanNaren/deepspeech.pytorch#270]
When i train CTC using train.py, i sometimes find data load costing too much time.
In the first epoch, the train data usually in a sorted order.
So the continuous batches in the first epoch should have nearly the same size. The loading time should nearly the same.
But I find sometime it took 0.1 seconds to load one batch, then the next batch it sometimes took 10 or more seconds to load data.
Does anyone find the same problem ?

I use python 2.7, and pytorch(py27_cuda9.0.176_cudnn7.0.5_2) 0.3.1.

**Comment by ryanleary** [comment]
What kind of disk and filesystem are you loading from? You could also try increasing the number of workers for the data loader (it's a train.py flag). Chances are this is specific to your system.

**Comment by Eric-Chen-007** [comment]
@ryanleary , thanks a lot for your reply.
I am running on hard disk, Centos 7 system, and filesystem is ext4.
I tried to increasing the number of workers (4 -> 12), 
it improves,  but it is still very slow on some batch (data loading time).
The frequency drops.

**Comment by ryanleary** [comment]
The data was local on both machines? Not using NFS or anything like that? Other processes running on the machines?

I've used this code on Ubuntu, Centos, OSX, across literally dozens of differently configured systems and haven't seen anything quite like this.

**Comment by Eric-Chen-007** [comment]
@ryanleary, yes, both machines use local hard disk.
Not using NFS or anything like NFS.
No other process running on the machines.

I read the code of dataloader carefully, but find nothing suspicious.
It troubles me.

**Comment by ryanleary** [comment]
I would try profiling the python code and stopping it as soon as you see it hang. Perhaps that will give some clue to where it's blocking.

**Comment by Eric-Chen-007** [comment]
@ryanleary , thanks a lot.
I am a beginner of pytorch, but i'll try to figure out this problem.

**Comment by Eric-Chen-007** [comment]
I read the pytorch code of Dataloader.

Then there is some special case.
For example,  we set num_workers = 10.
The Dataloader would first put 10*2 = 20 batch(index) in the "index_queue".
1
2
..
20
Waiting the 10 workers to process.

First, i find the Dataloader would put a new batch index in the "index_queue", only when we get the current request batch index (processed one).
For some special reason, the 1 (first) batch is the slowest one.
2~20 batches finish their computation earlier, and stored in "reorder_dict", then the left 9 workers are just waiting there, do nothing. 
When we finally get the processed first batch(1), the "index_queue” would be empty.
Then we put 21th batch in "index_queue".

Then we calculate the 1 batch in GPU Train.
And 2~20 batch in GPU Train.
If the GPU process is very quick.
But processing 21th new batch (load data, process data, extract audio feature) is very slow, slower than 1~20 batch in GPU processing. 
Then it would stuck.

**Comment by AlbertLZG** [comment]
I also meet this problem, is there any good solution to solve it? Pytorch's dataloader is too slow when processing large dataset.

**Comment by MisonoMayu** [comment]
I am experiencing the similar problem. It becomes more often When I set a larger batch size or use a more powerful gpu.
