### ISSUE TITLE
LookAhead layer vs Bi-rnn performance comparision

### ISSUE THREAD

**Issue by tarun73** [SeanNaren/deepspeech.pytorch#274]
Hi,
these are the two models i am training:
1. 3 X Bi-rnn , 2560 nodes  ==> Number of parameters: 66040608
2. 3 X rnn , 2560 nodes , lookahead layer with context 20. ==> Number of parameters: 33244448

machine config:
12 vCPUs, 64 GB memory
4 x NVIDIA Tesla P100

training on a distributed data parallel set up:
in scenario 1, though the number of parameters is more i am able to use a **batch size of 45** but in model 2 i am able to use only a **batch size of 10**.
My question is - 
Why is the use of LookAhead layer causing a drastic reduction in batch size?
(My understanding is the lookAhead layer is introduced to increase the training speed but i see a contradiction here)

**Comment by adityabansal727** [comment]
Same issue. Did anyone find an explanation?

**Comment by Rasmusafj** [comment]
@adityabansal727 I think the explanation might be that the current lookahead implementation stacks the context windows with the data before computing the output.
