### ISSUE TITLE
Results from transcribe.py and --offset error

### ISSUE THREAD

**Issue by dalcazar** [SeanNaren/deepspeech.pytorch#280]
Hi,

I am tyring to train a model with the docker container and when I run transcribe.py I get a JSON with a array of transcriptions:

python transcribe.py --model-path ../data/new-model/deepspeech_checkpoint_epoch_1_iter_5000.pth.tar --audio-path ../data/audios-prueba/in1.wav --cuda

{"output": [{"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}, {"transcription": ""}

Is this right? I don't know if now it returns for each recognized label an object with the transcription. I remember in previous versions the transcription was returned as a text.

Also, if I include the --offset param, I get an error:

root@e3168410529e:/workspace/deepspeech.pytorch# python transcribe.py --model-path ../data/new-model/deepspeech_checkpoint_epoch_1_iter_5000.pth.tar --audio-path ../data/audios-prueba/in1.wav --offsets --cuda
Traceback (most recent call last):
  File "transcribe.py", line 91, in <module>
    print(json.dumps(decode_results(model, decoded_output, decoded_offsets)))
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'IntTensor' is not JSON serializable

**Comment by Wilbur529** [comment]
Maybe you can try to remove the No.89 line of transcribe.py.

`out = out.transpose(0, 1)  # TxNxH`

I was also confused with this problem before, and i thought this line may be not useful.

**Comment by ryanleary** [comment]
Fixed in 4b0f7a9 and 99fee14. Thanks for the report.
