### ISSUE TITLE
How to get a sentence output from the transcribe.py instead of array of transcription

### ISSUE THREAD

**Issue by saibharani** [SeanNaren/deepspeech.pytorch#283]
I want to get a sentence as output instead of an array of possible transcription of characters. I tried using beam decoder and language model from openslr it also gives character transcription but i want a sentence as output. Thank you in advance.

**Comment by ryanleary** [comment]
Fixed in 4b0f7a9. Please repull master and it will work.

**Comment by saibharani** [comment]
Thank you
