### ISSUE TITLE
Problem with CTC decoder

### ISSUE THREAD

**Issue by lydiaji** [SeanNaren/deepspeech.pytorch#288]
I want to transcribe audio file with ctc decoder, but it seems something went wrong.
Does anyone know how to solve this problem?
Please kindly see as follows:

root@86137435ed59:/data/deepspeech.pytorch# python3 transcribe.py --model-path models/deepspeech_final.pth --cuda --decoder beam --lm-path /data/ctcdecode/third_party/kenlm --audio-path /data/bill_gates-TED.mp3

Loading the LM will be faster if you build a binary file.
Reading /data/ctcdecode/third_party/kenlm
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Traceback (most recent call last):
  File "transcribe.py", line 80, in <module>
    beam_width=args.beam_width, num_processes=args.lm_workers)
  File "/data/deepspeech.pytorch/decoder.py", line 99, in __init__
    num_processes, blank_index)
  File "/usr/local/lib/python3.5/dist-packages/ctcdecode-0.3-py3.5-linux-x86_64.egg/ctcdecode/__init__.py", line 17, in __init__
    self._num_labels)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/__init__.py", line 180, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: /data/ctcdecode/third_party/kenlm/util/file.cc:183 in std::size_t util::PartialRead(int, void*, std::size_t) threw FDException because `ret < 0'.
Is a directory in /data/ctcdecode/third_party/kenlm while reading 6 bytes in file /data/ctcdecode/third_party/kenlm

**Comment by ryanleary** [comment]
Is `kenlm` the actual language model? The error seems to indicate that is a directory.

**Comment by lydiaji** [comment]
Thanks for your reply. Now I downloaded a 3-gram language model and tried to run test.py. The result is as follows and seems not so correct. How should I solve it? Thanks!

root@86137435ed59:/data/deepspeech.pytorch# python3 transcribe.py --model-path models/deepspeech_final.pth --cuda --decoder beam --lm-path /data/3-gram.arpa --audio-path /data/bill_gates-TED.mp3
Loading the LM will be faster if you build a binary file.
Reading /data/3-gram.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
{"output": [{"transcription": "A ALOHA CA O UPON R AA AA A C O OF A OR"}], "_meta": {"language_model": {"name": "3-gram.arpa"}, "acoustic_model": {"version": "0.0.1", "hidden_size": 800, "rnn_type": "gru", "name": "deepspeech_final.pth", "hidden_layers": 5}, "decoder": {"alpha": 0.8, "lm": true, "beta": 1, "type": "beam"}}}

**Comment by ryanleary** [comment]
Probably need to tune the alpha and beta parameters. Appears to be working though.
