### ISSUE TITLE
Seg fault in transcribe.py when using a LM

### ISSUE THREAD

**Issue by miguelvr** [SeanNaren/deepspeech.pytorch#293]
I'm trying to transcribe with a pretrained LIbriSpeech DeepSpeech model with a Beam CTC Decoder and a KenLM language model, but I'm getting a LM related segmentation fault:

I'm running the following script:
`python transcribe.py --model-path /workspace/deepspeech.pytorch/models/librispeech_pretrained.pth --audio-path /data/LibriSpeech/val/wav/2277-149874-0012.wav --decoder beam --lm-path /workspace/deepspeech.pytorch/models/lm_csr_64k_vp_3gram.arpa`

I can run the same script without the `--lm-path` flag with no problems.

Is this a know problem?

Best,
Miguel

PS: I got the LM file from [here](http://www.keithv.com/software/csr/)
PPS: This might be a CTCDecoder incompatibility issue with pytorch 0.4

**Comment by miguelvr** [comment]
@SeanNaren  the problem is solved. The LM binary was faulty. Trained my own LM with KenLM and it worked fine :)

**Comment by SeanNaren** [comment]
glad you got it fixed :)
