### ISSUE TITLE
KeyError: tensor(0)

### ISSUE THREAD

**Issue by ayushmangupta1990** [SeanNaren/deepspeech.pytorch#296]
Epoch: [1][44/45]       Time 49.997 (20.081)    Data 0.022 (0.016)      Loss 62.5453 (71.7439)
Epoch: [1][45/45]       Time 51.765 (20.785)    Data 0.026 (0.016)      Loss 85.5225 (72.0051)
Training Summary Epoch: [1]     Time taken (s): 935     Average Loss 72.050
  0%|                                                                                                                               | 0/7 [00:00<?, ?it/s]train.py:344: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs = Variable(inputs, volatile=True)

Traceback (most recent call last):
  File "train.py", line 360, in <module>
    decoded_output, _ = decoder.decode(out.data, sizes)
  File "/ayu-disk/deepspeech.pytorch/decoder.py", line 196, in decode
    remove_repetitions=True, return_offsets=True)
  File "/ayu-disk/DS/deepspeech.pytorch/decoder.py", line 156, in convert_to_strings
    string, string_offsets = self.process_string(sequences[x], seq_len, remove_repetitions)
  File "/ayu-disk/DS/deepspeech.pytorch/decoder.py", line 169, in process_string
    char = self.int_to_char[sequence[i]]
KeyError: tensor(0)

**Comment by ryanleary** [comment]
#290

**Comment by MilkWYX** [comment]
Maybe you can use 
char = self.int_to_char[sequence[i].item()]
