### ISSUE TITLE
how to select the GPU (0 or 1)  for training

### ISSUE THREAD

**Issue by ayushmangupta1990** [SeanNaren/deepspeech.pytorch#297]
I have two GPU machine 
Is there any way to make train.py to run on GPU 1: not in GPU 0:(want to use GPU 1 for training)

Is there any way to pass this as the argument.

**Comment by miguelvr** [comment]
I added that option in #294, with the flag `--device-ids`. It just got merged

**Comment by ayushmangupta1990** [comment]
Thanks
