### ISSUE TITLE
pre-trained model trained on all 3 data sets

### ISSUE THREAD

**Issue by zenogantner** [SeanNaren/deepspeech.pytorch#299]
This is a wishlist item, and I do not know whether it would make sense: How about a model that is trained on all 3 datasets (AN4, LibriSpeech, TEDLIUM)?

**Comment by miguelvr** [comment]
I could help with that. I already have a pretrained model for LibriSpeech that outperforms the current version that is provided, with 7.7% WER

**Comment by SeanNaren** [comment]
If you could uploaded it somewhere accessible I would love to update the current models with that @miguelvr

**Comment by ryanleary** [comment]
@miguelvr was that trained only on Librispeech training data? What was the architecture? If you're willing to provide it, we'll get it uploaded here on github as well.

**Comment by miguelvr** [comment]
I have to check if I am allowed to share the model as this was obtained with company resources. But all in all, I trained with the default parameters, only with LibriSpeech data, but let the training run for 30 epochs instead of 15 (took about a week of training). Will get back to you soon with more info on this.

**Comment by miguelvr** [comment]
Finally got approval for this:
https://drive.google.com/file/d/10WNiZej3UYC9K_QVZwXdRslSyzcgmM1f/view?usp=sharing

```
Details:
                          WER       CER
Librispeech test clean    7.758     2.897
Librispeech test other    22.823    10.495
```

If you can then upload it to github that would be ideal.

Best,
Miguel

**Comment by ryanleary** [comment]
Thanks Miguel for the contrib! I'll see about getting it uploaded to github today.

**Comment by ryanleary** [comment]
@miguelvr following up -- I downloaded the model and got similar numbers as you using a language model, but with the standard greedy decoder, the results were roughly a point worse than our pretrained model. Do you see this as well?

**Comment by miguelvr** [comment]
@ryanleary I just tried with a language model, but will report the results with a GreedyDecoder

**Comment by ryanleary** [comment]
@miguelvr so you should know that the numbers reported for the models on the Releases page are achieved with only the greedy decoder. So I think the performance of that Librispeech model is slightly better than the one you uploaded. It was trained pretty much with the default except that the `--augment` flag was also specified.

**Comment by zenogantner** [comment]
@miguelvr  Thank you for sharing your model. I evaluated with the BeamCTCDecoder and the 4-gram language model from http://www.openslr.org/11/, and it is slightly better for low noise recordings, and not so good with more noise, on my own evaluation dataset (224 utterances):

```
                 CER      WER      Accuracy
deepspeech_librispeech_best.pth
low noise:       0.1674   0.3331   0.2768
medium noise:    0.3488   0.5785   0.0792

librispeech_pretrained.pth
low noise:       0.1934   0.3649   0.2857
medium noise:    0.3458   0.546    0.1031

Mozilla DeepSpeech 0.1.1
low noise:       0.1433   0.3329   0.3065
medium noise:    0.3372   0.6072   0.0562

```

Mozilla's DeepSpeech has even more trouble with noisy recordings, and is roughly as good as @miguelvr's model for low-noise recordings. Note that Mozilla DS has been trained on Fisher, LibriSpeech, and Switchboard.

So from my point of view, it is really hard to tell which model I would use.

**Comment by hoyden** [comment]
@miguelvr I'm training this model on Mandarin corpus recently.Could you tell me your parameter setting?THX

**Comment by miguelvr** [comment]
@hoyden I used the default parameters, but you'll have to adjust based on the amount of data you have available

**Comment by hoyden** [comment]
@miguelvr I have only 100+ hours data. I try to train it on default parameters and adjust several times.But the result was not as good as i want, the CER was still up to 16%. Could you give me some advice?

**Comment by miguelvr** [comment]
100h is too little data for this model, as far as I know. My best advice would be to use a GMM-HMM or a hybrid DNN-HMM model, that are able to perform better with lower amounts of data. Have a look into [Kaldi](https://github.com/kaldi-asr/kaldi).

**Comment by archiki** [comment]
> Finally got approval for this:
> https://drive.google.com/file/d/10WNiZej3UYC9K_QVZwXdRslSyzcgmM1f/view?usp=sharing
> 
> ```
> Details:
>                           WER       CER
> Librispeech test clean    7.758     2.897
> Librispeech test other    22.823    10.495
> ```
> 
> If you can then upload it to github that would be ideal.
> 
> Best,
> Miguel

@miguelvr  which commit has did you use while evaluating these results ? I am not able to reproduce the same and the numbers are quite bad. Will be great help if you could share the hash or the code files. 
Thanks

**Comment by altavatarindia** [comment]
I trained the model on 4 included datasets (except an4, which I somehow missed using), and uploaded the model too. Please see here: https://github.com/altavatarindia/deepspeech-releases/releases/tag/1-0-0-stable

**Comment by altavatarindia** [comment]
@miguelvr I would love to know too your model architecture, if you could share it. Thank you.
