### ISSUE TITLE
Run workload in docker error.

### ISSUE THREAD

**Issue by linrio** [SeanNaren/deepspeech.pytorch#300]
I want to run the deepspeech workload in docker. Followed by the step of [MLperf-speech_recognition-deepspeech](https://github.com/mlperf/reference/tree/master/speech_recognition) 

However, there is an error I do not know how to fix it: [Run in docker error](https://github.com/mlperf/reference/issues/47).

**Comment by SeanNaren** [comment]
This isn't totally related to the code here, but I'd suggest checking the input wav files, it seems they might be corrupted or something.
