### ISSUE TITLE
Using optional Kenlm language model???

### ISSUE THREAD

**Issue by byuns9334** [SeanNaren/deepspeech.pytorch#301]
Hi,  I have 2 questions regarding using KenLM.

1. In default setting of deepspeech.pytorch with beam search decoder, Is KenLM used? If it is, how is KenLM trained? Which (language model) dataset is KenLM trained on? 

2. If I want another dataset to be merged for training KenLM, what exactly should I do? or Is there some link about this? 

Thanks so much for reading!!

**Comment by zenogantner** [comment]
I have a related question: Would it make sense to offer pre-trained language models for download?
E.g. under https://github.com/SeanNaren/deepspeech.pytorch/releases

**Comment by ryanleary** [comment]
By default, only a greedy decoder is used (and these are the reported numbers for the pretrained models). If you want to use beam search (with or without a language model) you have to specify that at evaluation/inference time.

Instructions on how to train an n-gram language model is largely out of scope for this project, though there are some notes about it in the README. Trained language models are, in many cases, best when they're domain specific. To that end, for instance, with librispeech there are already pretrained language models made available on openslr.org.

**Comment by kmario23** [comment]
If someone is looking for a guide to train Kenneth Heafield's KenLM model, here's the repo:  [kmario23/KenLM-training](https://github.com/kmario23/KenLM-training)
