### ISSUE TITLE
fatal error: THC/THC.h: No such file or directory when compiling warp-ctc (python binding)

### ISSUE THREAD

**Issue by zhang-jian** [SeanNaren/deepspeech.pytorch#302]
When compiling warp-ctc (python binding), I got **fatal error: THC/THC.h: No such file or directory** 

**Python version:**
<pre>
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
</pre>
**Pytorch version:**
<pre>
torch                              0.4.0      
torchvision                        0.2.1      
</pre>

Error Log:
<pre>
user@gpu00:/scratch/user/tools/warp-ctc/build$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /scratch/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-8.0.61-oehfcuf3do4bwagkarjurizvcsrl7y2q (found suitable version "8.0", minimum required is "6.5") 
-- cuda found TRUE
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/user/tools/warp-ctc/build
user@gpu00:/scratch/user/tools/warp-ctc/build$ make
[ 11%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
[ 22%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_ctc_entrypoint.cu.o
Scanning dependencies of target warpctc
[ 33%] Linking CXX shared library libwarpctc.so
[ 33%] Built target warpctc
Scanning dependencies of target test_cpu
[ 44%] Building CXX object CMakeFiles/test_cpu.dir/tests/test_cpu.cpp.o
[ 55%] Building CXX object CMakeFiles/test_cpu.dir/tests/random.cpp.o
[ 66%] Linking CXX executable test_cpu
[ 66%] Built target test_cpu
[ 77%] Building NVCC (Device) object CMakeFiles/test_gpu.dir/tests/test_gpu_generated_test_gpu.cu.o
Scanning dependencies of target test_gpu
[ 88%] Building CXX object CMakeFiles/test_gpu.dir/tests/random.cpp.o
[100%] Linking CXX executable test_gpu
[100%] Built target test_gpu
user@gpu00:/scratch/user/tools/warp-ctc/build$ cd ../pytorch_binding
user@gpu00:/scratch/user/tools/warp-ctc/pytorch_binding$ python setup.py install
generating build/warpctc_pytorch/_warp_ctc/__warp_ctc.c
(already up-to-date)
not modified: 'build/warpctc_pytorch/_warp_ctc/__warp_ctc.c'
running install
running bdist_egg
running egg_info
writing warpctc_pytorch.egg-info/PKG-INFO
writing dependency_links to warpctc_pytorch.egg-info/dependency_links.txt
writing top-level names to warpctc_pytorch.egg-info/top_level.txt
reading manifest file 'warpctc_pytorch.egg-info/SOURCES.txt'
writing manifest file 'warpctc_pytorch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying warpctc_pytorch/_warp_ctc/__init__.py -> build/lib.linux-x86_64-3.6/warpctc_pytorch/_warp_ctc
running build_ext
building 'warpctc_pytorch._warp_ctc.__warp_ctc' extension
gcc -pthread -B /scratch/user/tools/anaconda3.6/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/scratch/user/tools/warp-ctc/include -I/scratch/user/tools/anaconda3.6/include/python3.6m -c build/warpctc_pytorch/_warp_ctc/__warp_ctc.c -o build/temp.linux-x86_64-3.6/build/warpctc_pytorch/_warp_ctc/__warp_ctc.o -std=c++11 -fPIC -DWARPCTC_ENABLE_GPU
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
In file included from /scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THVector.h:5:0,
                 from /scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/TH.h:12,
                 from build/warpctc_pytorch/_warp_ctc/__warp_ctc.c:492:
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_polevl’:
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:134:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i <= len; i++) {
   ^
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:134:3: note: use option -std=c99 or -std=gnu99 to compile your code
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_polevlf’:
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:142:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i <= len; i++) {
   ^
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigamma’:
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:260:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 6; ++i) {
   ^
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h: In function ‘TH_trigammaf’:
/scratch/user/tools/anaconda3.6/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THMath.h:278:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 6; ++i) {
   ^
build/warpctc_pytorch/_warp_ctc/__warp_ctc.c: At top level:
build/warpctc_pytorch/_warp_ctc/__warp_ctc.c:493:21: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
                     ^
compilation terminated.
error: command 'gcc' failed with exit status 1
</pre>

**Comment by miguelvr** [comment]
have you tried installing with docker? it should work that way

**Comment by zhang-jian** [comment]
No I haven't tried to use docker.

**Comment by mansur007** [comment]
i had the same issue on my laptop with no cuda support.
I realized that i should have omitted "export CUDA_HOME="/usr/local/cuda"" line from 
the installation instructions.

**Comment by rancheng** [comment]
`THC` was removed in pytorch `1.11`, please make sure you do the following change by replacing the dependencies:

```cpp
// #include <THC/THC.h>
#include <ATen/cuda/CUDAContext.h>
...
at::cuda::getCurrentCUDAStream();
```

this is a simple example, you can try to replace all `THC` based functions by `ATen`
