### ISSUE TITLE
Increasing memory usage on the first GPU

### ISSUE THREAD

**Issue by EgorLakomkin** [SeanNaren/deepspeech.pytorch#305]
I tried to train the model with the updated deepspeech.pytorch version (pytorch 0.4) on the 4x GPU and what I see is that memory usage is constantly increaing on the 1st GPU. Any ideas why this could happen or did anybody observe something like this?

**Comment by miguelvr** [comment]
I trained on a DGX-1 with 4x V100 and didn't notice that behaviour on the 1st GPU, the GPU memory was evenly distributed.

However, after the first epoch, I noticed the training speed started decreasing a bit, but after a while stabilizes (although still slower).

I did the 0.4 update and might have missed something, but I pretty much followed the migration guide suggested by the pytorch team

**Comment by EgorLakomkin** [comment]
Will close this as it really could be a problem with my set-up. If I will find out anything - I will post here
