### ISSUE TITLE
Gibberish inference result when using pre-trained model for unknown distribution

### ISSUE THREAD

**Issue by sakhawathsumit** [SeanNaren/deepspeech.pytorch#308]
I was trying to inference using pre-trained librispeech model with some [audio sample](http://dare.wisc.edu/audio) collected from web. But the result is quite depressing, model predicted every single character wrong.

Ground truth: “The Story of Arthur the Rat. Once upon a time there was a rat who couldn’t make up his”

Predicted : “HAM AUUEWIR CCHIUVHE C O HO AA UBBUSH”

Is there any way to solve this?

**Comment by EgorLakomkin** [comment]
Can you check if the audio file has 16kHz sampling rate?

**Comment by ryanleary** [comment]
Yes, check the sample rate. I converted the mp3 and took just the first fifteen seconds using sox:
`sox Arthur.mp3 -c 1 -r 16000 arthur_clip.wav trim 0 15`

and using the pruned librispeech lm (3gram.1e-7) with alpha=1.65, beta=0.35 I got the following output:
> **Hypothesis**: the story of other once upon a time there was a young rat who couldn't make up his mind whenever the other attained would like to come out hunting with them he would answer in the horse`
> 
> **Reference**: The Story of Arthur the Rat. Once upon a time there was a rat who couldn't make up his mind. Whenever the other rats asked him if he would like to come out hunting with them, he would answer in a hoarse

and with no LM:
> **Hypothesis**: the story of othof the rat once upon a time there was a young rat who couldn't make up is mind whenever the other raht sayis tim oof he wuld lage to come o unting with them he would answer in the horse

which is not bad.
