### ISSUE TITLE
loss_results[epoch] = avg_loss

### ISSUE THREAD

**Issue by ggdupont** [SeanNaren/deepspeech.pytorch#316]
I appears the loss_results array cannot be resized.

The context: I started to train a model on 20 epochs. Then I chose to change few tweaks for later epochs. It trains fine until it reaches epoch 21 and I get:

`
File "train.py", line 408, in <module> 
    loss_results[epoch] = avg_loss
IndexError: index 20 is out of bounds for dimension 0 with size 20
`

I'll try to find a workaround... but wanted to mention it in case anyone reach the same issue.

**Comment by SeanNaren** [comment]
this is due to the overwrite of the results arrays when we load a model [here](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/train.py#L151), but we'll need to figure out a nice way to extend this array if necessary...

**Comment by felixkreuk** [comment]
Has anyone come up with an elegant solution for this?
