### ISSUE TITLE
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by StephenZengCn** [SeanNaren/deepspeech.pytorch#32]
this happened when i set cuda=True
```
)
Traceback (most recent call last):
  File "train.py", line 318, in <module>
    main()
  File "train.py", line 182, in main
    out = model(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 71, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/parallel_apply.py", line 45, in parallel_apply
    raise output
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR
```

**Comment by StephenZengCn** [comment]
i follow this (issue)[https://github.com/pytorch/pytorch/issues/544], disable cudnn at at the beginning of the train script and i got this:
```
Traceback (most recent call last):
  File "train.py", line 320, in <module>
    main()
  File "train.py", line 184, in main
    out = model(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 71, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/parallel_apply.py", line 45, in parallel_apply
    raise output
RuntimeError: cublas runtime error : library not initialized at /b/wheel/pytorch-src/torch/lib/THC/THCGeneral.c:387
```

**Comment by StephenZengCn** [comment]
and i have multi gpu
i found this
https://discuss.pytorch.org/t/cublas-runtime-error-library-not-initialized-at-data-users-soumith-builder-wheel-pytorch-src-torch-lib-thc-thcgeneral-c-383/1375/2
it dos not help

**Comment by SeanNaren** [comment]
This issue looks to be involved with your installation of pytorch not this library, it may be best to open an issue there. Also what OS are you using?

**Comment by StephenZengCn** [comment]
ubuntu.

**Comment by SeanNaren** [comment]
Let me know if you've managed to fix this, I'd suggest updating drivers, making sure CUDA is installed correctly (and you can see your GPUs using `nvidia-smi` removing pytorch and installing from source

**Comment by StephenZengCn** [comment]
thanks for you help!
ubuntu16.04, cuda-8.0, install pytorch from source, success training with gpu if i set torch.backends.cudnn.enabled = False
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

**Comment by SeanNaren** [comment]
Awesome nearly there, try downloading `cudnn` manually from here: https://developer.nvidia.com/cudnn (the latest version you can) then putting them in the correct folders at `/usr/local/cuda/` (in the respective `lib64` or `include` folder) then try reinstalling from source.

**Comment by StephenZengCn** [comment]
Thanks!
Training with cudnn is about 10x faster.

**Comment by 4F2E4A2E** [comment]
> @StephenZengCn torch.backends.cudnn.enabled = False
Why do it have to be deactivated in order to work? Would it not mean that GPU / cudnn is deactivated?

**Comment by SeanNaren** [comment]
@4F2E4A2E I think it worked for him before, but I'd highly suggest not doing that for the reasons you specified. Are you running into issues?

**Comment by 4F2E4A2E** [comment]
@SeanNaren thank you. Yeah, i am trainig to run [1] training (default datasets). I wonder if it is a CUDA problem, do you know - besides nvcc --version ) how to verify the cudnn version installed?

**Comment by softhuafei** [comment]
Just `sudo rm -rf ~/.nv` and reboot, everything will be ok!

**Comment by lonelylingoes** [comment]
@softhuafei  It works without reboot.

**Comment by DoubleYing** [comment]
> 只需`sudo rm -rf ~/.nv`重启，一切都会好的！

请问一下，这行命令是将nvidia驱动删了吗?不会出现别的问题吗

**Comment by zhixuanli** [comment]
`sudo rm -rf ~/.nv` and reboot is not helpful for me, still having this problem.

My environment:
+ CUDA: 10.0.130
+ cudnn : 7602
+ pytorch: 1.2.0, installed via pip
+ torchvision: 0.4.0 
+ python: 3.6.6
+ ubuntu 16.04
+ RTX 2080ti

**Comment by soufien1996** [comment]
> `sudo rm -rf ~/.nv` and reboot is not helpful for me, still having this problem.
> 
> My environment:
> 
>     * CUDA: 10.0.130
> 
>     * cudnn : 7602
> 
>     * pytorch: 1.2.0, installed via pip
> 
>     * torchvision: 0.4.0
> 
>     * python: 3.6.6
> 
>     * ubuntu 16.04
> 
>     * RTX 2080ti

Anything yet?
