### ISSUE TITLE
Multi-GPU support via DDP for specific GPU Range

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/deepspeech.pytorch#322]
Currently the `multiproc.py` script assumes all available GPUs on the machine are available. Modify this script to support only specific set of IDs.

**Comment by miguelvr** [comment]
thanks man! I'll soon run some experiments on my side, looking for possible solutions as well

**Comment by SeanNaren** [comment]
@miguelvr was bored so whipped this up quickly, have a look at [this](https://github.com/SeanNaren/deepspeech.pytorch/tree/multiproc) branch!

I've also updated the docs with instructions on how to use it, but here is an example:

```
python -m multiproc train.py --cuda --train-manifest data/an4_train_manifest.csv  --val-manifest data/an4_val_manifest.csv  --device-ids 0,1,2,3 --batch-size 8
```

**Comment by miguelvr** [comment]
That was very similar to what I was thinking about! Super cool :+1:

**Comment by SeanNaren** [comment]
Awesome, seems to work for me so will open a PR
