### ISSUE TITLE
How to understand to score returned by the beam decoder?

### ISSUE THREAD

**Issue by weedwind** [SeanNaren/deepspeech.pytorch#327]
Hi, 

During decoding, I used the beam decoder, and I used top-5 best paths. When I look at the output scores returned by the decoder, I found 2 things that I don't understand:

1. The scores are in ascending order, starting from the smallest one. Since it's the "top" N best, why is the first score the smallest?
2. Some scores (the largest ones) are greater than 1. I am wondering since they are log probabilities, should they be less than 0?

So, how should I interpret the scores?

Thank you so much for any help

**Comment by adryyandc** [comment]
Take a look at this post:

https://github.com/kpu/kenlm/issues/150

**Comment by weedwind** [comment]
@adryyandc 

Hi, 

Thank you very much for help. I still don't understand my 2 questions above.


1. Since it's "top-N" paths, why is the first score the smallest?
2. Why are some scores greater than one since they are log probabilities?


I understand the kenlm score in the post you linked, but that score may not be the same score as the CTC decoder output.


Thank you very much

**Comment by Sakurawy** [comment]
@weedwind Hi, I find the same problem. Have you figure it out? Thank you!

**Comment by OmarHory** [comment]
[2.zip](https://github.com/SeanNaren/deepspeech.pytorch/files/5443316/2.zip)
![image](https://user-images.githubusercontent.com/43903002/97264536-3451aa80-1836-11eb-9975-0644b24f55aa.png)

Can someone explain those scores? 
Beamwidth = 30
