### ISSUE TITLE
computer  shut down when train Mandrion model

### ISSUE THREAD

**Issue by minushuang** [SeanNaren/deepspeech.pytorch#330]
the computer will be  shut down with the training of  Mandarin model. but the English model works well.
the  differences between  them are as below.
1. the `labels.json` for Mandarin is `["_", "语", "音", "识", "别",...,"百", "度", "  "]`with blank and space. `len(labels)=2665`
2. adding `labels = labels.decode('utf-8')` in `train.py` to decode the Chinese character  label to unicode.
3. adding `transcript = transcript.decode('utf-8')` in `data_loader.py` to decode the Chinese character to unicode.

why shut down?

**Comment by minushuang** [comment]
shut down after several epochs .(within ten epochs )

**Comment by minushuang** [comment]
I train the model without a space '  ' in `labels.json` at begin, and it can work normally except at the validation time when run the `decode.py` ,the code needs a space smybol '  ' in the `labels.json`.

so I add '  ' in the labels.json, and the computer shut down when training after several epochs(within 10 epochs)

**Comment by minushuang** [comment]
It is the `batch-size` too large to train a Mandarin model for my nvidia 1080 gpu.
default is 20, and 10 is OK to me.
but there is not a message of `out of memory` , shut down directly.
confused.

**Comment by hoyden** [comment]
I‘ve met this ，just run out of memory

**Comment by hoyden** [comment]
I am also training this model on Mandarin corpus recently.Could you tell me which corpus you are using?And i trained this model for several days, but the CER is still up to 16%.Could you tell me your result?Thx

**Comment by minushuang** [comment]
I used the THCHS30 datasets,about 30 hrs Mandarin corpus.
and the result was not good because the dataset is too small to train the deep model.
which corpus you are using...

**Comment by hoyden** [comment]
I'm also using some open source datasets--AISHELL,ST-CMDS,and THCHS30, but my experiment result was so bad...

**Comment by minushuang** [comment]
I applied for the AISHELL datasets several days ago, but haven't got a reply until now.

**Comment by sai10** [comment]
@minushuang  code you share the labels.json file of mandarin data?

**Comment by HandsLing** [comment]
@minushuang what is your wrong message? i met OOM error when validation, i found that it ays wrong message in this line: output_data.append((out.cpu(), output_sizes, target_strings)) in test.py,  i noticed that save_out is False but this judgment condition was if save_output is not None, None is not equal to False, and you output was very huge(cause len(labels)>2000), i changed save_output to None deal with it
