### ISSUE TITLE
ZeroDivisionError When moving to next epoch - during validation

### ISSUE THREAD

**Issue by 3210jr** [SeanNaren/deepspeech.pytorch#332]
Hi all,
I keep getting a ZeroDivisionError when moving from one epoch to another, i see that the error is in line  322, just not sure how to solve it.

This is the error I get:
```
Training Summary Epoch: [1]	Time taken (s): 310	Average Loss 13.810	
  0%|                                                                                                                       | 0/78 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    wer += decoder.wer(transcript, reference) / float(len(reference.split()))
ZeroDivisionError: float division by zero
```

Thanks!

**Comment by miguelvr** [comment]
Your reference is probably empty

**Comment by linerocks** [comment]
I also found this problem. After finding out, the reference text needs to be in uppercase.

**Comment by miguelvr** [comment]
Doesn't need to be upper case, it only needs to be consistent with the labels.json file
