### ISSUE TITLE
Beam decoder only supports single letter labels?

### ISSUE THREAD

**Issue by weedwind** [SeanNaren/deepspeech.pytorch#335]
Hi, 

I am using CTC to do phoneme recognition. My labels are phones, such as ["AX", "OW"] etc. I tried to use the basic beam decoder (without lm) to do decoding. But the decoder reports that the label size did not equal the probability tensor size. If I change to label to single letters, like ["A", "B"], it was fine. So I am wondering how to deal with multiple letter labels?

Thank you very much

**Comment by SilvrDuck** [comment]
This is apparently because of the implementation of the underlying ctcdecode library. It doesn’t look like it will be supported for now.

See here https://github.com/parlance/ctcdecode/issues/31
