### ISSUE TITLE
Which file or setting should I change if I want to apply another language?

### ISSUE THREAD

**Issue by dolpang2** [SeanNaren/deepspeech.pytorch#337]
Hi team,
I'd like to apply deepseepch.pytorch to Korean recognition.
I read some issues in this repository, but not sure which file or setting should I change.
Is it enough to change labels.json corresponding to Korean?

**Comment by miguelvr** [comment]
in theory, changing labels.json would be enough

**Comment by dolpang2** [comment]
@miguelvr Thx! I'll try
