### ISSUE TITLE
Not able to get warp CTC building help wanted

### ISSUE THREAD

**Issue by sivagururaman** [SeanNaren/deepspeech.pytorch#349]
I am trying to get the warp CTC to build as given in the readme. 
Error:
unsupported GNU version! gcc versions later than 6 are not supported

I tried with the gcc version of 4.x as well. Same error is shown. Can you please help?

Thanks!

**Comment by buriy** [comment]
Use gcc-5 , it doesn't compile with gcc-4, gcc-6 and gcc-7 .

**Comment by ashupednekar** [comment]
Are you using Ubuntu 18? It comes with gcc 7 as the default compiler... You'll have to uninstall it manually with 
sudo apt-get --purge remove gcc
And then manually install gcc 4.9 or 5.4.

If it's a server, I'd recommend switching to 16.04
