### ISSUE TITLE
Noise injection

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/deepspeech.pytorch#35]
Add noise injection capabilities that were dumped [here](https://github.com/willfrey/audio) into our dataloader.

**Comment by EgorLakomkin** [comment]
I have tried to add very basic data augmentation described in deep speech paper here #48. @SeanNaren what do you think? It is not that pretty, but does the job. Sox is quite fast and changes the tempo without adding "funny voice" effect, which librosa or pydub introduces, for instance, with it's change_speech function.

**Comment by SeanNaren** [comment]
This is super useful for sure! Will get that merged in. The next step is once we've sorted out the dataloader to get dynamic mixing of noise into the audio as in my colleagues repo linked above!

**Comment by ryanleary** [comment]
Can be closed based on #48.

**Comment by EgorLakomkin** [comment]
I think there is still need to add random noise overlapping and probably pitch shift.

**Comment by SeanNaren** [comment]
Added in #53
