### ISSUE TITLE
No speedup with multi-GPU setup

### ISSUE THREAD

**Issue by buriy** [SeanNaren/deepspeech.pytorch#359]
I managed to set up the repo with Multi-GPU training, had to compile for PyTorch 0.4.1 and torchaudio 0.1 and to use this fix: https://github.com/SeanNaren/deepspeech.pytorch/issues/325
However, I didn't get any speed up: with two GPUs compared to one GPU, the number of batches per epoch is 2x smaller, but each batch processing now takes two times longer (1.6 sec, was 0.8 sec).
This is my command line:
`CUDA_VISIBLE_DEVICES=0,1 python multiproc.py train.py --cuda --batch-size 12 --train-manifest data/ted_train_manifest.csv --val-manifest data/ted_val_manifest.csv --device-ids 0,1 --visdom --id ted_multigpu --save-folder saves/ted/ --model-path saves/ted/best.model --no-sortaGrad`

Also this warning suggests that something might not be working well:
`/Projects/ds2/model.py:98: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().`

**Comment by mvankeirsbilck** [comment]
I'm having the same issue (Pytorch 1.0, using gloo dist-backend)

> with two GPUs compared to one GPU, the number of batches per epoch is 2x smaller, but each batch processing now takes two times longer (1.6 sec, was 0.8 sec).

**Comment by snakers4** [comment]
Trying to run a CNN model (wav2letter) just using DP on 2 GPUs
Will report whether there is a speed-up
