### ISSUE TITLE
Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by edwardyoon** [SeanNaren/deepspeech.pytorch#362]
I've downloaded pre-trained model and deep speech.pytorch-1.1. When I try to transcribe audio, it throws RuntimeError: Calculated padded input size per channel: (61 x 6). Kernel size: (21 x 11). Kernel size can't be greater than actual input size. Any advice? 

I'm using CUDA-10.0, installations were all finished successfully. 

```
edward@GPU-machine:~/deepspeech.pytorch-1.1$ python transcribe.py --model_path models/librispeech_pretrained.pth --audio_path fox_question.wav 
Traceback (most recent call last):
  File "transcribe.py", line 88, in <module>
    out = model(Variable(spect, volatile=True))
  File "/home/edward/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/edward/deepspeech.pytorch-1.1/model.py", line 172, in forward
    x = self.conv(x)
  File "/home/edward/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/edward/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/edward/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/edward/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (61 x 6). Kernel size: (21 x 11). Kernel size can't be greater than actual input size at /pytorch/aten/src/THNN/generic/SpatialConvolutionMM.c:48
```

'''

**Comment by edwardyoon** [comment]
I used this sample http://www.voiptroubleshooter.com/open_speech/american.html?fbclid=IwAR38V9crNqoPL2x0Nt-KpQysWGJMPRB3m-QxNU-NpvUYEekyoHdxqMR5iOA

**Comment by edwardyoon** [comment]
solved. I've installed PyTorch 1.1 and CUDA 10.0, there were few changes.

**Comment by boyuangong** [comment]
Hi, I met the same problem using torch 0.4. But when change to torch 1.1. There's another problem same as  #373 . Do you meet this problem? I met this problem in the test phase. Thanks.

**Comment by maggieezzat** [comment]
> solved. I've installed PyTorch 1.1 and CUDA 10.0, there were few changes.

Hello @edwardyoon , I have the same problem,  PyTorch 1.1 and CUDA 10.0, What are the few changes you made ?

**Comment by Michacal** [comment]
Hello @maggieezzat , I have the same issue, have you found any solution?

**Comment by turlvo** [comment]
@Michacal I guess you already have got a answer.
There is a answer in #373 

You should add padding to the second convolution layer.
In model.py change line 137 to:
```
nn.Conv2d(32, 32, kernel_size=(21, 11), stride=(2, 1), padding=(0, 5))
```

**Comment by vpapaioannou** [comment]
Although in the documentation https://pytorch.org/docs/stable/nn.html is said that "It is up to the user to add the proper padding", it is quite tedious to calculate for each layer the proper padding. The problem actually comes from corresponding https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L345 in PyTorch 1.4.0 at least. However, in https://github.com/pytorch/pytorch/blob/0475d7b08d7cba11fc0b3ea7ccbf0046fa0b1cf7/torch/nn/functional.py there is function ``pad`` that can be used to solve the problem the way its handled in PyTorch 1.5, https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L342 that uses ``_pad`` in https://github.com/pytorch/pytorch/blob/0475d7b08d7cba11fc0b3ea7ccbf0046fa0b1cf7/torch/nn/functional.py#L3365. In PyTorch 1.4.0 this function if called ``pad`` at line 2802 of the corresponding ``functional.py`` file.

I hope that helps.
