### ISSUE TITLE
Do you have space to upload your learned models?

### ISSUE THREAD

**Issue by jybaek** [SeanNaren/deepspeech.pytorch#368]
In 413e17626f835cad9082a6e029461fb202886561 version( Based on the current master ), I finished the train with 32 batches, 70epochs, and got the following results.

```
$ python model.py  --model-path models/librispeech_pretrained_batch32_epochs70.pth
Model name:          librispeech_pretrained_batch32_epochs70.pth
DeepSpeech version:  0.0.1

Recurrent Neural Network Properties
  RNN Type:          gru
  RNN Layers:        5
  RNN Size:          800
  Classes:           29

Model Features
  Labels:            _'ABCDEFGHIJKLMNOPQRSTUVWXYZ
  Sample Rate:       16000
  Window Type:       hamming
  Window Size:       0.02
  Window Stride:     0.01

Training Information
  Epochs:            41
  Current Loss:      8.780
  Current CER:       7.571
  Current WER:       22.117
```
Do you have a separate path to collect model files? 
I would like to upload it if there is one. thanks.

**Comment by buriy** [comment]
You can upload binary files to github via "Releases", files should be up to 1 GB in size (Create a new release, then upload the file(s) ). You can upload it into your fork, and then provide a link to it for the repository author.
By the way, what version of LibriSpeech is this?

**Comment by jybaek** [comment]
@buriy I used [a version embedded in the source](http://www.openslr.org/resources/12/). Thank you.

**Comment by sai10** [comment]
Hello @jybaek  have trained on any chinese or mandarin dataset?

**Comment by jybaek** [comment]
@sai10 Nope, I am only training English and Korean.

**Comment by SeanNaren** [comment]
hey thanks for this! If you could upload the file somewhere i'll be more than happy to make a release, however preferrably i'd have pre-trained models for the rest of the datasets as well...

**Comment by buriy** [comment]
@SeanNaren @jybaek Have you considered merging all datasets together and training with a combined dataset?
(Also there's TEDLIUM v3 around, almost 2x larger than TEDLIUM v2)

**Comment by SeanNaren** [comment]
@buriy really good suggestions all around but GPU resources and internal work makes it difficult for me to facilitate this... I'll be more than happy to coordinate with someone willing to train this however!

I do want to make a few changes across the weekend, primarily adding mixed-precision support and sorting out some small bugs here and there!

**Comment by jybaek** [comment]
@SeanNaren I did not have time to learn other models 😅 . Sorry. I uploaded the model to the following path: 

https://github.com/jybaek/deepspeech2-korean/releases/tag/v1.3

**Comment by altavatarindia** [comment]
Just for info: I trained the model on 4 included datasets (except an4, which I somehow missed using), and uploaded the model too. Please see here: https://github.com/altavatarindia/deepspeech-releases/releases/tag/1-0-0-stable
