### ISSUE TITLE
Language model usage.

### ISSUE THREAD

**Issue by ronybanerjee93** [SeanNaren/deepspeech.pytorch#371]
I would like to know how can I use the kenLM language model in the code. Do I have to pass it in the --lm-path argument in the opts.py file? If yes then which particular file shall I refer to? I dont see any binary file in the kenLM directory. So specifically asking inside third_party/kenlm/lm/ which file do I need to pass as argument to train my network with beam search decoder with kenlm language model? As I couldn't find any relevant question in the issues, I had to open a new one. Thanks.

**Comment by ryanleary** [comment]
You'll have to build your own language model or use one that someone else has created. Training that model is out of scope for this project.

**Comment by ronybanerjee93** [comment]
git clone --recursive https://github.com/parlance/ctcdecode.git
cd ctcdecode && pip install . After running this some files related to kenLM have been loaded to the system. What are those files for? Do I need to build a binary file from there? And how to pass the language model trie to the beamsearch decoder?
