### ISSUE TITLE
Dockerfile run error 

### ISSUE THREAD

**Issue by Arif45** [SeanNaren/deepspeech.pytorch#372]
import wget
    ModuleNotFoundError: No module named 'wget'
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-z3cy8anb/
The command '/bin/sh -c cd ctcdecode; pip install .' returned a non-zero code: 1

**Comment by SeanNaren** [comment]
try building from master, I've added a missing dependency for ctcdecode to the dockerfile!
