### ISSUE TITLE
Torch: invalid memory size - maybe an overflow? 

### ISSUE THREAD

**Issue by slbinilkumar** [SeanNaren/deepspeech.pytorch#373]
RuntimeError: $ Torch: invalid memory size - maybe an overflow? at /opt/conda/conda-bld/pytorch_154417496763                                                                                         3/work/aten/src/TH/THGeneral.cpp:188

**Comment by mertyildiran** [comment]
I faced with this issue too.

**Comment by boyuangong** [comment]
The reason lead to this error is actually the kernel size is larger than the input size. I tried different pretrained models but still got the same error.

**Comment by mertyildiran** [comment]
@boyuangong I tried all of the pretrained models published under [v1.1 release](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/v1.1). Tried both v1.1 and v1.2 heads. Getting the exact same error.

It might fixed in the pytorch repo but not released yet: https://github.com/pytorch/pytorch/issues/16035#issuecomment-454547816

**Comment by yohanjk** [comment]
I'm also facing the same issue, isn't there any fix yet? @boyuangong

**Comment by boyuangong** [comment]
You need to tune the nn.sequential parameters. Check https://github.com/jhfjhfj1/autokeras/blob/master/autokeras/pretrained/voice_recognizer.py#L171-L178 for example.

**Comment by gkv91** [comment]
Same error here. Any fix?

**Comment by guyco87** [comment]
@boyuangong the link you provided is broken, could you fix it? What do you mean by tuning the nn.sequential parameters?

**Comment by gioannideImp** [comment]
has anyone figured out a solution to this issue?

**Comment by snard6** [comment]
I was getting the same issue. After upgrading to the latest pytorch I now get a friendlier error message:
```
RuntimeError: Calculated padded input size per channel: (61 x 6). Kernel size: (21 x 11). Kernel size can't be greater than actual input size
```

But it still isn't clear to me how to fix it.

**Comment by guyco87** [comment]
You should add padding to the second convolution layer.
In model.py change line 137 to:

`nn.Conv2d(32, 32, kernel_size=(21, 11), stride=(2, 1), padding=(0, 5))`

As it says in your error message, the input to that layer is (61 x 6) but your kernel size is (21 x 11) so padding on the second dimension is required here.

**Comment by snard6** [comment]
It appears the newest code has fixes to the spectrogram creation. While the older code has the actual model (for the released weights).

New code gives this error:
```RuntimeError: Error(s) in loading state_dict for DeepSpeech:
Missing key(s) in state_dict: "conv.seq_module.0.bias", "conv.seq_module.0.weight", "conv.seq_module.1.bias", "conv.seq_module.1.running_var", "conv.seq_module.1.weight", "conv.seq_module.1.running_mean", "conv.seq_module.3.bias", "conv.seq_module.3.weight", "conv.seq_module.4.bias", "conv.seq_module.4.running_var", "conv.seq_module.4.weight", "conv.seq_module.4.running_mean", "rnns.0.rnn.bias_hh_l0", "rnns.0.rnn.bias_ih_l0", "rnns.0.rnn.bias_ih_l0_reverse", "rnns.0.rnn.bias_hh_l0_reverse", "rnns.1.rnn.bias_hh_l0", "rnns.1.rnn.bias_ih_l0", "rnns.1.rnn.bias_ih_l0_reverse", "rnns.1.rnn.bias_hh_l0_reverse", "rnns.2.rnn.bias_hh_l0", "rnns.2.rnn.bias_ih_l0", "rnns.2.rnn.bias_ih_l0_reverse", "rnns.2.rnn.bias_hh_l0_reverse", "rnns.3.rnn.bias_hh_l0", "rnns.3.rnn.bias_ih_l0", "rnns.3.rnn.bias_ih_l0_reverse", "rnns.3.rnn.bias_hh_l0_reverse", "rnns.4.rnn.bias_hh_l0", "rnns.4.rnn.bias_ih_l0", "rnns.4.rnn.bias_ih_l0_reverse", "rnns.4.rnn.bias_hh_l0_reverse". 
Unexpected key(s) in state_dict: "conv.0.weight", "conv.0.bias", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.3.weight", "conv.3.bias", "conv.4.weight", "conv.4.bias", "conv.4.running_mean", "conv.4.running_var". 
size mismatch for rnns.0.rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
size mismatch for rnns.0.rnn.weight_ih_l0: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
```

Old code gives this error:
```
RuntimeError: Calculated padded input size per channel: (61 x 6). Kernel size: (21 x 11). Kernel size can't be greater than actual input size
```

I was able to work around this by checking out the newest code:
`git checkout master`

And then replacing the model definition with the older code:
`git checkout tags/v1.2 -- model.py`

This seems to work for me. The real solution is probably to release new weights for the new model architecture.

**Comment by rusiaaman** [comment]
> It appears the newest code has fixes to the spectrogram creation. While the older code has the actual model (for the released weights).
> 
> New code gives this error:
> 
> ```
> Missing key(s) in state_dict: "conv.seq_module.0.bias", "conv.seq_module.0.weight", "conv.seq_module.1.bias", "conv.seq_module.1.running_var", "conv.seq_module.1.weight", "conv.seq_module.1.running_mean", "conv.seq_module.3.bias", "conv.seq_module.3.weight", "conv.seq_module.4.bias", "conv.seq_module.4.running_var", "conv.seq_module.4.weight", "conv.seq_module.4.running_mean", "rnns.0.rnn.bias_hh_l0", "rnns.0.rnn.bias_ih_l0", "rnns.0.rnn.bias_ih_l0_reverse", "rnns.0.rnn.bias_hh_l0_reverse", "rnns.1.rnn.bias_hh_l0", "rnns.1.rnn.bias_ih_l0", "rnns.1.rnn.bias_ih_l0_reverse", "rnns.1.rnn.bias_hh_l0_reverse", "rnns.2.rnn.bias_hh_l0", "rnns.2.rnn.bias_ih_l0", "rnns.2.rnn.bias_ih_l0_reverse", "rnns.2.rnn.bias_hh_l0_reverse", "rnns.3.rnn.bias_hh_l0", "rnns.3.rnn.bias_ih_l0", "rnns.3.rnn.bias_ih_l0_reverse", "rnns.3.rnn.bias_hh_l0_reverse", "rnns.4.rnn.bias_hh_l0", "rnns.4.rnn.bias_ih_l0", "rnns.4.rnn.bias_ih_l0_reverse", "rnns.4.rnn.bias_hh_l0_reverse". 
> Unexpected key(s) in state_dict: "conv.0.weight", "conv.0.bias", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.3.weight", "conv.3.bias", "conv.4.weight", "conv.4.bias", "conv.4.running_mean", "conv.4.running_var". 
> size mismatch for rnns.0.rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
> size mismatch for rnns.0.rnn.weight_ih_l0: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
> ```
> 
> Old code gives this error:
> 
> ```
> RuntimeError: Calculated padded input size per channel: (61 x 6). Kernel size: (21 x 11). Kernel size can't be greater than actual input size
> ```
> 
> I was able to work around this by checking out the newest code:
> `git checkout master`
> 
> And then replacing the model definition with the older code:
> `git checkout tags/v1.2 -- model.py`
> 
> This seems to work for me. The real solution is probably to release new weights for the new model architecture.

This solution doesn't work for master anymore, I used 83c37dd for it to work.

**Comment by dendisuhubdy** [comment]
Any information on this issue?
