### ISSUE TITLE
Explanation MaskConv 

### ISSUE THREAD

**Issue by phtephanx** [SeanNaren/deepspeech.pytorch#374]
I was reading through the code for MaskConv:
https://github.com/SeanNaren/deepspeech.pytorch/blob/0bb3fcd2a72f4701627b623bf5718f2f0ff73425/model.py#L66

Could someone elaborate on why the _feature dimension_ "D" (index 2) is masked using the original (unpadded), but convoluted sequence lengths, which originate from dimension "T" (index 3)?

**Comment by ethanywang** [comment]
I think it should be index 3...

**Comment by Sakurawy** [comment]
The masked dimension is "T", the time length dimension. mask[i] has the shape of "CxDxT".
