### ISSUE TITLE
Error while testing over pretrained model

### ISSUE THREAD

**Issue by piyush101** [SeanNaren/deepspeech.pytorch#378]
I am using pytorch v1.0, python 3.6 and using the same commit as the release of the librispeech pretrained model.
When I try to run on librispeech pretrained model as-
`python3 test.py --model-path librispeech.pth --test-manifest an4_val_manifest.csv`

I get this error-
`RuntimeError: Error(s) in loading state_dict for DeepSpeech:
	Missing key(s) in state_dict: "conv.seq_module.0.weight", "conv.seq_module.0.bias", "conv.seq_module.1.weight", "conv.seq_module.1.bias", "conv.seq_module.1.running_mean", "conv.seq_module.1.running_var", "conv.seq_module.3.weight", "conv.seq_module.3.bias", "conv.seq_module.4.weight", "conv.seq_module.4.bias", "conv.seq_module.4.running_mean", "conv.seq_module.4.running_var", "rnns.0.rnn.bias_ih_l0", "rnns.0.rnn.bias_hh_l0", "rnns.0.rnn.bias_ih_l0_reverse", "rnns.0.rnn.bias_hh_l0_reverse", "rnns.1.rnn.bias_ih_l0", "rnns.1.rnn.bias_hh_l0", "rnns.1.rnn.bias_ih_l0_reverse", "rnns.1.rnn.bias_hh_l0_reverse"
	Unexpected key(s) in state_dict: "conv.0.weight", "conv.0.bias", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.3.weight", "conv.3.bias", "conv.4.weight", "conv.4.bias", "conv.4.running_mean", "conv.4.running_var". 
	size mismatch for rnns.0.rnn.weight_ih_l0: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
	size mismatch for rnns.0.rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).`

Can anyone please help, How to fix this error?

**Comment by mertyildiran** [comment]
@piyush101 I'm getting the same error. This is the first time I try this library.

**Comment by boyuangong** [comment]
You should checkout the corresponding commitment hash.

**Comment by piyush101** [comment]
> You should checkout the corresponding commitment hash.

@boyuangong  I am using the same commit hash as the release for the libripeech model i.e. e2c2d83235

**Comment by piyush101** [comment]
@SeanNaren @ryanleary How can I overcome this issue?

**Comment by lyc1993** [comment]
hi, have you fix this issue?

**Comment by piyush101** [comment]
@lyc1993 No. Do you experiencing the same?

**Comment by jybaek** [comment]
@SeanNaren Looks like the _hash(e2c2d832357a992f36e68b5f378c117dd270d6ff)_ in the `pretrained model` is wrong. People with errors should use at least the following version of the hash to try out the pre-trained model. The parameter is changed in conv_layer.

https://github.com/SeanNaren/deepspeech.pytorch/commit/80a060f44c23d34ebabd3bac94c70a8f19d56955

**Comment by lucgeo** [comment]
Hi,

Using the 80a060f I got two other different errors:

 size mismatch for rnns.0.rnn.weight_ih_l0: copying a param of torch.Size([2400, 1312]) from checkpoint, where the shape is torch.Size([2400, 672]) in current model.
        size mismatch for rnns.0.rnn.weight_ih_l0_reverse: copying a param of torch.Size([2400, 1312]) from checkpoint, where the shape is torch.Size([2400, 672]) in current model.

Lucian

**Comment by Kabur** [comment]
@piyush101  @mertyildiran @lucgeo 

Have you guys managed to overcome this issue?

@jybaek 
Getting the same error on this hash, as well as the master. Same case as for lucgeo it seems like. Any recommendations by any chance?
