### ISSUE TITLE
Server curl command error 

### ISSUE THREAD

**Issue by Arif45** [SeanNaren/deepspeech.pytorch#380]
After running the command: curl -X POST http://10.100.222.168:8880/transcribe -H "Content-type: multipart/form-data" -F "file=@/home/arif45/warp-ctc/pytorch_binding/audio/ctcdecode/deepspeech.pytorch/mehadi-1.wav"
the error message shows like:
 ...
Traceback (most recent call last):
"/home/arif45/warp-ctc/pytorch_binding/audio/ctcdecode/deepspeech.pytorch/server.py", line 37, in transcribe_file
    transcription, _ = transcribe(tmp_saved_audio_file.name, spect_parser, model, decoder, args.cuda)
  File "/home/arif45/warp-ctc/pytorch_binding/audio/ctcdecode/deepspeech.pytorch/transcribe.py", line 61, in transcribe
    spect.to(device)

**_TypeError: to() received an invalid combination of arguments - got (bool), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy)
 * (torch.dtype dtype, bool non_blocking, bool copy)
 * (Tensor tensor, bool non_blocking, bool copy)_**

-->

**Comment by SeanNaren** [comment]
can you retry master
