### ISSUE TITLE
ctcdecode import error

### ISSUE THREAD

**Issue by ronybanerjee93** [SeanNaren/deepspeech.pytorch#381]
I followed the dockerfile commands below,
git clone --recursive https://github.com/parlance/ctcdecode.git
cd ctcdecode; pip install .
which successfully installed ctcdecode 0.4
Building wheels for collected packages: ctcdecode
  **Running setup.py bdist_wheel for ctcdecode ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-b4vajaga/wheels/c6/02/f7/eab34b3c6e31c7ea539b569f19a985a2debf1c286b89414fbf
Successfully built ctcdecode
Installing collected packages: ctcdecode
Successfully installed ctcdecode-0.4**

After that I opened ipython and tried to import ctcdecode
which throws me the following error...
/home/myname/.conda/envs/dsproject/lib/python3.5/site-packages/ctcdecode/_ext/ctc_decode.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

I have tried uninstallinga and installing this again but nothing happened. 
I am using ubuntu 18.04, cuda 9 and torch 1.0.0.
What is the problem?

**Comment by ronybanerjee93** [comment]
I have solved this problem. So closing the issue. Thank you all.

**Comment by CuriousDeepLearner** [comment]
@ronybanerjee93 hello, could you please tell me how you solved your problem? I encountered the same one. thanks

**Comment by AshwinRJ** [comment]
How did you solve it? Can you please share?

**Comment by psharma94** [comment]
Did anyone figure out how to resolve this issue?

**Comment by manucarbonell** [comment]
In my case I had to go back to torch 1.0.1post2 to resolve it
