### ISSUE TITLE
transcription error

### ISSUE THREAD

**Issue by hajix** [SeanNaren/deepspeech.pytorch#385]
Hi

runing `python3.5 transcribe.py --model-path models/deepspeech_12.pth.tar  --audio-path test_audio/test00002.wav` cause tho following error:

> Traceback (most recent call last):
  File "transcribe.py", line 81, in <module>
    print(json.dumps(decode_results(model, decoded_output, decoded_offsets)))
  File "transcribe.py", line 37, in decode_results
    results['_meta']['acoustic_model'].update(DeepSpeech.get_meta(model))
AttributeError: type object 'DeepSpeech' has no attribute 'get_meta'

it seems `get_mata` is not a method of `DeepSpeech` class.

**Comment by jybaek** [comment]
It seems that model is abnormal or there is a different part from the current code. But my guess is that the model is `tar`. Unzip the `tar` and try.

**Comment by Jogool** [comment]
Besides the tar, line 37 in transcribe.py calls static methods that were removed in the last commit. Comment that out and it will run.
