### ISSUE TITLE
Need of Multiproc.

### ISSUE THREAD

**Issue by ronybanerjee93** [SeanNaren/deepspeech.pytorch#386]
HI,
I am new to pytorch and I have a doubt .Multiproc.py file is taking the argument of number of GPU's and running different training instances for different gpu-id's, ( correct me please if I am wrong). I just cannot understand which point in train.py does the linking of multiproc.py with the training process. Its tough to imagine whats going on. Which particular function is linking the multiproc to train.py in train.py. I hope I can explain my doubt. Please clear it anybody.

**Comment by ronybanerjee93** [comment]
Any help will be appreciated. Please

**Comment by buriy** [comment]
multiproc.py just starts several subprocesses, adding few additional arguments:
For example,
.venv/bin/python multiproc.py train.py asd
will run:
['train.py', 'asd', '--world-size', '2', '--rank', '0', '--gpu-rank', '0']
['train.py', 'asd', '--world-size', '2', '--rank', '1', '--gpu-rank', '1']

You need to read docs on pytorch's torch.nn.parallel.DistributedDataParallel to understand how it works.
