### ISSUE TITLE
Training on multi GPU stops after 1 epoch

### ISSUE THREAD

**Issue by SujathaSIyer** [SeanNaren/deepspeech.pytorch#387]
I tried training on Libri Speech 100 hour clean data on 2 GeForce 1080Ti GPUs using the same hyperparameters provided in the code. Training runs for 1 epoch and then I get the following error. 

> Validation Summary Epoch: [1]	Average WER 86.168	Average CER 33.194	
Traceback (most recent call last):
  File "train.py", line 363, in <module>
    wer_results=wer_results, cer_results=cer_results),
  File "/home/Sujatha/DeepspeechPytorch/deepspeech.pytorch/model.py", line 262, in serialize
    'version': model.version,
  File "/home/Sujatha/DeepspeechPytorch/dsp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'version'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/Sujatha/DeepspeechPytorch/deepspeech.pytorch/multiproc.py", line 46, in <module>
    cmd=p.args)
subprocess.CalledProcessError: Command '['/home/Sujatha/DeepspeechPytorch/dsp/bin/python3', 'train.py', '--tensorboard', '--log-dir', 'log_dir/', '--checkpoint', '--train-manifest', 'data/libri_train_manifest.csv', '--val-manifest', 'data/libri_val_manifest.csv', '--cuda', '--world-size', '2', '--rank', '0', '--gpu-rank', '0']' returned non-zero exit status 1.
['train.py', '--tensorboard', '--log-dir', 'log_dir/', '--checkpoint', '--train-manifest', 'data/libri_train_manifest.csv', '--val-manifest', 'data/libri_val_manifest.csv', '--cuda', '--world-size', '2', '--rank', '0', '--gpu-rank', '0']
['train.py', '--tensorboard', '--log-dir', 'log_dir/', '--checkpoint', '--train-manifest', 'data/libri_train_manifest.csv', '--val-manifest', 'data/libri_val_manifest.csv', '--cuda', '--world-size', '2', '--rank', '1', '--gpu-rank', '1']

Other details
Pytorch 1.0

I tried running on Pytorch 0.4.1 too. And I ran into the same error. Please let me know if I am missing out on something.

**Comment by cuhkebook** [comment]
Same errors.  Even remove the model.version, the hidden_size is missed.  It like the DistributedDataParallel remove those attribute?

**Comment by SujathaSIyer** [comment]
I was reading up about DistributedDataParallel. I made the following changes to the code.

In the file model.py 

> package = {
            'version': model.version,
            'hidden_size': model.hidden_size,
            'hidden_layers': model.hidden_layers,
            'rnn_type': supported_rnns_inv.get(model.rnn_type, model.rnn_type.__name__.lower()),
            'audio_conf': model.audio_conf,
            'labels': model.labels,
            'state_dict': model.state_dict(),
            'bidirectional': model.bidirectional
        }

I made this change

> package = {
            'version': model.module.version,
            'hidden_size': model.module.hidden_size,
            'hidden_layers': model.module.hidden_layers,
            'rnn_type': supported_rnns_inv.get(model.module.rnn_type, model.module.rnn_type.__name__.lower()),
            'audio_conf': model.module.audio_conf,
            'labels': model.module.labels,
            'state_dict': model.module.state_dict(),
            'bidirectional': model.module.bidirectional
        }

This worked for me

**Comment by BuaaAlban** [comment]
> I was reading up about DistributedDataParallel. I made the following changes to the code.
> 
> In the file model.py
> 
> > package = {
> > 'version': model.version,
> > 'hidden_size': model.hidden_size,
> > 'hidden_layers': model.hidden_layers,
> > 'rnn_type': supported_rnns_inv.get(model.rnn_type, model.rnn_type.**name**.lower()),
> > 'audio_conf': model.audio_conf,
> > 'labels': model.labels,
> > 'state_dict': model.state_dict(),
> > 'bidirectional': model.bidirectional
> > }
> 
> I made this change
> 
> > package = {
> > 'version': model.module.version,
> > 'hidden_size': model.module.hidden_size,
> > 'hidden_layers': model.module.hidden_layers,
> > 'rnn_type': supported_rnns_inv.get(model.module.rnn_type, model.module.rnn_type.**name**.lower()),
> > 'audio_conf': model.module.audio_conf,
> > 'labels': model.module.labels,
> > 'state_dict': model.module.state_dict(),
> > 'bidirectional': model.module.bidirectional
> > }
> 
> This worked for me. @cuhkebook

This also worked for me,  thanks a lot

**Comment by rushiagr** [comment]
Works flawlessly! Note that the bold 'name' appearing in the text is actually `__name__`.
