### ISSUE TITLE
LibriSpeech Training Stuck

### ISSUE THREAD

**Issue by kannadaraj** [SeanNaren/deepspeech.pytorch#393]
Hi @SeanNaren ,

  Thanks a ton for sharing the code. I am trying to do LibriSpeech training. Following same steps as explained. I am training on 4 of V-100 GPUs. The training uses all 100% of memory and gets stuck in the first epoch itself. The batch in which it gets stuck is random. I have seen it getting stuck at different batchon every try. It does nothing; i have waited for almost 2 hours. Please can you help. Thanks.

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:17.0 Off |                    0 |
| N/A   52C    P0    74W / 300W |   3985MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:18.0 Off |                    0 |
| N/A   47C    P0    68W / 300W |   4763MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:19.0 Off |                    0 |
| N/A   44C    P0    70W / 300W |   8177MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by SeanNaren** [comment]
have you checked the logs of all the other GPUs? They should be saved to .log files seen in the current directory of deepspeech.pytorch

**Comment by kannadaraj** [comment]
Thanks a lot for the tip. The error messages was not displayed in the terminal.  The error is 

`Traceback (most recent call last):
  File "train.py", line 252, in <module>
    out, output_sizes = model(inputs, input_sizes)
  File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 459, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/projects/phoneme_recognition/deepspeech.pytorch/model.py", line 215, in forward
    x = rnn(x, output_lengths)
  File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/projects/phoneme_recognition/deepspeech.pytorch/model.py", line 97, in forward
    x, h = self.rnn(x)
  File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 182, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

**Comment by BuaaAlban** [comment]
> Thanks a lot for the tip. The error messages was not displayed in the terminal. The error is
> 
> `Traceback (most recent call last): File "train.py", line 252, in <module> out, output_sizes = model(inputs, input_sizes) File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__ result = self.forward(*input, **kwargs) File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 459, in forward result = self.module(*inputs, **kwargs) File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__ result = self.forward(*input, **kwargs) File "/data1/projects/phoneme_recognition/deepspeech.pytorch/model.py", line 215, in forward x = rnn(x, output_lengths) File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__ result = self.forward(*input, **kwargs) File "/data1/projects/phoneme_recognition/deepspeech.pytorch/model.py", line 97, in forward x, h = self.rnn(x) File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__ result = self.forward(*input, **kwargs) File "/home/ubuntu/anaconda3/envs/pytorch_ds/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 182, in forward self.num_layers, self.dropout, self.training, self.bidirectional) RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

have you solved the problem? I have met the similar problem
