### ISSUE TITLE
Trying to create tensor with negative dimension

### ISSUE THREAD

**Issue by lucgeo** [SeanNaren/deepspeech.pytorch#395]
Hi,

I want to use the Librispeech pretrained models from [here] together with v1.1 or v1.2 releases. In both cases, when I called the test.py script, I got this error:
"RuntimeError: Trying to create tensor with negative dimension -4: [20, 32, 21, -4]".

Using the same pretrained models with the actual toolkit release, I got another error:

RuntimeError: Error(s) in loading state_dict for DeepSpeech:
        Missing key(s) in state_dict: "conv.seq_module.0.weight", "conv.seq_module.0.bias", "conv.seq_module.1.weight", "conv.seq_module.1.bias", "conv.seq_module.1.running_mean", "conv.seq_module.1.running_var", "conv.seq_module.3.weight", "conv.seq_module.3.bias", "conv.seq_module.4.weight", "conv.seq_module.4.bias", "conv.seq_module.4.running_mean", "conv.seq_module.4.running_var", "rnns.0.rnn.bias_ih_l0", "rnns.0.rnn.bias_hh_l0", "rnns.0.rnn.bias_ih_l0_reverse", "rnns.0.rnn.bias_hh_l0_reverse", "rnns.1.rnn.bias_ih_l0", "rnns.1.rnn.bias_hh_l0", "rnns.1.rnn.bias_ih_l0_reverse", "rnns.1.rnn.bias_hh_l0_reverse", "rnns.2.rnn.bias_ih_l0", "rnns.2.rnn.bias_hh_l0", "rnns.2.rnn.bias_ih_l0_reverse", "rnns.2.rnn.bias_hh_l0_reverse", "rnns.3.rnn.bias_ih_l0", "rnns.3.rnn.bias_hh_l0", "rnns.3.rnn.bias_ih_l0_reverse", "rnns.3.rnn.bias_hh_l0_reverse", "rnns.4.rnn.bias_ih_l0", "rnns.4.rnn.bias_hh_l0", "rnns.4.rnn.bias_ih_l0_reverse", "rnns.4.rnn.bias_hh_l0_reverse".
        Unexpected key(s) in state_dict: "conv.0.weight", "conv.0.bias", "conv.1.weight", "conv.1.bias", "conv.1.running_mean", "conv.1.running_var", "conv.3.weight", "conv.3.bias", "conv.4.weight", "conv.4.bias", "conv.4.running_mean", "conv.4.running_var".
        size mismatch for rnns.0.rnn.weight_ih_l0: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).
        size mismatch for rnns.0.rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2400, 672]) from checkpoint, the shape in current model is torch.Size([2400, 1312]).

Any ideas please? Which combination of toolkit - pretrained models does it work now?

Thanks,
Lucian

[here]: https://github.com/SeanNaren/deepspeech.pytorch/releases/download/v1.1/librispeech_pretrained.pth

**Comment by jybaek** [comment]
fyi. https://github.com/SeanNaren/deepspeech.pytorch/issues/378#issuecomment-466895900
