### ISSUE TITLE
Testing results on pre-trained Librispeech model

### ISSUE THREAD

**Issue by shunpoo** [SeanNaren/deepspeech.pytorch#405]
Hello, 

I've downloaded DeepSpeech code of  [version 1.2](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/v1.2) and the pre-trained [librispeech models V2](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/v1.1).

Then I tried to evaluate the pre-trained model on **test_clean** set of Librispeech. ( csv file and wav files are processed by librispeech.py which is under the data/ folder. )
Command : 
`python test.py --test-manifest ./data/libri_test_clean_manifest.csv --model-path ./models/librispeech_pretrained.pth --batch-size 15 --cuda`

But I got results which is different from the value shown on the [table](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/v1.1).
My result : 
**Test Summary  Average WER 35.910 Average CER 13.594**
Tuning batch-size value has less effect to the results.

Result with [language model](http://www.openslr.org/11/) is also evaluated.
Command : 
`python test.py --test-manifest ./data/libri_test_clean_manifest.csv --model-path ./models/librispeech_pretrained.pth --batch-size 15 --cuda --decoder beam --lm-path ./data/LM/3-gram.arpa.gz`
And i got 
**Test Summary 	Average WER 29.915	Average CER 15.689**

I modified few lines of code, but it seems no effects to the results.
1. load_audio function in _data_loader.py_
    `sound = sound.numpy()` to `sound = sound.numpy().T`
2. Delete `volatile=True` attribute in _test.py_ and use `with torch.no_grad()` to wrap lines from 67 to 101.
3. In _decoder.py_, int() is used to change type. 
line 169 : `char = self.int_to_char[int(sequence[i])]`
line 172 : `if remove_repetitions and i != 0 and char == self.int_to_char[int(sequence[i - 1])]:`

Did I miss something ?
Any suggestions would be appreciated. Thanks ! 

some packages version:
`python == 3.6.7`
`torch.__version__ == '1.0.1.post2'`
`librosa.__version__ == '0.6.3'`
`python-levenshtein == 0.12.0`
`numpy.__version__ == '1.16.2'`
`sox --version == SoX v14.4.2`

**Comment by nhh1501** [comment]
I have same problem. Do you fix it?

**Comment by archiki** [comment]
Hi, even I faced the same issue, what fix did you use ?
