### ISSUE TITLE
Results worse than DeepSpeech 1

### ISSUE THREAD

**Issue by Kailegh** [SeanNaren/deepspeech.pytorch#408]
Hi, first of all, thank you all for your amazing work. I have been using Mozilla DeepSpeech for a while, but they base their model int the first DeepSpeech paper, I was planning on implementing my own when I found your repo.  
My question comes here, Mozilla code achieves in the LibriSpeech clean test a WER of ~8%. How is your implementation of DeepSpeech2 achieving a WER of 10? Am I missing something? Or is it just that they have more resources and time to make tests and fine-tune their code?

Thanks a lot!

**Comment by jybaek** [comment]
I think not used language model at the pre-trained model in here repository. I do not think I've ever used data augmentation, etc., because most people probably want to get similar results.

In summary, using data augmentation and using all the data from `librispeech` will yield better results. You have to do it yourself. Computing costs are used.

**Comment by Kailegh** [comment]
OK, so no language model is used in those results?

I will test it and post the results.

**Comment by jybaek** [comment]
@Kailegh Data augmentation is important too. I think not used augmentation in pre-trained model. Because I've got better then results from pre-trained model when used augmentation. ( e.g. `--augment` and `--noise-...` )

**Comment by slbinilkumar** [comment]
current WER is achieved by only greedy decoder.

**Comment by SeanNaren** [comment]
Two points to make here:

- The pre-trained model given with this repo can definitely be improved by re-training on the latest master for a longer duration
- Not sure if the Mozilla DeepSpeech repo uses a language model, but if it does that would explain the improvement over this repos' pre-trained models
