### ISSUE TITLE
Impossible to continue checkpoint with mixed-precission

### ISSUE THREAD

**Issue by Kailegh** [SeanNaren/deepspeech.pytorch#410]
specs:
CUDA 10.1

 I have run a training with the --cuda and the --mixed-precision tags using the following command:
`python train.py --train-manifest ../Engine/spanish_data_8k/train_call_center_augmented.csv --val-manifest ../Engine/spanish_data_8k/call_center_segmented/call_center_test_clean.csv --sample-rate 8000 --batch-size 16 --cuda --tensorboard --visdom --checkpoint --checkpoint-per-batch 500 --silent --mixed-precision`

I have tried to start again a training continuing from that point with this command:
`python train.py --train-manifest ../Engine/spanish_data_8k/train_call_center_augmented.csv --val-manifest ../Engine/spanish_data_8k/call_center_segmented/call_center_test_clean.csv --sample-rate 8000 --batch-size 16 --cuda --tensorboard --visdom --checkpoint --checkpoint-per-batch 500 --silent --mixed-precision --continue-from models/deepspeech_final.pth`

but I get the following error

> Traceback (most recent call last):
>   File "train.py", line 264, in <module>
>     out, output_sizes = model(inputs, input_sizes)
>   File "/home/sbduser/anaconda3/envs/DS2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/sbduser/DeepSpeech/deepspeech2_pytorch/model.py", line 208, in forward
>     x, _ = self.conv(x, output_lengths)
>   File "/home/sbduser/anaconda3/envs/DS2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/sbduser/DeepSpeech/deepspeech2_pytorch/model.py", line 59, in forward
>     x = module(x)
>   File "/home/sbduser/anaconda3/envs/DS2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/sbduser/anaconda3/envs/DS2/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

Has this ever happened to you or do you know how could I solve it?
Thanks a lot for your work!!

**Comment by Kailegh** [comment]
I am running out of time today, I have avoided the error by using this:

```
            if args.mixed_precision:
                inputs = inputs.half()
```
I do not know if this ruins the training or not, but at least the training begins, I hope to give you more info tomorrow.

**Comment by SeanNaren** [comment]
sorry for the late fix, but could you re-train/load a model using https://github.com/SeanNaren/deepspeech.pytorch/pull/417? I wasn't saving the model's mixed precision flag hence the input wasn't being converted automatically
