### ISSUE TITLE
Incorrect CER calculation

### ISSUE THREAD

**Issue by buriy** [SeanNaren/deepspeech.pytorch#420]
Hi devs,
in the CER calculation, you remove blank space characters in levenshtein distance function, but still count the number of characters including the spaces in denominator.
```
def decoder_cer(s1, s2):
        s1, s2, = s1.replace(' ', ''), s2.replace(' ', '')
        return Lev.distance(s1, s2)

cer = decoder.cer(transcript, reference) / float(len(reference))
```

**For example, for "asd fgh" and "qwe rty" this will give you 0.85 not 1 (to ones who says "they share a common space, so 0.85 is correct here" -- remember we *planned* to ignore whitespaces!).**

**And what's worse, for "asdfgh" and "qwe rty" this will also give you 0.85 (they don't share a common space now!).**
So you might get 4% CER instead of 5.35% CER for AN4 dataset (33% difference), and so on.
For librispeech validation, CER 10% will usually become CER 10.5%, not a big difference, but still a very important moment when one tries to compare two different systems.

An obvious fix is
```
cer = decoder.cer(transcript, reference) / float(len(reference.replace(' ','')))
```

**Comment by nhh1501** [comment]
This will not be good when I ask questions here.
My results of pretrained model on Librispeech 
`!python test.py --test-manifest ./data/libri_test_clean_manifest.csv --model-path ./models/librispeech_pretrained.pth  --cuda`
test clean : Average WER 35.904	Average CER 13.584
other clean :Average WER 61.491	Average CER 28.430
I don't know what's the matter. Could you help me?

**Comment by archiki** [comment]
@buriy @SeanNaren @nhh1501  
Hi, Even I face the same issue in evaluation as @nhh1501 , I am using the code in v1.2 and the latest pre-trained model given. I didn't use the -- cuda command but other changes made are the same. 
Could anyone please help ?
