### ISSUE TITLE
RuntimeError: `lengths` array must be sorted in decreasing order when `enforce_sorted` is True.

### ISSUE THREAD

**Issue by Marcovaldong** [SeanNaren/deepspeech.pytorch#432]
I'm trying to train this model, however I got this error: 

```
Traceback (most recent call last):
  File "train.py", line 273, in <module>
    out, output_sizes = model(inputs, input_sizes)
  File "/disk2/dongsq/environments/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk2/dongsq/my/deepspeech.pytorch/model.py", line 217, in forward
    x = rnn(x, output_lengths)
  File "/disk2/dongsq/environments/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk2/dongsq/my/deepspeech.pytorch/model.py", line 96, in forward
    x = nn.utils.rnn.pack_padded_sequence(x, output_lengths)  # , enforce_sorted=False)
  File "/disk2/dongsq/environments/anaconda3/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 268, in pack_padded_sequence
    torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: `lengths` array must be sorted in decreasing order when `enforce_sorted` is True. You can pass `enforce_sorted=False` to pack_padded_sequence and/or pack_sequence to sidestep this requirement if you do not need ONNX exportability.
```

After I add `enforce_sorted=False` in [here](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/model.py#L96), there is no error and the code can be runned successfully. 

However, I cannot use multi gpus to train. I tried to configure some gpus by `os.environ["CUDA_VISIBLE_DEVICES"] = ','.join(map(str, [1,2,3]))`, the code will only use the first gpu. I don't know which part will influence this? @SeanNaren

**Comment by SeanNaren** [comment]
Are you using the multiproc.py script to do multi-GPU?

**Comment by Marcovaldong** [comment]
No, I used multi-gpu by configuring environment variable `os.environ["CUDA_VISIBLE_DEVICES"] = ','.join(map(str, [1,2,3]))` in train.py. Should I use multiproc.py? 

And is it normal to got that error? Should I added `enforce_sorted=False` in [here](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/model.py#L96)

**Comment by Marcovaldong** [comment]
@SeanNaren  Thanks for your reply. 

When using the multiproc.py script, I can train the model with multi-gpus. However, Should I must add `enforce_sorted=False` at [here](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/model.py#L96)
