### ISSUE TITLE
Failed To Setup Project

### ISSUE THREAD

**Issue by SibtainRazaJamali** [SeanNaren/deepspeech.pytorch#436]
I have followed installation instruction completely. 
No problem occurred while installing. 
But when running 
python train.py --help
There is an error
'RuntimeError: Failed to parse the argument list of a type annotation: name ‘Optional’ is not defined'
Pytorch Version is updated.

**Comment by buriy** [comment]
So, what would you do to debug it? :)

**Comment by SibtainRazaJamali** [comment]
Torch Audio library is producing this error.
I don't know how to remove this error.

**Comment by buriy** [comment]
If you googled for this error, you've found that there's a broken torchaudio version, you need to choose another one.

**Comment by SibtainRazaJamali** [comment]
i did find  a link but still couldn't run train command
this was link
https://github.com/pytorch/audio@d92de5b

**Comment by Kabur** [comment]
Just checkout to 788c81d124ab5d1f028864c51aa6292da3bc9d00 after cloning the audio library and keep installing from there. Necessary for pytorch>=1.1

**Comment by SeanNaren** [comment]
Torch Audio has been replaced in master with Scipy, highly suggest moving to master!
