### ISSUE TITLE
Any update on Kuberflow / Mixed / Distributed training?

### ISSUE THREAD

**Issue by igormq** [SeanNaren/deepspeech.pytorch#437]

**Comment by SeanNaren** [comment]
Sorry I've been a bit distracted/busy recently with other improvements for this library! Will hopefully try to get this done soon.

**Comment by igormq** [comment]
I am struggling trying to train the librispeech using 4 gpus (FP16, BS=32) =(. Hopefully, you can shed some light ! Waiting for the updates. Thank you @SeanNaren

**Comment by SeanNaren** [comment]
@igormq make a separate ticket with the issues you're running into, or if you have already made one let me know which one it is!

**Comment by igormq** [comment]
Sure, I will open another ticket. Thank you very much.
