### ISSUE TITLE
Alignments for long audio files

### ISSUE THREAD

**Issue by maggieezzat** [SeanNaren/deepspeech.pytorch#445]
I already trained a model, now I would like to use it to generate alignments to segment long audio files into few seconds long, what changes should I introduce to the decoder? I mean is there any method in ctcdecode that generates the alignments with the transcriptions?

**Comment by SeanNaren** [comment]
have a look at the [offsets](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/transcribe.py#L62) capability in the transcribe.py script, hopefully this can help!

**Comment by SeanNaren** [comment]
I'll close this for now but feel free to re-open if needs be
