### ISSUE TITLE
What kind of RTF should one expect?

### ISSUE THREAD

**Issue by migueljette** [SeanNaren/deepspeech.pytorch#45]
Hi there,

Just out of curiosity, what kind of RTF can one expect from your code?
I want to test it out, but I was curious to know ahead of time if the decoding is fairly fast.

Thank you!
Miguel

**Comment by SeanNaren** [comment]
Hey! What do you mean by RTF?

**Comment by migueljette** [comment]
Oh, sorry.
RTF = Real-Time Factor.
If RTF=1, then it would take 5 minutes to decode an audio of length 5 minutes.
If RTF=0.2, it would take 1 minute for the same audio.

I guess that number depends on hardware and size of models... but I wanted to get an idea of how fast it can decode.

**Comment by SeanNaren** [comment]
Good question! Probably something I could get for you. Are you interested in CPU time/GPU time? Multi-GPU support etc?

**Comment by migueljette** [comment]
At the end of the day, the real number i am interested in is the "real time" from a user standpoint. In a perfect world, for me, it would take 15-20 seconds to decode a 5 minutes audio (RTF=0.05-0.1).

But it would also be interesting to know how much of that time is spent using CPU and GPU. And what kind of optimizations can be done to speed things up (multi-GPU, etc).

Excuse my questions, but in order to decode, I imagine I absolutely need a GPU, right? Also, there must be a step for feature extraction that uses CPU before that.
Do you actually support using multi-GPU for decoding?
Thank you! I'm very interested!

**Comment by ryanleary** [comment]
You should read the deepspeech2 paper as it includes some practical information on making a deployment system. There are many different things that can be done to tune the real-time factor -- some of that hardware-dependent.

**Comment by migueljette** [comment]
Yes, I have read the paper, but I wasn't sure how much of the paper applied to this particular tool. So many pieces could be different than Baidu's implementation. :) But I guess I won't know until I give this a test... i'll try to find some time in the near future!

**Comment by ryanleary** [comment]
The current implementation will take a single utterance, do the forward/backwards passes through the RNN and then do a very simple greedy decode. So the decoder is about as simple as you can imagine (no language model, no beam search) and is therefore very fast. The forward/backward pass in the RNN can occur on either GPU or CPU. GPU, of course, will be faster.

There are no recipes defined just yet, so you as the end user can specify RNN size, RNN type, number of layers, you could even change the convolution layers. Modifying any of those parameters will change the RTF.

From there, other factors could affect RTF as well depending on how you want to use this thing? Are you talking about batch processing (offline)? Online/streaming? All of these things will levy different requirements, so without more information on HOW you want to use this system, it would be very challenging to concoct a number/benchmark to give you an answer there.

**Comment by migueljette** [comment]
Thanks for the comments!
That helps a lot! I didn't realize that there was no language model or beam search implemented. 
My use case is to use it as an offline transcriber (for now). This is helpful. It sounds like I need to test it out with my data and see what kind of pipeline I want to build.

**Comment by EgorLakomkin** [comment]
I am working on adding very simple beam search decoding with n-gram language model. Should be ready soon.

**Comment by SeanNaren** [comment]
Hey @EgorLakomkin hows that decoder coming along? Anything I can do to help (have a branch open?)

**Comment by EgorLakomkin** [comment]
Hi @SeanNaren, last week was pretty hectic, I will open the branch this week with what I achieved so far

**Comment by SeanNaren** [comment]
@EgorLakomkin No worries, thanks for the contributions thus far :D

**Comment by ryanleary** [comment]
I also have a WIP for a beam decoder, but my wife had a baby last week, making last week (and this) similarly hectic... I'll see if I can get a branch pushed at some point this week. Would love to collaborate to get something working and flexible with different kinds of language models and optional dictionaries.

**Comment by ryanleary** [comment]
I think we can close this. The short version is the RTF will be a function of hardware, whether or not you use the beam search decoder, and the size of your network.
