### ISSUE TITLE
python train.py:RuntimeError: Unexpected optimization level None

### ISSUE THREAD

**Issue by SunlerZRY** [SeanNaren/deepspeech.pytorch#452]
When I was trying to run train.py, I met this problem:
![image](https://user-images.githubusercontent.com/45224648/62948645-5a4c8400-be17-11e9-9bc3-457933b80262.png)
I am confused about usage of opt_level in this code. Could you help me to understand how opt_level  and args.opt_level work here?

**Comment by AlexandrMoruk** [comment]
Same problem

**Comment by triwoods** [comment]
@SunlerZRY 'opt_level' is coming from mix-precision training using Nvidia Apex package.
more details here:
https://nvidia.github.io/apex/

**Comment by SeanNaren** [comment]
I'll add some documentation around this, I'm not a big fan of how it's currently supported and I should add a default here. O0 is standard full precision training, please specify this for now and I'll make a PR to add a default! These can be seen here: https://nvidia.github.io/apex/amp.html#opt-levels-and-properties

**Comment by SunlerZRY** [comment]
@ AlexandrMoruk Have you solve the problem. I use ubuntu 16.0 , python 3.6 and Pytorch 1.0.  I'm not sure if there is any relation with the enviroment.

**Comment by AlexandrMoruk** [comment]
@SunlerZRY You have to add an option --opt-level O0 or another, where O is the letter of alphabet.
