### ISSUE TITLE
Mandarin Pretrained model

### ISSUE THREAD

**Issue by ykshi** [SeanNaren/deepspeech.pytorch#457]
Is anyone has Mandarin pretrained model of DeepSpeech2? Thank a lot for the help

**Comment by SeanNaren** [comment]
Hey! Sadly we do not have a mandarin pre-trained model. You may be interested in the PaddlePaddle repo which has a pre-trained mandarin model [here](https://github.com/PaddlePaddle/DeepSpeech#speech-model-released)
