### ISSUE TITLE
Getting Word level timestamps + confidence

### ISSUE THREAD

**Issue by Kartik14** [SeanNaren/deepspeech.pytorch#459]
Hi,

I am trying to get word level timestamps from transcribe.py using the --offset flag which gives character offset for the input. The comman I am using is as follows:

`python transcribe.py --model-path deepspeech.pytorch/deepspeech_final.pth --decoder beam --alpha 2 --beta 0.4 --beam-width 128 --lm-path 4-gram.binary --audio-path wav/common_voice_en_17300642.wav --offset`

It gives the following output:

>{"output": [{"transcription": "HOW CAN I TELL YOU THAT YOU ARE FIT ENOUGH TO JOIN THE CAMP", "offsets": [37, 38, 43, 48, 51, 52, 54, 65, 59, 65, 67, 68, 71, 71, 78, 80, 81, 83, 88, 90, 91, 92, 94, 97, 99, 100, 101, 105, 107, 109, 111, 113, 117, 118, 122, 125, 126, 129, 133, 136, 137, 139, 142, 144, 145, 149, 152, 153, 157, 159, 163, 164, 165, 166, 169, 171, 172, 180, 182]}], "_meta": {"acoustic_model": {"name": "deepspeech_final.pth"}, "language_model": {"name": "4-gram.binary"}, "decoder": {"lm": true, "alpha": 2.0, "beta": 0.4, "type": "beam"}}}

The transcription is correct, now I am trying to get word level timestamps in seconds for the audio file. From Readme:

>### **Time offsets**
>Use the --offsets flag to get positional information of each character in the transcription when using transcribe.py script. The offsets are based on the size of the output tensor, which you need to convert into a format required. For example, based on default parameters you could multiply the offsets by a scalar (duration of file in seconds / size of output) to get the offsets in seconds.

I am unable to understand what does the "size of output" exactly mean. I though it was 182 (largest value in offsets) but using it to extract words timestamps does not give the correct values. For example to get word HOW, I am taking start time as ``(37*4.2/182)`` and end time as ``(48*4.2/182)`` where 4.2 is the length of audio clip in seconds.

Can someone tell me what I am doing wrong? I have attached the audio file and word level forced alignment file for reference.

[common_voice_en_17300642.zip](https://github.com/SeanNaren/deepspeech.pytorch/files/3724108/common_voice_en_17300642.zip)

Also I was wondering if there is any way to get word level confidence values when using a beam-decoder? 

Any help will be appreciated. 
Thank you.

**Comment by SeanNaren** [comment]
You can only get character timestamps currently (but that can be converted into word based timestamps). I think to answer this I'll make the adjustments such that meaningful timestamps can be generated.

In terms of confidence values that's currently not support by this package!

**Comment by atifemreyuksel** [comment]
@SeanNaren is there any development in the latest version for producing meaningful timestamps for either characters or words in transcription generated?

If adjustment is not completed, can you describe the suitable way to get meaningful timestamps please?
