### ISSUE TITLE
Using `opt-level O0` causes RuntimeError on CPU

### ISSUE THREAD

**Issue by Anwarvic** [SeanNaren/deepspeech.pytorch#464]
I've downloaded the an4 dataset and ready to train a model using the following command:
```
python train.py --train-manifest data/an4_dataset/an4_train_manifest.csv --val-manifest data/an4_dataset/an4_val_manifest.csv
```
Which produces this error:
```
RuntimeError: Unexpected optimization level None. Options are 'O0', 'O1', 'O2', 'O3'.
 Note that in `O0`, `O1`, etc., the prefix O is the letter O, not the number zero.
```
So, as I understood from issue #452, you have to set a value as there is no default value for `opt-level`. So, I set `O0` as the optimization level and it shows this error:
```
RuntimeError: Found param conv.seq_module.0.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.
```
I don't understand what this means but my guess is it expects me to have Cuda on my machine. Is my guess is correct? And how to fix this problem?

**Comment by SeanNaren** [comment]
Thanks for making an issue, I guess CPU training is broken due to the AMP api. Before I mend this is CPU based training feasible for you?

**Comment by shamoons** [comment]
I assume CPU training doesn't work?

**Comment by SeanNaren** [comment]
It isn't easily supported it seems due to the apex wrapper, but I'm trying to understand where the use case is for CPU training!

**Comment by shamoons** [comment]
@SeanNaren for me, the CPU use case is for sanity checks. So I can run things locally before running it on GPUs (in the cloud). I figured out a fix that involves conditionally not running apex. I can PR it if you’re interested

**Comment by faboyds** [comment]
@shamoons Could you share your solution to train on the CPU?
