### ISSUE TITLE
error whein i install warp-ctc

### ISSUE THREAD

**Issue by fanguanghu** [SeanNaren/deepspeech.pytorch#472]
when i run make,errors occurs：
[ 11%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
nvcc fatal   : Could not open output file /warp-ctc/build/CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o.NVCC-depend
CMake Error at warpctc_generated_reduce.cu.o.cmake:207 (message):
  Error generating
  /warp-ctc/build/CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o

CMakeFiles/warpctc.dir/build.make:296: recipe for target 'CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o' failed
make[2]: *** [CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/warpctc.dir/all' failed
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by akashrajkn** [comment]
@fanguanghu I got a similar error. I replaced warp-ctc with PyTorch's [nn.CTCLoss](https://pytorch.org/docs/stable/nn.html#ctcloss) function.
