### ISSUE TITLE
problem with CTC beam decoder offsets 

### ISSUE THREAD

**Issue by spakhomov** [SeanNaren/deepspeech.pytorch#483]
I am experiencing an issue with the ctc beam decoder occasionally producing inconsistent offsets that are out of sequence. For example, here is a list of offsets that I got from the ctc decoder - label followed by offset:

W 43
A 45
Y 51
S 87
I 551
D 646
E 647
S 655
  656
C 657
R 660
I 663
B 664
E 682
  680
E 682
V 683
E 689
R 691
Y 694
T 699
H 700
I 701
N 702
G 703

Note that offset 682 is followed by 680 and then back to 682 on the next label. This happens multiple times in each file I test. For example, later in that same output, I got this:

H 6906
H 6906
  6904
T 6905
H 6906
A 6907
T 6908
' 6911
S 6913

Note where offset 6906 is repeated and then drops to 6904 on the blank label and 6905 on the T and back to 6906 on the following H. 

Running the exact same audio through the greedy decoder with the same network always returns offsets in increasing order. These "glitches" only show up when I use the ctc beam decoder. Here is the same segment as the first one above output by the greedy decoder:

W 43
A 45
  50
Y 51
O 53
U 54
  62
  76
O 79
  83
E 86
S 87
T 89
A 98
L 99
  148
O 151
K 158
A 160
  164
  172
  192
T 193
H 194
A 195
T 196
S 199
  200
A 250
  253
A 256
  262
T 263
A 266
E 514
  523
T 525
A 527
K 528
E 529
  532
A 535
  536
L 538
I 539
L 544
A 546
  548
B 549
I 551
  556
P 558
I 560
C 561
T 566
U 569
R 570
E 571
  632
A 635
N 636
D 637
  644
D 646
E 647
S 654
C 657
R 660
I 662
B 664
E 665
  680
E 682
V 683
E 689
R 691
Y 694
T 699
H 700
I 701
N 702

Has anyone experienced this issue? I am not even sure how to go about debugging it. It looks like something is getting derailed around the blank label...

Any ideas or pointers would be very much appreciated.

**Comment by kouohhashi** [comment]
Hi I'm getting same issue.
Have you solved this problem?
