### ISSUE TITLE
Bad word error (76.8) rate for single word audios

### ISSUE THREAD

**Issue by kapoorparul** [SeanNaren/deepspeech.pytorch#492]
Why is it that it performs badly on just  single words audio transcription task?

**Comment by farisalasmary** [comment]
Are your characters matches character inside `labels.json` file?

**Comment by kapoorparul** [comment]
My bad, some words had digits in their transcription. However, on removing all such errors also, I am getting WER of 61.8 and CER of 24.03. 
I am using LibriSpeech pre trained model.

**Comment by farisalasmary** [comment]
Are you trying to retrain the model or just use it for inference?

**Comment by kapoorparul** [comment]
just inference
