### ISSUE TITLE
Do the pretained models  use use_half?

### ISSUE THREAD

**Issue by shamoons** [SeanNaren/deepspeech.pytorch#493]
I see when loading the model, there's a mandatory `use_half` parameter:
https://github.com/SeanNaren/deepspeech.pytorch/blob/master/utils.py#L34

Is this set to `True` or `False` in the pretrained models?

**Comment by SeanNaren** [comment]
The pre-trained models uses mixed precision, so when evaluating/inference you should add the --half flag, which sets use_half to true

**Comment by shamoons** [comment]
Thanks
