### ISSUE TITLE
Can we modify this to accept more than just wav files?

### ISSUE THREAD

**Issue by shamoons** [SeanNaren/deepspeech.pytorch#495]
By using `soundfile`, we can also do `flac` and other formats. I'm happy to make a PR for this. @SeanNaren ?

**Comment by SeanNaren** [comment]
Definitely! More than happy to support this if it's straight forward.

**Comment by shamoons** [comment]
@SeanNaren PR up: https://github.com/SeanNaren/deepspeech.pytorch/pull/496

**Comment by SeanNaren** [comment]
Thanks! I'm just wondering if there is a training speed issue with using soundfile, is there anyway we can test this?

**Comment by shamoons** [comment]
What do you propose? I can run some tests.
-
Shamoon Siddiqui
MS, MBA, PhD (in progress)
"We are what we repeatedly do. Excellence, therefore, is not an act but a
habit."

**Comment by SeanNaren** [comment]
Do you know if given a wav file soundfile/scipy load the data the same way? i think that's the crucial check to make here

**Comment by shamoons** [comment]
They're not the exact same. But I swapped the order of `samples` and `sample_rate` as they are different
