### ISSUE TITLE
What are the inputs to the model?

### ISSUE THREAD

**Issue by shamoons** [SeanNaren/deepspeech.pytorch#499]
It looks like the size is: `torch.Size([3, 1, 161, 1343])`

So 3 is the batch size. 161 is the size of the spectrogram. 1343 is the sequence length. So what is the last 1?

**Comment by xieyidi** [comment]
I met the same problem

**Comment by SeanNaren** [comment]
The 1 is required as a number of channels to the convolutional layer!

**Comment by xieyidi** [comment]
the size of output is:torch.Size([32, 695, 2885])
what does 695 and 2885 represent?
What happens to the size of the data with BeamCTCDecoder function

**Comment by SeanNaren** [comment]
I assume you're using a batch size of 32, a character alphabet/sequence length of 695/2885?
