### ISSUE TITLE
How To Train with Ken-LM model?

### ISSUE THREAD

**Issue by wahyubram82** [SeanNaren/deepspeech.pytorch#500]
I try to build my own speech model and plan it to use deepspeeech.pytorch and ken-lm.
because it's more stable on my laptop...

but i don't found any clue how to use it.

if we build language model with ken-lm, i follow the instruction in https://tilmankamp.github.io/FOSDEM2018/

it will produce some file, esspecially binary file.

but consider the train.py script in deepspeech.pytorch, i don't have any clue, how to use it.

**Comment by SeanNaren** [comment]
The Ken-lm language model is trained separately from the acoustic model. Then at test/transcribe time they are combined! https://github.com/SeanNaren/deepspeech.pytorch#using-an-arpa-lm

**Comment by wahyubram82** [comment]
so, the result of deepspeech.pytorch is like phonem, that should decode with a lm, to make it 'readable' by humans?

**Comment by wahyubram82** [comment]
Mr. Sean, I try to understand the logic of DeepSpeech2.pytorch...
I really confuse when see other articel that they train only 20 epoch, and another system, eg: https://github.com/yao-matrix/deepSpeech2, need train until more than 10k epochs.

mine, use GPU MX-150 2GB, try to train 900 epochs, with 12 batch, not sure it's enough, or not enough, or even over enough. but after 19 hours (136 epochs), the transcription only look like this:

"AA A A AA AAAAAAA A AA AAAAAAA A AA AAAA AAAAAAA AAA AV"

how it should be?

I mean, did i need train until 10k epochs or maybe more, so the transcription will be 'readable',?

what i should do?

I try to build a new language model (Bahasa Indonesia), with the dataset from Mozilla Voice Common. If you have a good machine or access to it, can you provide the 'Bahasa Indonesia' model so I can used that model for transfer learning?
