### ISSUE TITLE
How are non-real words given in the transcription?

### ISSUE THREAD

**Issue by shamoons** [SeanNaren/deepspeech.pytorch#503]
I am using the pretrained model and the output is:
```
{"output": [{"transcription": "I WILL ASK THE LEAST IMAGINABLE BUT I MUST HAVE SOMEHIN"}], "_meta": {"acoustic_model": {"name": "librispeech_pretrained_v2.pth"}, "language_model": {"name": "3-gram.pruned.3e-7.arpa"}, "decoder": {"lm": true, "alpha": 1.97, "beta": 4.36, "type": "greedy"}}}
```

I ran it with:
```
python transcribe.py --model-path data/pretrained_models/librispeech_pretrained_v2.pth  --lm-path saved_models/3-gram.pruned.3e-7.arpa --decoder greedy --alpha 1.97 --beta 4.36 --beam-width 1024 --audio-path myfile.wav
```

So my issue is where did `SOMEHIN` come from. Isn't the point of the LM to ensure that only real words from the language are transcription candidates?

**Comment by raotnameh** [comment]
@shamoons do you have check if 'SOMEHIN' is in the LM vocab? 
also, if it is not, then in the decoder part change the value of OOV to something even higher than -1000.https://github.com/parlance/ctcdecode/blob/d4da7fa300d11cae0bc050489f8b51f4a939304d/ctcdecode/src/scorer.h#L16

**Comment by HandsLing** [comment]
@shamoons I think this issue happended because you are using "greedy" decoder, not the beam decoder.

**Comment by raotnameh** [comment]
@HandsLing True, just saw it.
