### ISSUE TITLE
server.py doesn't work with beam decoder and language model

### ISSUE THREAD

**Issue by yasersakkaf** [SeanNaren/deepspeech.pytorch#511]
Hi, I am using Beam decoder, I've updated it in opts.py and also updated the model paths properly.
Yes, I have installed all the necessary packages as mentioned in READMe.

I am using a pre-trained TEDLIUM acoustic model available here https://github.com/SeanNaren/deepspeech.pytorch/releases and pre-trained language 'model 4-gram.arpa' available here http://www.openslr.org/11/.

When I execute server.py I get the following error:
```
(v2t_new) root@cuda:/home/yaser/deepspeech.pytorch# python server.py
INFO:root:Setting up server...
Traceback (most recent call last):
  File "server.py", line 79, in <module>
    main()
  File "server.py", line 67, in main
    decoder = BeamCTCDecoder(model.labels, lm_path=args.lm_path, alpha=args.alpha, beta=args.beta,
  File "/home/yaser/deepspeech.pytorch/decoder.py", line 98, in __init__
    self._decoder = CTCBeamDecoder(labels, lm_path, alpha, beta, cutoff_top_n, cutoff_prob, beam_width,
  File "/root/miniconda3/envs/v2t_new/lib/python3.8/site-packages/ctcdecode/__init__.py", line 17, in __init__
    self._scorer = ctc_decode.paddle_get_scorer(alpha, beta, model_path.encode(), self._labels,
TypeError: paddle_get_scorer(): incompatible function arguments. The following argument types are supported:
    1. (arg0: float, arg1: float, arg2: str, arg3: List[str], arg4: int) -> capsule

Invoked with: 0.8, 1, b'models/4-gram.arpa', "_'ABCDEFGHIJKLMNOPQRSTUVWXYZ ", 29
```

When I use the greedy decoder without a language model, It works totally fine !!
Thanks in advance

**Comment by SeanNaren** [comment]
Thanks! Could you try this branch and tell me if it works for you? https://github.com/SeanNaren/deepspeech.pytorch/pull/512

**Comment by yasersakkaf** [comment]
Thanks for replying.
I made the necessary changes in decoder.py.

It works now.
Thanks once again !!!
