### ISSUE TITLE
ImportError: TkAgg

### ISSUE THREAD

**Issue by aadil-srivastava01** [SeanNaren/deepspeech.pytorch#517]
Docker Image does not have matplotlib dependency, I tried installing it, but after installation and on running training job I'm getting:

`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`.

![image](https://user-images.githubusercontent.com/13318820/81072182-61ff0c00-8f03-11ea-97fe-440691fcd4ae.png)

**Comment by XinyiJi1** [comment]
Hi! Have you solved this problem since I also met this problem and struggling...don't know how to solve this? :)

**Comment by aadil-srivastava01** [comment]
> Hi! Have you solved this problem since I also met this problem and struggling...don't know how to solve this? :)

Hi!!
You just have to remove the line `matplotlib.use('TkAgg')` in the file data/spec_augment.py & do a pip install matplotlib to get the latest version.
I will then work fine.

**Comment by XinyiJi1** [comment]
> > Hi! Have you solved this problem since I also met this problem and struggling...don't know how to solve this? :)
> 
> Hi!!
> You just have to remove the line `matplotlib.use('TkAgg')` in the file data/spec_augment.py & do a pip install matplotlib to get the latest version.
> I will then work fine.

Ok, got it! Thank you so so much!!! :)
