### ISSUE TITLE
What is the input format of the audio should be?

### ISSUE THREAD

**Issue by stereomatchingkiss** [SeanNaren/deepspeech.pytorch#520]
For transcription, what is the format of the audio should be? Like how many channels, sample rate, bit rate.

**Comment by kouohhashi** [comment]
It has to be like below now.
But other format may be included down the road.

- Format: wav
- Channel: single channel
- Sample rate: 16000

Thanks.

**Comment by raotnameh** [comment]
@stereomatchingkiss @kouohhashi  the sample rate could be different than 16000. It's just we have to mention it while training. 


Though, 16000 is preferred in the research community.
