### ISSUE TITLE
Odd transcription results

### ISSUE THREAD

**Issue by pbnsilva** [SeanNaren/deepspeech.pytorch#527]
Hello,

I'm trying to run `transcribe.py` with pre-trained librispeech model and the `3-gram.pruned.3e-7.arpa` language model:
```
python transcribe.py --model-path ~/data/stt/librispeech_pretrained_v2.pth --audio-path "~/data/stt/base.wav"
--lm-path ~/data/stt/3-gram.pruned.3e-7.arpa --decoder beam --alpha 1.97 --beta 4.36 --beam-width 1024
```

And the result I get:
```json
{"output": [{"transcription": "EVA ONES SHE OMASH"}], "_meta": {"acoustic_model": {"name": "librispeech_pretrained_v2.pth"}, "language_model": {"name": "3-gram.pruned.3e-7.arpa"}, "decoder": {"lm": true, "alpha": 1.97, "beta": 4.36, "type": "beam"}}}
```

The audio file is a very clear english sentence, but the transcription result isn't even english.

What am I missing? How should I debug this?

Thank you

**Comment by Bolaka** [comment]
@pbnsilva - hey was your issue solved?

**Comment by kerolos** [comment]
hello  @pbnsilva , @Bolaka did you guys able to get a readable transcription  after beam search decoding ?
thanks in advance.
