### ISSUE TITLE
Breaking Changes have been introduced in new commit!

### ISSUE THREAD

**Issue by harveenchadha** [SeanNaren/deepspeech.pytorch#533]
Hi,

I tried training on the an4 dataset using new code pushed 3 days back, the WER failed to decrease from 40 in 50 epochs I trained.

![image](https://user-images.githubusercontent.com/30959215/83148349-7a370500-a116-11ea-9649-e69261831c5d.png)

**Comment by SeanNaren** [comment]
This is an issue will need to spend some time investigating...

**Comment by SeanNaren** [comment]
Seems like using a much smaller batch size helps a lot, setting the batch-size to 8 has helped. I would suggest trying AdamW (`--adam`) if you'd like to keep the batch size high, however AN4 is a very small dataset.
