### ISSUE TITLE
Question on released model

### ISSUE THREAD

**Issue by arunarn2** [SeanNaren/deepspeech.pytorch#534]
This is not really an issue. Just had some questions on the released models. 
I wanted to know if the released models are cumulative or was the AN4 model (released [here](https://github.com/SeanNaren/deepspeech.pytorch/releases/download/v2.0/an4_pretrained_v2.pth))trained just on the AN4 dataset, similarly the case with LibriSpeech and Ted datasets. Also it is possible to know how many epochs the model was trained for to achieve the reported WER reported on the release notes pages. 

Thanks

**Comment by SeanNaren** [comment]
The model have just be trained on their sole dataset, no cumulation I'm afraid!

On the actual epoch that the model was selected for, this was chosen based on the validation results. The AN4 dataset is ridiculously small, so it's probably not that important which model we choose but is good enough for just ensuring our model works.

I plan to make a few changes such that if you pass the model to a script, it will return all that information for you in a readable format! Will include that in release notes in due time.
