### ISSUE TITLE
Issues with --decoder beam

### ISSUE THREAD

**Issue by meharbhatia** [SeanNaren/deepspeech.pytorch#541]
Hello, I am facing this issue while using beam decoder. It works with greedy decoder though.

Traceback (most recent call last):
  File "test.py", line 104, in <module>
    half=args.half)
  File "test.py", line 42, in evaluate
    decoded_output, _ = decoder.decode(out, output_sizes)
  File "****/decoder.py", line 144, in decode
    out, scores, offsets, seq_lens = self._decoder.decode(probs, sizes)
  File "****/lib/python3.6/site-packages/ctcdecode/__init__.py", line 55, in decode
    output, timesteps, scores, out_seq_len)
TypeError: paddle_beam_decode(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: List[str], arg3: int, arg4: int, arg5: int, arg6: float, arg7: int, arg8: int, arg9: int, arg10: at::Tensor, arg11: at::Tensor, arg12: at::Tensor, arg13: at::Tensor) -> int

**Comment by SeanNaren** [comment]
Could you try re-installing ctcdecode from master? there was a few changes made which may fix this

**Comment by SeanNaren** [comment]
Open this issue if you've not fixed this...
