### ISSUE TITLE
Why not simply use torch.nn.CTCLoss instead Warp-CTC?

### ISSUE THREAD

**Issue by dertilo** [SeanNaren/deepspeech.pytorch#551]
are there benchmarks of [warp-ctc](https://github.com/SeanNaren/warp-ctc) vs. pytorch's implementation? I [reproduced](https://github.com/dertilo/speech-recognition) your [results](https://github.com/SeanNaren/deepspeech.pytorch/releases) with pytorch's implementation, so I ask myself what could have been the motivation for using warp-ctc?

**Comment by SeanNaren** [comment]
Hey! It's probably in a decent state however there are many bugs within torch's native CTC such as this: https://github.com/pytorch/pytorch/issues/17798
