### ISSUE TITLE
Integrate PyTorch Lightning

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/deepspeech.pytorch#568]
I've been pretty skeptical about high level PyTorch libraries to reduce boilerplate, but PyTorch Lightning seems to be the real deal and a good long term solution for support! (more info [here](https://github.com/PyTorchLightning/pytorch-lightning)).

Integration will include a bunch of fixes I'd like to make as well, which will break backwards compatibility. This means a new model iteration will need to be done but it's overdue.

To make sure I don't miss anything here's a checklist:

- [x] Feature parity in training/testing/loading models
- [x] Save/Load models during training using the same exposed checkpointing parameters
- [x] Ensure GCS based checkpointing is included
- [x] Add Trains/Visdom custom logging module (seems there is already integration for Trains [here](https://github.com/PyTorchLightning/pytorch-lightning-bolts) after speaking to @williamFalcon)
- [x] Update README/Instructions for scaling, validate scaling parameters including data samplers etc

Final Steps:

- [ ] Final model iteration across all datasets, and potentially a combined dataset if we can find someone with resources!

**Comment by SeanNaren** [comment]
I'm seeing some regressions in the accuracy using AN4 and just want to finish this up.

Also blocking integration is lack of models + waiting for the next PyTorch release to handle native AMP support for RNNs.

**Comment by williamFalcon** [comment]
we also support apex. (users have both options)

**Comment by SeanNaren** [comment]
@williamFalcon thanks! I'm kinda hoping PyTorch 1.6.1 comes out soon enough so I never have to worry about apex installation ever again...

**Comment by williamFalcon** [comment]
oh lol. haha. that’s a good point :)

**Comment by SeanNaren** [comment]
Going to create a separate ticket to track the models required for the new release.
