### ISSUE TITLE
No module named deepspeech_pytorch.opts

### ISSUE THREAD

**Issue by usernaamee** [SeanNaren/deepspeech.pytorch#570]
When running **search_lm_params.py** as prescribed in the README, we are trying to import add_decoder_args from deepspeech_pytorch.opts, which does not exists. I assume that the API might have changed. Can you suggest the alternative? I'd be happy to submit a pull request.

**Comment by SeanNaren** [comment]
Eek, I probably need to fix this since a lot has changed and this file might've been left out... more than happy for you to have a look if you're interested in fixing, might be able to get to it soon
