### ISSUE TITLE
Bangla transcription output : \u09a6\u09b6\u09a8 \u09a6\u09be\u09a4\u09cd\u09b0

### ISSUE THREAD

**Issue by jongli747** [SeanNaren/deepspeech.pytorch#573]
I change the labels.json file like this - [ "অ","আ","ই","ঈ","উ"....]
After training the model transcription is like this - \u09a6\u09b6\u09a8

I have no idea what is happening.
What should I do?

Thanks

**Comment by kouohhashi** [comment]
Are you using transcribe.py?
If so you can use `print(results)` instead of `print(json.dumps(results))`?
json.dumps may cause the conversion.

**Comment by jongli747** [comment]
@kouohhashi Thanks! It worked.
