### ISSUE TITLE
possible bug in usage of beam-decoder outputs

### ISSUE THREAD

**Issue by levhaikin** [SeanNaren/deepspeech.pytorch#575]
it seems that the `scores` of the beams retrieved in the following line are not used anywhere:
https://github.com/SeanNaren/deepspeech.pytorch/blob/916e560468eaa367a54e6f8bb6597b1b41fde7cb/deepspeech_pytorch/decoder.py#L146
downstream, in the following line:
https://github.com/SeanNaren/deepspeech.pytorch/blob/916e560468eaa367a54e6f8bb6597b1b41fde7cb/deepspeech_pytorch/testing.py#L80
the first beam is taken regardless of the decoder being used (greedy/beam). for greedy, this is fine as there is only one "beam" anyway. however, for beam-decoder, why is it true that the first one is also the highest scoring beam? shouldn't the `scores` (from above) be used to decide where the highest scoring beam is located, or are they assumed to be sorted? (I actually saw in a particular test run that they are **not** sorted descending by scores)  

am I missing anything?

**Comment by SeanNaren** [comment]
Hey @levhaikin I'm also certain ctcdecode sorts the beams by their score: https://github.com/parlance/ctcdecode/blob/master/ctcdecode/src/ctc_beam_search_decoder.cpp#L188

this however is different to the score that is returned:

https://github.com/parlance/ctcdecode/blob/master/ctcdecode/src/ctc_beam_search_decoder.cpp#L206

after all this time I'm still uncertain why this is score is returned and not the raw beam score...

**Comment by levhaikin** [comment]
it looks like this code removes the "scorer" (language-model) scores from the total score. perhaps there were some bug with that related to numerical stability. the inline comment is a hint: 
`// compute aproximate ctc score as the return score, without affecting the
  // return order of decoding result. To delete when decoder gets stable.`

I looked in the original implementation in PaddlePaddle/DeepSpeech. looks like it didn't change for three years...

thanks for the clarification @SeanNaren
