### ISSUE TITLE
New Pytorch Lightning Pre-trained Models Release

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/deepspeech.pytorch#576]
Within #568 and #569 are a bunch of fixes and clean ups that open a lot of doors in terms of integration.

The integration deprecates many old paradigms and cleans up a lot of unnecessary boilerplate however requires a model refresh to ensure pre-trained models exist before merge.

I'm up for discussion on what models we should train, however my compute is limited till I purchase a better GPU, **so any assistance in running models would be appreciated**!

**Instructions to Run**

Requires PyTorch 1.7. This will become a hard requirement for running AMP due to PyTorch 1.7 RNN AMP support.

```bash
git checkout feature/lightning

cd data/
python an4.py # Run corresponding dataset script
cd ../
python train.py +configs=an4.yaml # Swap this to whatever config you want to train, saves best validated model

# Examples for other datasets, ensure to use the data/<dataset>.py script to download the data first
python train.py +configs=librispeech.yaml # Swap this to whatever config you want to train, saves best validated model
python train.py +configs=tedlium.yaml # Swap this to whatever config you want to train, saves best validated model
```

Code supports multi-GPU. To use just add `trainer.gpus=X` to the command. I'm happy to accept any community made models, if you do modify the config please just add the modifications you made :)

**Required Models**

- [x] AN4
- [x] LibriSpeech
- [x] TEDLium

**Comment by piraka9011** [comment]
I can help with running models. Have access to an RTX 3090 and (for now) a V100 GPU.

**Comment by SeanNaren** [comment]
Hey @piraka9011!! Thanks so much :) I've updated the lightning branches with a lot of changes and I'll be starting training on LibriSpeech using the set configs. I've also updated the issue above.

So feel free to train a model using Tedlium or commonvoice!

**Comment by piraka9011** [comment]
Is training with the `ddp` configs necessary btw especially since I only have 1 GPU?
Been also having issues installing `fairseq` (Something to do with `ninja -v` command not working during build...), so I just commented out that config.

**Comment by SeanNaren** [comment]
Not essential! Just helps to speed up the training process :)

**Comment by SeanNaren** [comment]
I've trained a LibriSpeech model finally performs slightly poorer than the previous release (less than a point difference) and given the time taken the train (whilst I'm not trying to replicate any results in particular) this is fine.

I'll start training the other models ASAP.

Also I've had time to mull it over, I think the people really want a useable model rather than academic models.

This came out recently: http://www.openslr.org/94/ from FB, which really is mostly an english LibriVox dump that they've gone through and processed which is awesome. Given what i've seen before, adding this + some other datasources should get us a reasonable model that can work for most use cases (not the best though). If I can find a reasonable way to train this, I think this should be the highlight model of the release.

**Comment by SeanNaren** [comment]
I've removed common voice from the pre-trained model tracker, and after release will work on a combined common voice/LibriSpeech multilingual (but just the english portion, since its extremely skewed) model!

**Comment by SeanNaren** [comment]
I've got pre-trained models for the minimum now, we're good to go :)
