### ISSUE TITLE
About boosting accuracy for keywords or phrases

### ISSUE THREAD

**Issue by kouohhashi** [SeanNaren/deepspeech.pytorch#577]
HI, 
Some speech-to-text engine accept keywords to increase probability of picking that words.

Since Assemblyai, which is one of deepspeech2 descendant, has such feature, I think deepspeech-based model can utilize such keywords to boost accuracy.

But I have no idea how to do that.

Could someone give me a hint?
Or could someone give me url to learn?

Thanks in advance.

And this is nothing to do with deepspeech itself... sorry about that.

**Comment by hajix** [comment]
Hi
A beam search on raw network output will help to find keywords more accurately. This will be done in decoding step and could be parallelized with  parlance ctcdecode. FST based search methods also help gain performance.
