### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by OmarHory** [SeanNaren/deepspeech.pytorch#578]
I want to know the difference between both of these sections of data augmentation.
Which one should I use?

![daaug](https://user-images.githubusercontent.com/43903002/94286198-57e6b400-ff5d-11ea-9d23-964f06e754e2.png)

Thanks!

**Comment by SeanNaren** [comment]
That looks like a mistake to me, there should be only one... where did you get this from?

**Comment by OmarHory** [comment]
I have no idea honestly...
I followed the installation instructions as the readme.
If it is a mistake, where the augmentation section should be? under the 'data' or independent?

**Comment by OmarHory** [comment]
Thank you Sean, I just changed the train_config.py default values to ensure that the augmentation configuration is set.

I am closing the issue, thanks.

**Comment by SeanNaren** [comment]
Awesome, thanks @OmarHory! I think longer term we'll need to be a bit clearer where to specify parameters, will see if I can create an issue to encapsulate this
