### ISSUE TITLE
Confidence scores

### ISSUE THREAD

**Issue by BlackIsTheNewBlack** [SeanNaren/deepspeech.pytorch#582]
Hello Sean,

First, thanks for all the great work! It is very inspiring.

I would like to sponsor a new feature: word level confidence scores. AWS and Azure have them, they are a pretty useful metric.
Ideally, they would work like probabilities, ie be normalized [0, 1) so, for example, we can flag all undecidable words. As it is, the model is perfectly happy to output garbage text from garbage audio and some kind of sanity check would be useful.

Can you please PM me an estimate?

Thanks!

**Comment by OmarHory** [comment]
Any progress with this?
