### ISSUE TITLE
Librispeech dataset

### ISSUE THREAD

**Issue by siddu9501** [SeanNaren/deepspeech.pytorch#590]
What dataset is used for the DS2 librispeech model? 

I see that the data/librispeech.py file contains argument (max_duration) that prunes the audio segments longer than 15 seconds. Is there a reason why it is kept so?

**Comment by SeanNaren** [comment]
DS2 uses a culmination of datasets, with hard sequence lengths in place (usually 15 seconds hence why it's in the script!). The paper has a lot of info: https://arxiv.org/abs/1512.02595

The hard length is to reduce memory overhead, longer sequences can cause us to run into OOM easily!
