### ISSUE TITLE
Using Pytorch CTCLoss instead of warp-ctc

### ISSUE THREAD

**Issue by piraka9011** [SeanNaren/deepspeech.pytorch#596]
Is there any interest in using the builtin Pytorch [`CTCLoss`](https://pytorch.org/docs/stable/generated/torch.nn.CTCLoss.html#torch.nn.CTCLoss) as opposed to the warp-ctc one linked in the README?

I've made the changes on a local branch and can merge upstream if this is of interest.
I think it's better to remove the dependency on an external repo and use something that is actively maintained by the PyTorch team.

**Comment by kouohhashi** [comment]
Sounds great because it seems PyTorch CTCLoss is stable now.

**Comment by SeanNaren** [comment]
Yes! I should have time this week to finish off the move to Pytorch Lightning + refractors like this :)

**Comment by SeanNaren** [comment]
This has been done in #568
