### ISSUE TITLE
Make model traceable

### ISSUE THREAD

**Issue by avramandrei** [SeanNaren/deepspeech.pytorch#599]
Hi,

I am trying to create a traceable model using `torch.jit.trace`. However, the following part of the model in MaskConv is not is not traceable, mainly because you are converting some tensors to python integers/boolean values (e.g. `mask[i].size(2)` gets converted to Python int).

```
mask = torch.BoolTensor(x.size()).fill_(0)
if x.is_cuda:
    mask = mask.cuda()
for i, length in enumerate(lengths):
    length = length.item()
    if (mask[i].size(2) - length) > 0:
        mask[i].narrow(2, length, mask[i].size(2) - length).fill_(1)
x = x.masked_fill(mask, 0)
```

Could you suggests another implementation alternative that is traceable? I am trying to serve the model in a batch-inference enable environment, so I believe that this masking is important (else if I had a single batch, I could simply ignore it, no?).

Thank you,
Andrei

**Comment by kouohhashi** [comment]
I comment out the part below and it works since the batch size of my inference input is always 1.

```
for i, length in enumerate(lengths):
    length = length.item()
    if (mask[i].size(2) - length) > 0:
        mask[i].narrow(2, length, mask[i].size(2) - length).fill_(1)
```

If you need to handle batch datasets, I think you can pad them before input them into your model to make it work.
I know this is not cool but still it work...
