### ISSUE TITLE
MaskConv is not traceable

### ISSUE THREAD

**Issue by avramandrei** [SeanNaren/deepspeech.pytorch#600]
Hi,

I am trying to create a traceable model using `torch.jit.trace`. However, the following part of the model in MaskConv is not traceable, mainly because some tensors gets converted to python integers/boolean values (e.g. `mask[i].size(2)` tensor gets converted to Python int in `narrow(2, length, mask[i].size(2) - length)`).

```
for i, length in enumerate(lengths):
    length = length.item()
    if (mask[i].size(2) - length) > 0:
        mask[i].narrow(2, length, mask[i].size(2) - length).fill_(1)
```

Could you suggests another implementation alternative that is traceable? I am trying to serve the model in a batch-inference enable environment, so I believe that this masking is important (else if I had a single batch, I could simply ignore it, no?).

Thank you,
Andrei

**Comment by SeanNaren** [comment]
This is annoying. Unfortunately I had to add this module to make sure that padding was correctly being added after each Convolution layer, which requires knowing the original lengths.

**Comment by avramandrei** [comment]
Hmm, I understand. Is there any way in which this could be fixed? 

I need this feature to improve the inference latency. Maybe I can ignore masking all together if I use a batch size of 1. What do you think?
