### ISSUE TITLE
Language Model Effect (Alpha, beta)

### ISSUE THREAD

**Issue by OmarHory** [SeanNaren/deepspeech.pytorch#606]
Is there a way to make my DeepSpeech Model depend only on the language model (more of a closed domain)?
From my experience that Alpha and Beta parameters are responsible to do such thing, is there a way to always let Deep speech only take the probability scores that are in the Language model? Does setting alpha to 1 does the job? because in my case it doesn't as on some occurrences it takes probabilities that are out of the model not the LM.

Thanks in advance!

**Comment by SeanNaren** [comment]
The alpha and beta value are used to control the importance of the Language Model, have you tried much higher weights than 1 for the alpha/beta?
