### ISSUE TITLE
Windows OS Support

### ISSUE THREAD

**Issue by ccuiyuhan** [SeanNaren/deepspeech.pytorch#610]
can the project be runed on windows？

**Comment by SeanNaren** [comment]
I'm actually not sure... I know PyTorch can be installed on windows, and given Lightning is tested, I don't see why not! I think certain things do not work on Windows but error messages should come up.

**Comment by vinson2233** [comment]
In `data_loader.py`, change the audio backend into : 
```
torchaudio.set_audio_backend("soundfile")
```
