### ISSUE TITLE
LibriSpeech MLS (English Only) + CommonVoice

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/deepspeech.pytorch#611]
Combining LibriSpeech MLS (English Only) and CommonVoice EN should create a model reasonable for speech recognition across data outside the training distribution.

However that's roughly 50k hours (I think) to train on. This will take time, and resources to train!

- [ ] Create dataset preparation script for LibriSpeech MLS (http://www.openslr.org/94/)
- [ ] Create formatted dataset on drive/s3
- [ ] Train model

If anyone can help it would be super appreciated.

**Comment by piraka9011** [comment]
> Create formatted dataset on drive/s3

How are you thinking of formatting the data?
via the CSV or as a single tar file to download? and where?

**Comment by SeanNaren** [comment]
hey man!

I actually don't no what's the best thing to do. In a perfect world I'd format the data and let people download it, but given the file size I don't think that's possible :(

I think more likely is I format the data and train via a local drive, with a manifest file/local file system. Then pre-trained weights for all!

Given I've trained models like this before, it shouldn't take more than 4/8 V100s for 4/5 days.
