### ISSUE TITLE
Should training use FileCheckpointHandler or CheckpointHandler

### ISSUE THREAD

**Issue by piraka9011** [SeanNaren/deepspeech.pytorch#612]
I noticed `FileCheckpointHandler` is not used anywhere.
Is that intended? 

I think [this](https://github.com/SeanNaren/deepspeech.pytorch/blob/master/deepspeech_pytorch/training.py#L26) should reference `FileCheckpointHandler` and not the base `CheckpointHandler`.

I also discovered this becuase I had to add `dirpath` and `filename` keys to the `checkpoint` key in the config files. (see the new PTL hydra-configs).

**Comment by SeanNaren** [comment]
Lol yes it should no idea how the code worked 😂 would you be able to make a PR for this?
