### ISSUE TITLE
Model inference: mistakes in README

### ISSUE THREAD

**Issue by NikolaiBabkin** [SeanNaren/deepspeech.pytorch#617]
Since PyTorch Lightning was integrated, this doesn’t work anymore:

python test.py model.model_path=**models/deepspeech.pth** test_path=**/path/to/test_manifest.csv**

Instead _models/deepspeech.pth_ should be path to PyTorch Lightning Checkpoint, something like _outputs/YYYY-MM-DD/HH-MM-SS/_dirpath_/***.ckpt_

Also, train_manifest, val_manifest, test_manifest store in _.json_ format

Probably this one doesn’t work either 
![image](https://user-images.githubusercontent.com/38789010/107068962-2c13ee80-67d9-11eb-8345-cb50ddb2c890.png)

All in all there is a lot to change in README to make it consistent with recent V3 release and PyTorch Lightning integration.

**Comment by SeanNaren** [comment]
ugh I've been so lazy. I'll try get time to clean this up ASAP, apologies here!

**Comment by NikolaiBabkin** [comment]
Thank you!

**Comment by yaser-sakkaf** [comment]
Hi Sean, know you are busy but it would be great if someone from your side worked on updating the README.
