### ISSUE TITLE
AN4 pre-trained model

### ISSUE THREAD

**Issue by NikolaiBabkin** [SeanNaren/deepspeech.pytorch#618]
Link to pre-trained model AN4 doesn’t work.
https://github.com/SeanNaren/deepspeech.pytorch/releases/download/v3.0/an4_pretrained_v3.ckpt

**Comment by SeanNaren** [comment]
Fixed thanks man! Small error: 

https://github.com/SeanNaren/deepspeech.pytorch/releases/download/V3.0/an4_pretrained_v3.ckpt

Should be fine now :)
