### ISSUE TITLE
Missing mandatory value: checkpoint.dirpath

### ISSUE THREAD

**Issue by NikolaiBabkin** [SeanNaren/deepspeech.pytorch#619]
While calling `python train.py` with some config,
the following error can occur:
_omegaconf.errors.MissingMandatoryValue: Missing mandatory value: checkpoint.dirpath_
this is the result of the bag in https://github.com/romesco/hydra-lightning.
While this pull request in progress https://github.com/romesco/hydra-lightning/pull/17,
the issue chan be manually fixed in three ways:

1. by changing:
`dirpath: Any = MISSING` => `dirpath: Any = None` 
in _ModelCheckpointConf, site-packages/hydra_configs/pytorch_lightning/callbacks.py_

2. Adding in _config_name_.yaml
```
checkpoint:
    dirpath: some_path
```

3. `python train.py +checkpoint.dirpath = some_path`

**Comment by jade0520** [comment]
Hi I have a same error when I run train.py and I found your issue where you wrote the manual solutions thankfully.
but I have a little problem with step 2, could you help me please?

I have two questions :
can I just add yaml file of **any name** to **any folder**?
and some_path means literally **any path**? is this path not going to be used for this code?  or is that path for saving checkpoints?

Thanks!

**Comment by NikolaiBabkin** [comment]
Hi!

This issue https://github.com/romesco/hydra-lightning/pull/17 closed, so if you still have the error, you probably should update `hydra-lightning` library.

> can I just add yaml file of any name to any folder?

Yes, you can. But you should pay attention how you going to send it to `train.py`. You better put it to the `configs` folder, then to train model with this config you should just run ` python train.py +configs= config_name`

> and some_path means literally any path? is this path not going to be used for this code? or is that path for saving checkpoints?

With https://github.com/romesco/hydra-lightning/pull/17 closed, by default checkpoints stored in `outputs/YYYY-MM-DD/HH-MM-SS/lightning_logs/version_0/checkpoints`

If you add to config:
```
checkpoint:
    dirpath: checkpoints_dir
```
then checkpoints stored in `outputs/YYYY-MM-DD/HH-MM-SS/checkpoints_dir`

**Comment by jade0520** [comment]
Thank you for your help and nice explanation!

Then, I gotta update hydra-lightning first :)
And your reply for my questions are helping me a lot for understanding the code thanks again!
