### ISSUE TITLE
Read cvs file error?

### ISSUE THREAD

**Issue by hujunyao** [SeanNaren/deepspeech.pytorch#639]
when train input file is csv, it complains error. We find the errors come from following code. when input_path is file , it reads the file as json file ,but actually it is cvs file .

in https://github.com/SeanNaren/deepspeech.pytorch/blob/master/deepspeech_pytorch/loader/data_loader.py
...
def _parse_input(self, input_path):
        ids = []
        if os.path.isdir(input_path):
...
        else:
            # Assume it is a manifest file
            with open(input_path) as f:
                manifest = json.load(f)  <------ SHOULD READ CVS file according class comments.
..........

**Comment by Makabongwe-Nkabinde** [comment]
Hi, you can use the option of giving the directories that contain your training files and validation files.

**Comment by madprogramer** [comment]
[Release V3.0](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/V3.0) seems to have discontinued .csv's in favor of .json :

> Move towards json structure for manifest files

Documentation on _how_ to format the json manifest files is non-existent at this time, so if you need to just feed in your .csv's as soon as possible consider downgrading to [V2.1](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/V2.1)

**Comment by madprogramer** [comment]
The issue can be closed now I think?
