### ISSUE TITLE
how long does it take to achieve the accurate 

### ISSUE THREAD

**Issue by li-xx-5** [SeanNaren/deepspeech.pytorch#641]
hello, i wanna ask how long does it take to train the model to achieve the accurate.

**Comment by li-xx-5** [comment]
@SeanNaren. hello,how many steps does it take to train the model to achieve a better result.Thank you.

**Comment by SeanNaren** [comment]
Hey! I report epochs etc in the configs here for the pre-trained models: https://github.com/SeanNaren/deepspeech.pytorch/tree/master/configs

Hard for me to define how many steps to fine-tune onto your data however :)
