### ISSUE TITLE
Very high WER on custom testing-data

### ISSUE THREAD

**Issue by madprogramer** [SeanNaren/deepspeech.pytorch#645]
While evaluating the [V3.0](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/V3.0) pre-trained models, on a subsample of [EmoV-DB](https://github.com/numediart/EmoV-DB) (N= ~280) I saw some pretty ridiculous error rates when running `test.py`: 

![image](https://user-images.githubusercontent.com/3719664/117120677-4e97b280-ad9c-11eb-903c-76a9ce38d5f4.png)

I thought WER was supposed to be a percentage (between 0 and 100), is something wrong with the precision?

**Comment by SeanNaren** [comment]
WER can actually be higher than 100 as it isn't a percentage per say, but in most cases you can treat it as such.

is EmoV-DB a subset of one of these models? These models will not perform well on data outside of their domain, i.e for librispeech which was trained on audio books, it would do well transcribing audio books.

Hoping #611 will be the answer to having a model that can perform well on a larger set of audio :)

**Comment by madprogramer** [comment]
No it's probably very much outside the domain. (Though it is similar to AN4, with isolated sentences)
