### ISSUE TITLE
noise inject

### ISSUE THREAD

**Issue by li-xx-5** [SeanNaren/deepspeech.pytorch#646]
hello，when i want to inject the noise wav, i use the command line 
python3 noise_inject.py --input-path /home/lix/deepspeech2/data/an4_dataset/train/an4/wav/an100-mskh-b.wav --noise-path /home/lix/deepspeech2/1.wav --output-path /home/lix/deepspeech2/output.wav --noise-level 0.5

TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
how can i inject the noise wav, thank you.

**Comment by Emegua** [comment]
Would you mind explaining how you fixed the issue?
