### ISSUE TITLE
Error occur  after running this commend python "train.py data.train_path=data/train_manifest.json data.val_path=data/val_manifest.json" 

### ISSUE THREAD

**Issue by rahadarmannabid** [SeanNaren/deepspeech.pytorch#648]
Error occur  after running this commend python "train.py data.train_path=data/train_manifest.json data.val_path=data/val_manifest.json" 

Traceback (most recent call last):
  File "train.py", line 21, in hydra_main
    train(cfg=cfg)
  File "/home/ran/deepspeech.pytorch/deepspeech_pytorch/training.py", line 26, in train
    cfg=cfg.checkpoint
  File "/home/ran/deepspeech.pytorch/deepspeech_pytorch/checkpoint.py", line 26, in __init__
    prefix=cfg.prefix
TypeError: __init__() got an unexpected keyword argument 'prefix'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
(base) ran@ran-desktop:~/deepspeech.pytorch$

**Comment by kanuarj** [comment]
Even I'm facing the same error, although I tried ```export  HYDRA_FULL_ERROR=1``` before and later tried running. Yet the same issue persists. Went through this issue in general and found out there is a method overriding somewhere.
