### ISSUE TITLE
Not able to load the saved Checkpoints

### ISSUE THREAD

**Issue by kanuarj** [SeanNaren/deepspeech.pytorch#654]
I have came across an error pertaining to load the checkpoints. 
My checkpoints are saved in `/outputs/2021-06-23/17-59-11/lightning_logs/version_0/checkpoints/epoch=N-step=N.ckpt` path.
But when I try the command :
`python train.py trainer.resume_from_checkpoint=lightning_logs/deepspeech_checkpoint_epoch_N_iter_N.ckpt` to load them I get an error. I solved the EOF error of name and also tried yet I get the error as 
```
/home/User/anaconda3/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:68: UserWarning: No checkpoint file exists at `resume_from_checkpoint`. Start from scratch
```
I even tried full path.
Any suggestions ?

**Comment by uygarrr** [comment]
hey I believe I guess terminal can't interpret the file name correctly. I encountered similar error during inference. Just rename the *.ckpt file and try again. By the way did you do any inference so far?

**Comment by kanuarj** [comment]
I did tried that. Yet it restarts from beginning. There was an issue with naming conventions while being saved with = sign which I did renamed manually and gave the path too.

**Comment by kanuarj** [comment]
> hey I believe I guess terminal can't interpret the file name correctly. I encountered similar error during inference. Just rename the *.ckpt file and try again. By the way did you do any inference so far?
