### ISSUE TITLE
Question about data shuffling

### ISSUE THREAD

**Issue by liangsusan-git** [SeanNaren/deepspeech.pytorch#676]
https://github.com/SeanNaren/deepspeech.pytorch/blob/075a69ae66aa284c5c5a954c6c15efe6d56898dd/deepspeech_pytorch/loader/data_loader.py#L305

Hi Sean,

I was wondering if this line is necessary -- would shuffling samples within a batch make any difference?

**Comment by SeanNaren** [comment]
I don't think it does, I think this is an archaic thing I left in when sequence lengths were not appropriately taken into consideration; i.e the model would predict on padding which is very sub-optimal. This could probably be removed :)

**Comment by liangsusan-git** [comment]
Okay, thanks.
