### ISSUE TITLE
cant train!

### ISSUE THREAD

**Issue by Chenwe111** [SeanNaren/deepspeech.pytorch#677]
when i use python train.py +configs=an4, it has an error!!!
How can i do ?

Error merging checkpoint=file
Invalid type assigned : ModelCheckpointConf is not a subclass of ModelCheckpointConf. value: {'_target_': 'pytorch_lightning.callbacks.ModelCheckpoint', 'filepath': None, 'monitor': None, 'verbose': False, 'save_last': None, 'save_top_k': 1, 'save_weights_only': False, 'mode': 'min', 'dirpath': None, 'filename': None, 'auto_insert_metric_name': True, 'every_n_train_steps': None, 'train_time_interval': None, 'every_n_epochs': None, 'save_on_train_epoch_end': None}
        full_key: 
        reference_type=Optional[DeepSpeechConfig]
        object_type=DeepSpeechConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by SeanNaren** [comment]
Eek! seems like things have broken. I'm going to make a parent issue because I think it's time I refresh this library, amazed people still use it 😂
