### ISSUE TITLE
mismatch in supported batch size between benchmarking script and actual training script

### ISSUE THREAD

**Issue by SiddGururani** [SeanNaren/deepspeech.pytorch#68]
Hi! I'm playing around with deepspeech with the Librispeech dataset. Initially, when I blindly ran the training script with a large batch size I ran into an out-of-memory error, as expected.

So then I checked the largest sequence length in the librispeech data(around 2900 for my the default audio config) and ran the benchmarking script with --seconds 30. Turns out I can only support a batch size of 10. But when I let my model train using this batch-size I run into an OOM error in the final few batches.

Why is this the case? Since the benchmarking script is testing the exact same model configuration (I'm going with the default config) with random input data of size larger than any of the batches in Librispeech, shouldn't it run to completion?

**Comment by SeanNaren** [comment]
We actually run into this internally, my guess is there is additional buffers (maybe from the loss function i.e warp-ctc) that causes this issue. A trick I use is switching over to the CPU implementation of the loss function to try prevent this. What I'm going to do is make a branch of the code that does this, could you test that branch for me to see if the problem still persists? Will hopefully open it tomorrow...

**Comment by SiddGururani** [comment]
Sure, I'm still only testing stuff out so I can run a test with the new branch. Will keep an eye out for that.
Thanks! 
(turns out the sweet spot for my hardware is a batch-size of 7)

**Comment by SeanNaren** [comment]
Interesting, what GPU are you using? I've opened a branch here, could you let me know if it allows you to use a batch size similar to the benchmark script?

https://github.com/SeanNaren/deepspeech.pytorch/tree/cpu-ctc

**Comment by SiddGururani** [comment]
I'm using a GTX 970 with 4 GB memory. I'll most likely be able to test this out only on Tuesday but I'll definitely let you know when I do.

**Comment by SiddGururani** [comment]
So I did end up running the cpu-ctc branch and I still wasn't able to get a higher batch size to work. 
Also, previously I didn't factor in memory requirement for validation because it never got to the end of the epoch. The batch size that I was able to use without running into OOM errors with the master branch turned out to be a whopping 3. Almost stochastic.

One thing that I learned from this process is that I should probably test whether the chosen hyperparams work using the single largest batch from the training data and the largest validation batch.

**Comment by SiddGururani** [comment]
I have one question with regards to memory usage.
Should I be running into OOM issues if my model runs through several epochs without any problems? I feel like the answer should be no but I ran an experiment last night to compare two different architectures, one wider and one deeper, and they both ran out of memory during validation after the 4th and the 3rd epoch respectively.

This issue isn't really the same as the original one but is related. Should I open another issue for this?

**Comment by ryanleary** [comment]
I've had some OOM issues as well and just thought of another thing to keep in mind: If using the `--augment` flag, the tempo changes will change the length of the audio.

So for librispeech, for example, the longest audio length in the corpus is something on the order of 36 seconds. If that longest example happens to be augmented with a tempo of 1.15, the length then is about 41.5 seconds. This obviously has major implications on the possible batch size (and isn't explicitly captured within the benchmark script).

**Comment by SiddGururani** [comment]
Thanks for pointing that out. I hadn't considered that. I'm not using augmentation in my current runs but this  info will help me in the future when I do.

**Comment by SiddGururani** [comment]
Should we assume that the mismatch has to do with 2 facts?:
1. The validation set might have a batch with sequence length larger than the largest batch in the training set.
2. There may be extra buffers in warp-CTC which aren't being accounted for during benchmarking. (I'm still a little suspicious about this because the loss is being computed during training too)

The fact that memory use varies across epochs is also a little suspect since I usually leave my training to run overnight with no load on the GPU other than the model training. But that should probably be another issue.

If the aforementioned are acceptable reasons for the issue, we can probably close this issue.

**Comment by SeanNaren** [comment]
On number 2, that's why I was hoping using the CPU based loss calculation meant that we avoid the additional buffers, but sadly it still unstability!

I'll keep this ticket open because a solution should be found :) A dirty solution that may work is to replicate a dataset in the benchmark script from the lowers size to the highest size, and iterate through that a few times.

**Comment by ryanleary** [comment]
I think this may be addressed now by the calls to `del loss` and `del out` on each minibatch iteration.

**Comment by SeanNaren** [comment]
That's awesome, will evaluate this and close!
