### ISSUE TITLE
About omegaconf.errors.ValidationError: Unexpected object type: tuple at train_config.py

### ISSUE THREAD

**Issue by Esthesia** [SeanNaren/deepspeech.pytorch#684]
I have a question regarding to the configuration setting errors with hydra.

> Traceback (most recent call last):
>   File "train.py", line 12, in <module>
>     cs.store(group="optim", name="adam", node=AdamConfig)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/hydra/core/config_store.py", line 85, in store
>     cfg = OmegaConf.structured(node)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 123, in structured
>     return OmegaConf.create(obj, parent, flags)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 179, in create
>     flags=flags,
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 882, in _create_impl
>     format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 793, in format_and_raise
>     _raise(ex, cause)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 771, in _raise
>     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 848, in _create_impl
>     flags=flags,
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 111, in __init__
>     format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 793, in format_and_raise
>     _raise(ex, cause)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 771, in _raise
>     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 94, in __init__
>     self._set_value(content, flags=flags)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 649, in _set_value
>     raise e
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 646, in _set_value
>     self._set_value_impl(value, flags)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 676, in _set_value_impl
>     data = get_structured_config_data(value, allow_objects=ao)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 481, in get_structured_config_data
>     return get_dataclass_data(obj, allow_objects=allow_objects)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 410, in get_dataclass_data
>     node=dummy_parent, key=name, value=value, cause=ex, msg=str(ex)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
>     _raise(ex, cause)
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 771, in _raise
>     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/_utils.py", line 406, in get_dataclass_data
>     parent=dummy_parent,
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 1075, in _maybe_wrap
>     key=key,
>   File "/opt/conda/envs/py37/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 1052, in _node_wrap
>     raise ValidationError(f"Unexpected object type: {type_str(ref_type)}")
> omegaconf.errors.ValidationError: Unexpected object type: tuple
>     full_key: betas
>     object_type=AdamConfig

I tried to solve with Customizing the OmegaConfig and change the Adam optimizer configuration but failed. 
Do you have any idea to solve this?

**Comment by fabianoluzbr** [comment]
https://github.com/SeanNaren/deepspeech.pytorch/issues/683

**Comment by Esthesia** [comment]
Thanks for notifying it!
