### ISSUE TITLE
Noise injection - files used

### ISSUE THREAD

**Issue by aaronzira** [SeanNaren/deepspeech.pytorch#69]
What sorts of durations are folks using for injected noise files? Any ideas on whether it's likely to be problematic if the ~2000 files I'm using are all less than one second?

**Comment by SeanNaren** [comment]
I think this opens up a good issue in noise data curation. Currently it's pretty blindfire which it shouldn't be. Would it make sense to make a script that takes in a noise file/input file, mixes them up with a specific SNR and outputs it for listening purposes?

**Comment by SeanNaren** [comment]
I've made a branch that gives a noise injection script to test out different input files and noise files, so you can audibly hear how they would sound. Let me know if that's helpful for you to make your decision!

You'll need to reinstall the audio library so:

```
pip uninstall audio
git clone https://github.com/SeanNaren/audio-1.git
cd audio
python setup.py install
```

```
git pull
git checkout noise-inject-script
```

Follow the instructions [here](https://github.com/SeanNaren/deepspeech.pytorch/tree/noise-inject-script) to run!
