### ISSUE TITLE
Error while executing training script

### ISSUE THREAD

**Issue by anindyasarkarIITH** [SeanNaren/deepspeech.pytorch#77]
I have got following error:
ImportError: /usr/local/lib/python2.7/dist-packages/torch/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/nitin/warp-ctc/build/libwarpctc.so)

I installed pytorch from pip ,my current gcc version is 4.9..

**Comment by SiddGururani** [comment]
The way I got around that was that I searched for libgomp.so.1 in usr/lib/gcc/5 and placed a symbolic link to that file in the torch/lib folder. I'm not really sure if that's the best solution but that's what did it for me. 
For good measure, I've also kept a backup of the original libgomp.so.1 which was in the torch/lib directory.

**Comment by ryanleary** [comment]
For whatever reason, pytorch is distributing their own libgomp with pytorch. It seems this often conflicts with whatever's built into the system (version-wise). So when you build warp-ctc with a different version from the one provided with pytorch and then warp-ctc is installed, when it's instantiated, it tries to load the libgomp.so from pytorch (which is now in the classpath) and not the one it was built with.

**Comment by SeanNaren** [comment]
My suggestion is install pytorch from source or release by following [this](https://github.com/SeanNaren/deepspeech.pytorch/issues/13#issuecomment-303386763) based on what was said above.
