### ISSUE TITLE
flags --visdom and --continue_from break the code

### ISSUE THREAD

**Issue by SiddGururani** [SeanNaren/deepspeech.pytorch#79]
I was in the process of introducing Tensorboard logging when I noticed bugs in how visdom was dealing with continuing from a checkpoint model.

Essentially, there are two bugs that I found and fixed.

- The variable `epoch` is being incremented wrongly inside the visdom logging section in line 289 of train.py
- When loading the `loss_results, wer_results, cer_results` from the `package`, the current statement assigns the variables directly from the dictionary. However, these variables are shorter buffers that only contain the results until the checkpoint epoch. Since they were assigned directly, the three variables are no longer of length = `args.epochs` and therefore give an `IndexError` when they are eventually accessed.

I've fixed these bugs and also added tensorboard logging in my fork: https://github.com/SiddGururani/deepspeech.pytorch

Shall I submit a pull request and we can discuss the tensorboard logging part in further detail there?

**Comment by SeanNaren** [comment]
That sounds good to me! When it comes to tensorboard logging, as long as its optional (much like visdom logging) that would be fine!

**Comment by ryanleary** [comment]
@SiddGururani I pulled down your tensorboard integration and tested it with a quick an4 training. Big +1. I was planning on doing the same thing. Works great. I added a flush to the writes though.

**Comment by ryanleary** [comment]
Thanks for the contrib @SiddGururani. This is great.

**Comment by SiddGururani** [comment]
Thanks guys! I'm gonna go ahead and close this.
