### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cdj0311** [SeanNaren/deepspeech.pytorch#8]
When run "python train.py", there is an error appeared: "Segmentation fault (core dumped)."

**Comment by SeanNaren** [comment]
Hey could i get more info? Maybe what OS/install you've done?

**Comment by SeanNaren** [comment]
I'll close this for now, if you are still having issues feel free to re-open

**Comment by igormq** [comment]
I'm having the same issue. Python 2.7, latest torch version, Ubuntu 16.04 on 2 GTX 1080. =)

**Comment by mikeXwang** [comment]
So do I.
When I import torch,this error happened.
