### ISSUE TITLE
Language model to predict.py

### ISSUE THREAD

**Issue by mit456** [SeanNaren/deepspeech.pytorch#86]
I am very new in this field, I ran `train.py` on librispeech dataset after complete training I ran `test.py` as following - 

`python test.py --model_path models/deepspeech_final.pth.tar --val_manifest data/libri_test_manifest.csv --cuda` 

I got following output:
`Validation Summary    Average WER 3.972    Average CER 0.747`

One more thing I noticed in `test.py` argument is `--val_manifest`, that is validation manifest file, But I think it should be `--test_manifest`?

Now I wanted to test the same model on unseen data using `predict.py`, but how do I include language model?

**Comment by ryanleary** [comment]
This is being tracked in #76.

**Comment by mit456** [comment]
I didn't notice, closing.

**Comment by SeanNaren** [comment]
You are correct about the `val_manifest` argument, will fix!

**Comment by mit456** [comment]
Can I fix and put a PR?

**Comment by SeanNaren** [comment]
@mit456 Already done, check the master branch :) but thanks for the help!

**Comment by SiddGururani** [comment]
As an aside, @mit456 I'm curious about the hyperparameters that you chose for the model that you trained. If you could share that with me, that would be very helpful. A WER of 3-4% on librispeech test sounds amazing!

**Comment by mit456** [comment]
@SiddGururani I didn't change much, I increased `--epochs` from 70 to 80.

**Comment by ryanleary** [comment]
@mit456 Did you train with all of the default parameters (model size/layer count/rnn type)? What kind/how many GPUs did you use?

**Comment by mit456** [comment]
I am using Telsa K80, But does it matter I mean quality of GPU?

**Comment by ryanleary** [comment]
No I was just curious. That's a surprisingly good model. Was curios of the architecture and how long it took to train.

**Comment by SeanNaren** [comment]
Yeah @mit456 any chance we could see the model (upload it somewhere?) because thats an incredibly low WER!

**Comment by mit456** [comment]
Where do I upload (Any option)? It seems to be 87Mb file.

**Comment by SeanNaren** [comment]
@mit456 which dataset was this? I assume this isn't the entire librispeech training set (including around 1000 hours)?

**Comment by mit456** [comment]
@SeanNaren I think I did training on full librispeech dataset.

In `librispeech.py` this is the list of Urls:

`LIBRI_SPEECH_URLS = {`
      `"train": ["http://www.openslr.org/resources/12/train-clean-100.tar.gz",`                                                                             
              `"http://www.openslr.org/resources/12/train-clean-360.tar.gz",`
              `"http://www.openslr.org/resources/12/train-other-500.tar.gz"],`

     "val": ["http://www.openslr.org/resources/12/dev-clean.tar.gz",
            "http://www.openslr.org/resources/12/dev-other.tar.gz"],

    "test": ["http://www.openslr.org/resources/12/test-clean.tar.gz",
             "http://www.openslr.org/resources/12/test-other.tar.gz"

`}`

I checked one more thing, Number of wav files in training dataset i.e equal to `281242`. Please confirm if that's the number for 1000 hours.

Thanks

**Comment by SeanNaren** [comment]
That does sound like the entire dataset to me which is incredibly surprising. In the librispeech_dataset folder could you run `find . -name "*.wav" | xargs soxi -D | paste -sd+ - | bc` and tell me what the output is? I just want to first verify you used the entire dataset and it correctly trained. 

Also could you run the `test.py` script on that model, with the param for `test_manifest` being the `librispeech_test_manifest.csv` and give the output WER/CER?

**Comment by mit456** [comment]
Outputs: 

1. `find . -name "*.wav" | xargs soxi -D | paste -sd+ - | bc`  = `3536310.271085`. What is the command doing after calculating the time using `soxi -D`? Just curios?

2. `test.py` is throwing error in current `master` branch

Error:
`Traceback (most recent call last):`
  `File "test.py", line 22, in <module>`
    `model = DeepSpeech.load_model(args.model_path, cuda=args.cuda)`
  `File "/vmdata/mithun/deepspeech.pytorch/model.py", line 128, in load_model`
    `model.load_state_dict(package['state_dict'])`
  `File "/vmdata/mithun/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 332, in load_state_dict`
   ` .format(name))`
`KeyError: 'unexpected key "rnns.0.batch_norm.module.weight" in state_dict'`


I tried going to some older commit and running `test.py` and giving the result -
`Validation Summary 	Average WER 3.972	Average CER 0.747`

I can take a look why is it failing in current master branch.

**Comment by ryanleary** [comment]
That seems too good. Did you add the test data into the training set per chance?

Also, the load is failing because the model architecture changed slightly. A workaround is adding 
```        for k, v in package['state_dict'].copy().items():
            if k.startswith('rnns.0.batch_norm.'):
                del package['state_dict'][k]```
in `model.py:load_model` immediately before the `model.load_state_dict(package['state_dict'])` line.

**Comment by SeanNaren** [comment]
@mit456 any chance you could send me the exact command you left running?

**Comment by mit456** [comment]
@SeanNaren Are you asking the training command? 

This is the command I ran and left running in screen - 
`python train.py --train_manifest data/libri_test_manifest.csv --val_manifest data/libri_val_manifest.csv --cuda --checkpoint`

@ryanleary Thanks I will add the workaround and try.

**Comment by mit456** [comment]
@SeanNaren Should I try training again and check if anything wrong I did? I will keep this model somewhere.

**Comment by SeanNaren** [comment]
@mit456 that's interesting, was thinking that you may have accidentally done `--train_manifest data/libri_val_manifest.csv` instead... If you could do the workaround that @ryanleary posted and get us testing results this will help us a lot!

**Comment by ryanleary** [comment]
It looks like you trained on the test set. (and then tested on the test set), hence the unusually good results (and fast training time). the `--train_manifest` flat should point to the training set (`data/libri_train_manifest.csv`), not `data/libri_test_manifest.csv`.

**Comment by SiddGururani** [comment]
I was also concerned that the data might have been all the Librispeech data including the validation and the test data but judging by the command that he ran, it doesn't seem that way.
@ryanleary How did you find that he trained using the test set?

**Comment by ryanleary** [comment]
The comment he posted with the training command before the edit showed `python train.py --train_manifest data/libri_test_manifest.csv ...`.

**Comment by mit456** [comment]
I agree. My bad, I did the mistake, sorry for misleading you guys. :( 

I am running again with this:

`python train.py --train_manifest data/libri_train_manifest.csv --val_manifest data/libri_val_manifest.csv --cuda --checkpoint`

I will post the results. 

Thanks

**Comment by SiddGururani** [comment]
It's cool, man. It was most likely a typo. Glad you were able to find the problem because otherwise this model would seem deceptively good but would perform poorly with new data.

**Comment by SeanNaren** [comment]
Hehe don't feel bad, made the same mistake a while ago as well :) glad to have found the issue!
