### ISSUE TITLE
Python 3: DeepSpeech.PyTorch X PyTorch Audio

### ISSUE THREAD

**Issue by dlmacedo** [SeanNaren/deepspeech.pytorch#93]
I am getting the following error when trying Python 3.6:

```
Traceback (most recent call last):
  (...)
  File "/home/dlm/code/deepspeech.pytorch/data/data_loader.py", line 17, in load_audio
    sound, _ = torchaudio.load(path.encode('utf-8'))  # py3 fix
  File "/home/dlm/anaconda3/lib/python3.6/site-packages/torchaudio-0.1-py3.6-linux-x86_64.egg/torchaudio/__init__.py", line 26, in load
    func(bytes(filename, "ascii"), out, sample_rate_p)
TypeError: encoding without a string argument

```

**Comment by marcoleewow** [comment]
I got the same error too when I tried to run train.py with Python 3.5. 
I fixed it by deleting `.encode('utf-8')` in the line  `sound, _ = torchaudio.load(path.encode('utf-8'))  # py3 fix` in `deepspeech.pytorch/data/data_loader.py`.

**Comment by dlmacedo** [comment]
https://github.com/pytorch/audio/issues/5

**Comment by dlmacedo** [comment]
We need to figure out if we should change Pytorch Audio or DeepSpeeach.Pytorch.

**Comment by SiddGururani** [comment]
I got the same error when I did a fresh clone and installation so I reverted to the old torchaudio for now.
