### ISSUE TITLE
Infinity loss warning (received an inf loss, setting loss value to 0)

### ISSUE THREAD

**Issue by aaronzira** [SeanNaren/deepspeech.pytorch#94]
The following was produced during a run on 1000+ hours of proprietary data merged with TED, using an architecture of 5x1024 (but with insertion of a third conv2d layer à la the DS2 paper), but has been observed with other such (smaller) merged datasets, as well as TED alone with different architectures, none of the others having made use of the third conv2d. In what type of situation is this expected to occur? I'm guessing it has something to do with the effect of the convolutions on very short audio files, but I'm not sure. Part of the reason I suspect this is that I have only observed the message during the early minibatches of an epoch. On this particular run it did not cause major problems, but on others it has progressed to the point where most batches display the warning until the run simply crashes.

```
Learning rate annealed to: 0.000064
Epoch: [12][1/38287]    Time 1.292 (0.820)      Data 0.942 (0.002)      Loss 48.0788 (32.5879)
Epoch: [12][2/38287]    Time 0.360 (0.820)      Data 0.000 (0.002)      Loss 31.5731 (32.5879)
Epoch: [12][3/38287]    Time 0.324 (0.820)      Data 0.000 (0.002)      Loss 63.3200 (32.5880)
Epoch: [12][4/38287]    Time 0.323 (0.820)      Data 0.000 (0.002)      Loss 38.4442 (32.5880)
Epoch: [12][5/38287]    Time 0.335 (0.820)      Data 0.002 (0.002)      Loss 58.3626 (32.5881)
Epoch: [12][6/38287]    Time 0.326 (0.820)      Data 0.003 (0.002)      Loss 42.6859 (32.5881)
Epoch: [12][7/38287]    Time 0.342 (0.820)      Data 0.000 (0.002)      Loss 60.4953 (32.5882)
WARNING: received an inf loss, setting loss value to 0
Epoch: [12][8/38287]    Time 0.333 (0.820)      Data 0.001 (0.002)      Loss 0.0000 (32.5881)
Epoch: [12][9/38287]    Time 0.502 (0.820)      Data 0.002 (0.002)      Loss 51.2113 (32.5881)
Epoch: [12][10/38287]   Time 0.331 (0.820)      Data 0.002 (0.002)      Loss 34.3016 (32.5881)
```

**Comment by SeanNaren** [comment]
The usual suspect is that you have very short files, and transcripts that are longer than the resulting sequence length of the tensors. This usually ends in an infinite loss. I'm deciding whether it would be a good idea to add a warning message, if this appears.

**Comment by naveenss1995** [comment]
@SeanNaren  can you specify the audio frame width you have used? I am training with a data filtered by syallables per second (<7) and still getting infinite loss, and i didnt want to remove observations with a charachters per second ,lest the model be inexperienced to syllables having large number of words.
