### ISSUE TITLE
Error while compiling training script...  

### ISSUE THREAD

**Issue by anindyasarkarIITH** [SeanNaren/deepspeech.pytorch#96]
While executing training.py I am getting following error: 

 File "/home/anindya/Documents/Projects/deep_speech_pytorch/deepspeech.pytorch-master/data/data_loader.py", line 17, in load_audio
    sound, _ = torchaudio.load(path)  # py3 fix      sound, _ = torchaudio.load(path.encode('utf-8'))
  File "build/bdist.linux-x86_64/egg/torchaudio/__init__.py", line 26, in load
    func(bytes(filename, "ascii"), out, sample_rate_p)
TypeError: str() takes at most 1 argument (2 given)
********************
Attached screen shot in which I can't find the file in highlighted section.

![screenshot from 2017-06-20 17_46_34](https://user-images.githubusercontent.com/20046403/27332909-83451ade-55e1-11e7-994e-ebe1e27dce3a.png)

**Comment by SeanNaren** [comment]
Repull the master branch, fixed in #97

**Comment by anindyasarkarIITH** [comment]
Sorry I forgot to mention that I am using python 2.7. The mentioned link is for python 3 and anyways I followed that but didn't work. I was getting same error.

**Comment by SeanNaren** [comment]
Can't replicate this on my end, are you using the latest version for `torchaudio` and for deepspeech?

**Comment by SeanNaren** [comment]
Fix has been pushed (here)[https://github.com/pytorch/audio/pull/6] for the audio library!

**Comment by anindyasarkarIITH** [comment]
Thanks man it's working as I executed in python 3.

**Comment by SeanNaren** [comment]
This was merged into the audio library, pull master and re-install the pytorch audio library to fix :)
